import type { ConfigDeListagem } from '@/componentes/comuns/PaginaDeListagem';

const telas: Record<string, ConfigDeListagem> = {
  '/cadastros/empresas': {
    titulo: 'Empresas',
    descricao: 'Empresas do grupo cadastradas no sistema.',
    textoNovo: 'Nova empresa',
    colunas: [
      { titulo: 'Razão social', larga: true },
      { titulo: 'Nome fantasia' },
      { titulo: 'CNPJ' },
      { titulo: 'Cidade' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Rorainópolis Empreendimentos Imobiliários Ltda', 'Rorainópolis Lotes', '12.345.678/0001-90', 'Boa Vista', { selo: { texto: 'Ativa', tom: 'ok' } }],
      ['Norte Terras Loteadora S.A.', 'Norte Terras', '23.456.789/0001-01', 'Boa Vista', { selo: { texto: 'Ativa', tom: 'ok' } }],
      ['Caracaraí Desenvolvimento Urbano Ltda', 'CDU Empreendimentos', '34.567.890/0001-12', 'Caracaraí', { selo: { texto: 'Ativa', tom: 'ok' } }],
      ['Serra do Sol Incorporadora Ltda', 'Serra do Sol', '45.678.901/0001-23', 'Palmas', { selo: { texto: 'Inativa', tom: 'neutro' } }],
      ['Vale do Cerrado Loteamentos Ltda', 'Vale do Cerrado', '56.789.012/0001-34', 'Goiânia', { selo: { texto: 'Ativa', tom: 'ok' } }],
    ],
  },
  '/cadastros/filiais': {
    titulo: 'Filiais',
    descricao: 'Unidades e filiais vinculadas às empresas do grupo.',
    textoNovo: 'Nova filial',
    colunas: [
      { titulo: 'Nome', larga: true },
      { titulo: 'Empresa' },
      { titulo: 'CNPJ' },
      { titulo: 'Cidade' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Filial Boa Vista Centro', 'Rorainópolis Empreendimentos Imobiliários Ltda', '12.345.678/0002-71', 'Boa Vista', { selo: { texto: 'Ativa', tom: 'ok' } }],
      ['Filial Rorainópolis', 'Rorainópolis Empreendimentos Imobiliários Ltda', '12.345.678/0003-52', 'Rorainópolis', { selo: { texto: 'Ativa', tom: 'ok' } }],
      ['Filial Caracaraí', 'Caracaraí Desenvolvimento Urbano Ltda', '34.567.890/0002-03', 'Caracaraí', { selo: { texto: 'Ativa', tom: 'ok' } }],
      ['Filial Cuiabá', 'Vale do Cerrado Loteamentos Ltda', '56.789.012/0002-15', 'Cuiabá', { selo: { texto: 'Ativa', tom: 'ok' } }],
      ['Filial Palmas', 'Serra do Sol Incorporadora Ltda', '45.678.901/0002-04', 'Palmas', { selo: { texto: 'Inativa', tom: 'neutro' } }],
    ],
  },
  '/cadastros/loteamentos': {
    titulo: 'Loteamentos',
    descricao: 'Loteamentos registrados junto aos empreendimentos.',
    textoNovo: 'Novo loteamento',
    colunas: [
      { titulo: 'Nome', larga: true },
      { titulo: 'Cidade' },
      { titulo: 'Matrícula' },
      { titulo: 'Lotes', numerico: true },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Residencial Rio Branco', 'Boa Vista', '48.512', 320, { selo: { texto: 'Aprovado', tom: 'ok' } }],
      ['Jardim das Palmeiras', 'Rorainópolis', '22.104', 180, { selo: { texto: 'Aprovado', tom: 'ok' } }],
      ['Vila Nova Caracaraí', 'Caracaraí', '15.987', 96, { selo: { texto: 'Em análise', tom: 'info' } }],
      ['Recanto dos Ipês', 'Boa Vista', '48.998', 210, { selo: { texto: 'Aprovado', tom: 'ok' } }],
      ['Portal do Cerrado', 'Goiânia', '77.321', 450, { selo: { texto: 'Pendente', tom: 'atencao' } }],
    ],
  },
  '/cadastros/empreendimentos': {
    titulo: 'Empreendimentos',
    descricao: 'Empreendimentos imobiliários da carteira.',
    textoNovo: 'Novo empreendimento',
    colunas: [
      { titulo: 'Nome', larga: true },
      { titulo: 'Loteamento' },
      { titulo: 'Cidade' },
      { titulo: 'Unidades', numerico: true },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Rio Branco Fase 1', 'Residencial Rio Branco', 'Boa Vista', 160, { selo: { texto: 'Em obras', tom: 'info' } }],
      ['Rio Branco Fase 2', 'Residencial Rio Branco', 'Boa Vista', 160, { selo: { texto: 'Planejamento', tom: 'atencao' } }],
      ['Jardim das Palmeiras Único', 'Jardim das Palmeiras', 'Rorainópolis', 180, { selo: { texto: 'Concluído', tom: 'ok' } }],
      ['Portal do Cerrado Fase 1', 'Portal do Cerrado', 'Goiânia', 225, { selo: { texto: 'Em obras', tom: 'info' } }],
      ['Vila Nova Caracaraí Único', 'Vila Nova Caracaraí', 'Caracaraí', 96, { selo: { texto: 'Suspenso', tom: 'vencido' } }],
    ],
  },
  '/cadastros/quadras': {
    titulo: 'Quadras',
    descricao: 'Quadras cadastradas dentro dos empreendimentos.',
    textoNovo: 'Nova quadra',
    colunas: [
      { titulo: 'Identificação' },
      { titulo: 'Empreendimento', larga: true },
      { titulo: 'Lotes', numerico: true },
      { titulo: 'Área total (m²)', numerico: true },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Quadra A', 'Rio Branco Fase 1', 24, 7200, { selo: { texto: 'Disponível', tom: 'ok' } }],
      ['Quadra B', 'Rio Branco Fase 1', 18, 5400, { selo: { texto: 'Disponível', tom: 'ok' } }],
      ['Quadra 03', 'Jardim das Palmeiras Único', 30, 9000, { selo: { texto: 'Esgotada', tom: 'neutro' } }],
      ['Quadra C', 'Portal do Cerrado Fase 1', 22, 6600, { selo: { texto: 'Disponível', tom: 'ok' } }],
      ['Quadra 01', 'Vila Nova Caracaraí Único', 16, 4800, { selo: { texto: 'Bloqueada', tom: 'critico' } }],
    ],
  },
  '/cadastros/corretores': {
    titulo: 'Corretores',
    descricao: 'Corretores autônomos e vinculados às imobiliárias parceiras.',
    textoNovo: 'Novo corretor',
    colunas: [
      { titulo: 'Nome', larga: true },
      { titulo: 'CRECI' },
      { titulo: 'CPF' },
      { titulo: 'Cidade' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Marcos Antônio Ferreira', 'CRECI-RR 1245', '111.222.333-44', 'Boa Vista', { selo: { texto: 'Ativo', tom: 'ok' } }],
      ['Juliana Beatriz Souza', 'CRECI-RR 987', '222.333.444-55', 'Boa Vista', { selo: { texto: 'Ativo', tom: 'ok' } }],
      ['Carlos Eduardo Nascimento', 'CRECI-TO 342', '333.444.555-66', 'Palmas', { selo: { texto: 'Ativo', tom: 'ok' } }],
      ['Fernanda Lima Rocha', 'CRECI-GO 5521', '444.555.666-77', 'Goiânia', { selo: { texto: 'Inativo', tom: 'neutro' } }],
      ['Ricardo Alves Pereira', 'CRECI-RR 764', '555.666.777-88', 'Rorainópolis', { selo: { texto: 'Ativo', tom: 'ok' } }],
    ],
  },
  '/cadastros/parceiros': {
    titulo: 'Parceiros',
    descricao: 'Imobiliárias e empresas parceiras na comercialização.',
    textoNovo: 'Novo parceiro',
    colunas: [
      { titulo: 'Nome', larga: true },
      { titulo: 'CNPJ' },
      { titulo: 'Cidade' },
      { titulo: 'Comissão', numerico: true },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Roraima Imóveis Ltda', '67.890.123/0001-45', 'Boa Vista', '5,0%', { selo: { texto: 'Ativo', tom: 'ok' } }],
      ['Cerrado Negócios Imobiliários', '78.901.234/0001-56', 'Goiânia', '4,5%', { selo: { texto: 'Ativo', tom: 'ok' } }],
      ['Palmas Corretora Associada', '89.012.345/0001-67', 'Palmas', '4,0%', { selo: { texto: 'Ativo', tom: 'ok' } }],
      ['Cuiabá Terras Consultoria', '90.123.456/0001-78', 'Cuiabá', '5,5%', { selo: { texto: 'Suspenso', tom: 'vencido' } }],
      ['Rorainópolis Corretagem', '01.234.567/0001-89', 'Rorainópolis', '4,8%', { selo: { texto: 'Ativo', tom: 'ok' } }],
    ],
  },
  '/cadastros/bancos': {
    titulo: 'Bancos',
    descricao: 'Instituições bancárias utilizadas para recebimentos.',
    textoNovo: 'Novo banco',
    colunas: [
      { titulo: 'Código', numerico: true },
      { titulo: 'Nome', larga: true },
      { titulo: 'Situação' },
    ],
    linhas: [
      [1, 'Banco do Brasil S.A.', { selo: { texto: 'Ativo', tom: 'ok' } }],
      [104, 'Caixa Econômica Federal', { selo: { texto: 'Ativo', tom: 'ok' } }],
      [341, 'Itaú Unibanco S.A.', { selo: { texto: 'Ativo', tom: 'ok' } }],
      [237, 'Banco Bradesco S.A.', { selo: { texto: 'Ativo', tom: 'ok' } }],
      [756, 'Sicoob', { selo: { texto: 'Inativo', tom: 'neutro' } }],
    ],
  },
  '/cadastros/agencias': {
    titulo: 'Agências',
    descricao: 'Agências bancárias vinculadas aos bancos cadastrados.',
    textoNovo: 'Nova agência',
    colunas: [
      { titulo: 'Banco', larga: true },
      { titulo: 'Agência' },
      { titulo: 'Cidade' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Banco do Brasil S.A.', '3021-5', 'Boa Vista', { selo: { texto: 'Ativa', tom: 'ok' } }],
      ['Caixa Econômica Federal', '0987-2', 'Boa Vista', { selo: { texto: 'Ativa', tom: 'ok' } }],
      ['Itaú Unibanco S.A.', '1122-9', 'Rorainópolis', { selo: { texto: 'Ativa', tom: 'ok' } }],
      ['Banco Bradesco S.A.', '4456-0', 'Caracaraí', { selo: { texto: 'Ativa', tom: 'ok' } }],
      ['Sicoob', '2233-4', 'Goiânia', { selo: { texto: 'Inativa', tom: 'neutro' } }],
    ],
  },
  '/cadastros/contas-bancarias': {
    titulo: 'Contas bancárias',
    descricao: 'Contas correntes utilizadas para movimentação financeira.',
    textoNovo: 'Nova conta bancária',
    colunas: [
      { titulo: 'Banco', larga: true },
      { titulo: 'Agência' },
      { titulo: 'Conta' },
      { titulo: 'Saldo atual', numerico: true },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Banco do Brasil S.A.', '3021-5', '18.542-1', 'R$ 128.450,32', { selo: { texto: 'Ativa', tom: 'ok' } }],
      ['Caixa Econômica Federal', '0987-2', '00432-8', 'R$ 54.900,00', { selo: { texto: 'Ativa', tom: 'ok' } }],
      ['Itaú Unibanco S.A.', '1122-9', '77123-4', 'R$ 9.230,15', { selo: { texto: 'Ativa', tom: 'ok' } }],
      ['Banco Bradesco S.A.', '4456-0', '65210-9', 'R$ 312.780,90', { selo: { texto: 'Ativa', tom: 'ok' } }],
      ['Sicoob', '2233-4', '11098-3', 'R$ 0,00', { selo: { texto: 'Encerrada', tom: 'neutro' } }],
    ],
  },
  '/cadastros/centros-de-custo': {
    titulo: 'Centros de custo',
    descricao: 'Centros de custo utilizados na apuração financeira.',
    textoNovo: 'Novo centro de custo',
    colunas: [
      { titulo: 'Código' },
      { titulo: 'Descrição', larga: true },
      { titulo: 'Empresa' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['CC-001', 'Comercial e Vendas', 'Rorainópolis Empreendimentos Imobiliários Ltda', { selo: { texto: 'Ativo', tom: 'ok' } }],
      ['CC-002', 'Administrativo', 'Rorainópolis Empreendimentos Imobiliários Ltda', { selo: { texto: 'Ativo', tom: 'ok' } }],
      ['CC-003', 'Obras e Infraestrutura', 'Caracaraí Desenvolvimento Urbano Ltda', { selo: { texto: 'Ativo', tom: 'ok' } }],
      ['CC-004', 'Jurídico', 'Norte Terras Loteadora S.A.', { selo: { texto: 'Ativo', tom: 'ok' } }],
      ['CC-005', 'Marketing', 'Vale do Cerrado Loteamentos Ltda', { selo: { texto: 'Inativo', tom: 'neutro' } }],
    ],
  },
  '/cadastros/plano-de-contas': {
    titulo: 'Plano de contas',
    descricao: 'Estrutura de contas contábeis e financeiras.',
    textoNovo: 'Nova conta',
    colunas: [
      { titulo: 'Código' },
      { titulo: 'Descrição', larga: true },
      { titulo: 'Tipo' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['1.1.001', 'Receita de venda de lotes', 'Receita', { selo: { texto: 'Ativa', tom: 'ok' } }],
      ['1.1.002', 'Receita de juros de parcelas', 'Receita', { selo: { texto: 'Ativa', tom: 'ok' } }],
      ['2.1.001', 'Despesas administrativas', 'Despesa', { selo: { texto: 'Ativa', tom: 'ok' } }],
      ['2.1.002', 'Despesas com comissões', 'Despesa', { selo: { texto: 'Ativa', tom: 'ok' } }],
      ['3.1.001', 'Custo de obras e infraestrutura', 'Custo', { selo: { texto: 'Inativa', tom: 'neutro' } }],
    ],
  },
  '/cadastros/formas-de-pagamento': {
    titulo: 'Formas de pagamento',
    descricao: 'Formas de pagamento aceitas para recebimento de parcelas.',
    textoNovo: 'Nova forma de pagamento',
    colunas: [
      { titulo: 'Descrição', larga: true },
      { titulo: 'Tipo' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Boleto bancário', 'Boleto', { selo: { texto: 'Ativa', tom: 'ok' } }],
      ['PIX', 'Instantâneo', { selo: { texto: 'Ativa', tom: 'ok' } }],
      ['Cartão de crédito', 'Cartão', { selo: { texto: 'Ativa', tom: 'ok' } }],
      ['Transferência bancária (TED)', 'Transferência', { selo: { texto: 'Ativa', tom: 'ok' } }],
      ['Débito em conta', 'Débito automático', { selo: { texto: 'Inativa', tom: 'neutro' } }],
    ],
  },
  '/cadastros/indices-economicos': {
    titulo: 'Índices econômicos',
    descricao: 'Índices utilizados para reajuste de contratos e parcelas.',
    textoNovo: 'Novo índice',
    colunas: [
      { titulo: 'Sigla' },
      { titulo: 'Nome', larga: true },
      { titulo: 'Variação do mês', numerico: true },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['IGP-M', 'Índice Geral de Preços do Mercado', '0,6%', { selo: { texto: 'Ativo', tom: 'ok' } }],
      ['INCC', 'Índice Nacional de Custo da Construção', '0,4%', { selo: { texto: 'Ativo', tom: 'ok' } }],
      ['IPCA', 'Índice de Preços ao Consumidor Amplo', '0,3%', { selo: { texto: 'Ativo', tom: 'ok' } }],
      ['SELIC', 'Taxa Referencial do Sistema Especial', '1,1%', { selo: { texto: 'Ativo', tom: 'ok' } }],
      ['TR', 'Taxa Referencial', '0,0%', { selo: { texto: 'Inativo', tom: 'neutro' } }],
    ],
  },
  '/cadastros/tipos-de-documento': {
    titulo: 'Tipos de documento',
    descricao: 'Tipos de documentos exigidos nos cadastros e contratos.',
    textoNovo: 'Novo tipo de documento',
    colunas: [
      { titulo: 'Descrição', larga: true },
      { titulo: 'Obrigatório' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['RG', 'Sim', { selo: { texto: 'Ativo', tom: 'ok' } }],
      ['CPF', 'Sim', { selo: { texto: 'Ativo', tom: 'ok' } }],
      ['Comprovante de residência', 'Sim', { selo: { texto: 'Ativo', tom: 'ok' } }],
      ['Certidão de casamento', 'Não', { selo: { texto: 'Ativo', tom: 'ok' } }],
      ['Contrato social', 'Não', { selo: { texto: 'Inativo', tom: 'neutro' } }],
    ],
  },
  '/cadastros/motivos-de-cancelamento': {
    titulo: 'Motivos de cancelamento',
    descricao: 'Motivos utilizados no cancelamento de contratos e vendas.',
    textoNovo: 'Novo motivo',
    colunas: [
      { titulo: 'Descrição', larga: true },
      { titulo: 'Categoria' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Inadimplência superior a 90 dias', 'Financeiro', { selo: { texto: 'Ativo', tom: 'ok' } }],
      ['Desistência do comprador', 'Comercial', { selo: { texto: 'Ativo', tom: 'ok' } }],
      ['Erro de cadastro', 'Administrativo', { selo: { texto: 'Ativo', tom: 'ok' } }],
      ['Decisão judicial', 'Jurídico', { selo: { texto: 'Ativo', tom: 'critico' } }],
      ['Substituição de titularidade', 'Comercial', { selo: { texto: 'Inativo', tom: 'neutro' } }],
    ],
  },
  '/cadastros/usuarios': {
    titulo: 'Usuários',
    descricao: 'Usuários com acesso ao sistema.',
    textoNovo: 'Novo usuário',
    colunas: [
      { titulo: 'Nome', larga: true },
      { titulo: 'E-mail' },
      { titulo: 'Perfil' },
      { titulo: 'Último acesso' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Ana Paula Martins', 'ana.martins@rorainopolisemp.com.br', 'Administrador', '28/07/2025', { selo: { texto: 'Ativo', tom: 'ok' } }],
      ['Bruno Henrique Costa', 'bruno.costa@rorainopolisemp.com.br', 'Financeiro', '27/07/2025', { selo: { texto: 'Ativo', tom: 'ok' } }],
      ['Camila Rodrigues Dias', 'camila.dias@rorainopolisemp.com.br', 'Comercial', '25/07/2025', { selo: { texto: 'Ativo', tom: 'ok' } }],
      ['Diego Fernandes Lopes', 'diego.lopes@rorainopolisemp.com.br', 'Jurídico', '10/06/2025', { selo: { texto: 'Bloqueado', tom: 'critico' } }],
      ['Eliane Souza Pinto', 'eliane.pinto@rorainopolisemp.com.br', 'Cobrança', '29/07/2025', { selo: { texto: 'Ativo', tom: 'ok' } }],
    ],
  },
  '/cadastros/perfis': {
    titulo: 'Perfis',
    descricao: 'Perfis de acesso utilizados na atribuição de permissões.',
    textoNovo: 'Novo perfil',
    colunas: [
      { titulo: 'Nome', larga: true },
      { titulo: 'Usuários vinculados', numerico: true },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Administrador', 3, { selo: { texto: 'Ativo', tom: 'ok' } }],
      ['Financeiro', 5, { selo: { texto: 'Ativo', tom: 'ok' } }],
      ['Comercial', 12, { selo: { texto: 'Ativo', tom: 'ok' } }],
      ['Cobrança', 4, { selo: { texto: 'Ativo', tom: 'ok' } }],
      ['Jurídico', 2, { selo: { texto: 'Inativo', tom: 'neutro' } }],
    ],
  },
  '/cadastros/permissoes': {
    titulo: 'Permissões',
    descricao: 'Permissões de acesso associadas aos perfis do sistema.',
    textoNovo: 'Nova permissão',
    colunas: [
      { titulo: 'Descrição', larga: true },
      { titulo: 'Módulo' },
      { titulo: 'Perfis vinculados', numerico: true },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Visualizar contratos', 'Comercial', 4, { selo: { texto: 'Ativa', tom: 'ok' } }],
      ['Editar plano de contas', 'Financeiro', 2, { selo: { texto: 'Ativa', tom: 'ok' } }],
      ['Aprovar cancelamento de contrato', 'Jurídico', 1, { selo: { texto: 'Ativa', tom: 'ok' } }],
      ['Emitir boletos', 'Cobrança', 3, { selo: { texto: 'Ativa', tom: 'ok' } }],
      ['Gerenciar usuários e perfis', 'Administrativo', 1, { selo: { texto: 'Inativa', tom: 'neutro' } }],
    ],
  },
};

export default telas;
