import type { ConfigDeListagem } from '@/componentes/comuns/PaginaDeListagem';

const telas: Record<string, ConfigDeListagem> = {
  '/cobrancas/manual': {
    titulo: 'Cobrança manual',
    descricao: 'Cobranças registradas manualmente pela equipe financeira',
    textoNovo: 'Cobrança manual',
    colunas: [
      { titulo: 'Cliente', larga: true },
      { titulo: 'Contrato' },
      { titulo: 'Lote' },
      { titulo: 'Responsável' },
      { titulo: 'Valor', numerico: true },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Marcos Vinícius Andrade', 'CT-2025-0142', 'Quadra 04 - Lote 12', 'Fernanda Lima', 'R$ 1.850,00', { selo: { texto: 'Pendente', tom: 'atencao' } }],
      ['Luciana Ferreira Costa', 'CT-2024-0987', 'Quadra 09 - Lote 03', 'Ricardo Souza', 'R$ 3.200,00', { selo: { texto: 'Registrada', tom: 'ok' } }],
      ['Paulo Henrique Batista', 'CT-2025-0210', 'Quadra 02 - Lote 27', 'Fernanda Lima', 'R$ 980,00', { selo: { texto: 'Vencida', tom: 'vencido' } }],
      ['Simone Alves Rocha', 'CT-2023-0455', 'Quadra 11 - Lote 08', 'Ricardo Souza', 'R$ 2.400,00', { selo: { texto: 'Registrada', tom: 'ok' } }],
      ['Adriano Gomes Teixeira', 'CT-2025-0301', 'Quadra 06 - Lote 15', 'Fernanda Lima', 'R$ 1.150,00', { selo: { texto: 'Pendente', tom: 'atencao' } }],
    ],
  },
  '/cobrancas/automatica': {
    titulo: 'Cobrança automática',
    descricao: 'Régua automática de cobrança configurada por dias de atraso',
    textoNovo: 'Regra de cobrança',
    colunas: [
      { titulo: 'Regra', larga: true },
      { titulo: 'Gatilho' },
      { titulo: 'Canal' },
      { titulo: 'Clientes atingidos', numerico: true },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Lembrete de vencimento', 'D-3', 'WhatsApp + E-mail', 312, { selo: { texto: 'Ativa', tom: 'ok' } }],
      ['Aviso de atraso leve', 'D+1', 'SMS', 87, { selo: { texto: 'Ativa', tom: 'ok' } }],
      ['Cobrança de atraso moderado', 'D+15', 'WhatsApp', 54, { selo: { texto: 'Ativa', tom: 'ok' } }],
      ['Escalonamento para jurídico', 'D+45', 'E-mail + Carta', 19, { selo: { texto: 'Em processamento', tom: 'info' } }],
      ['Campanha de negociação', 'D+30', 'WhatsApp + SMS', 41, { selo: { texto: 'Pausada', tom: 'neutro' } }],
    ],
  },
  '/cobrancas/juridica': {
    titulo: 'Cobrança jurídica',
    descricao: 'Contratos encaminhados para cobrança judicial ou notificação extrajudicial',
    textoNovo: 'Encaminhamento jurídico',
    colunas: [
      { titulo: 'Cliente', larga: true },
      { titulo: 'Contrato' },
      { titulo: 'Dias em atraso', numerico: true },
      { titulo: 'Escritório responsável' },
      { titulo: 'Valor em cobrança', numerico: true },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Roberto Carlos Nascimento', 'CT-2022-0078', 187, 'Nogueira & Associados', 'R$ 18.400,00', { selo: { texto: 'Ação protocolada', tom: 'critico' } }],
      ['Vanessa Cristina Pires', 'CT-2023-0134', 96, 'Nogueira & Associados', 'R$ 9.750,00', { selo: { texto: 'Notificação extrajudicial', tom: 'atencao' } }],
      ['Edson Luiz Martins', 'CT-2021-0056', 340, 'Barros Advocacia', 'R$ 27.900,00', { selo: { texto: 'Ação protocolada', tom: 'critico' } }],
      ['Cristiane Souza Lima', 'CT-2023-0299', 62, 'Barros Advocacia', 'R$ 5.300,00', { selo: { texto: 'Em análise', tom: 'info' } }],
    ],
  },
  '/cobrancas/whatsapp': {
    titulo: 'Cobrança por WhatsApp',
    descricao: 'Mensagens de cobrança enviadas pelo canal WhatsApp Business',
    textoNovo: 'Disparo por WhatsApp',
    colunas: [
      { titulo: 'Cliente', larga: true },
      { titulo: 'Telefone' },
      { titulo: 'Mensagem', larga: true },
      { titulo: 'Enviado em' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Juliana Pereira Santos', '(95) 99123-4567', 'Lembrete de parcela a vencer em 3 dias', '26/07/2026', { selo: { texto: 'Lido', tom: 'ok' } }],
      ['Diego Ramos Oliveira', '(95) 98876-2211', 'Parcela em atraso - regularize sua situação', '27/07/2026', { selo: { texto: 'Entregue', tom: 'ok' } }],
      ['Patrícia Almeida Duarte', '(95) 99765-3320', 'Segunda via de boleto disponível', '28/07/2026', { selo: { texto: 'Enviado', tom: 'info' } }],
      ['Gustavo Henrique Silva', '(95) 98123-9087', 'Parcela em atraso - regularize sua situação', '25/07/2026', { selo: { texto: 'Falhou', tom: 'vencido' } }],
      ['Renata Cardoso Farias', '(95) 99432-1098', 'Lembrete de parcela a vencer em 3 dias', '27/07/2026', { selo: { texto: 'Lido', tom: 'ok' } }],
    ],
  },
  '/cobrancas/sms': {
    titulo: 'Cobrança por SMS',
    descricao: 'Mensagens de texto enviadas para cobrança de parcelas em atraso',
    textoNovo: 'Disparo por SMS',
    colunas: [
      { titulo: 'Cliente', larga: true },
      { titulo: 'Telefone' },
      { titulo: 'Operadora' },
      { titulo: 'Enviado em' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Anderson Melo Cavalcante', '(95) 99211-4432', 'Vivo', '28/07/2026', { selo: { texto: 'Entregue', tom: 'ok' } }],
      ['Katia Regina Nunes', '(95) 98455-7710', 'Claro', '27/07/2026', { selo: { texto: 'Entregue', tom: 'ok' } }],
      ['Wellington Souza Braga', '(95) 99988-1123', 'Tim', '26/07/2026', { selo: { texto: 'Falhou', tom: 'vencido' } }],
      ['Bianca Ribeiro Costa', '(95) 98211-6654', 'Oi', '28/07/2026', { selo: { texto: 'Enviado', tom: 'info' } }],
    ],
  },
  '/cobrancas/email': {
    titulo: 'Cobrança por e-mail',
    descricao: 'Comunicações de cobrança enviadas por e-mail aos compradores',
    textoNovo: 'Disparo por e-mail',
    colunas: [
      { titulo: 'Cliente', larga: true },
      { titulo: 'E-mail', larga: true },
      { titulo: 'Assunto', larga: true },
      { titulo: 'Enviado em' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Fabiana Rocha Guimarães', 'fabiana.guimaraes@email.com', 'Sua parcela vence em 5 dias', '24/07/2026', { selo: { texto: 'Aberto', tom: 'ok' } }],
      ['Márcio Antônio Vieira', 'marcio.vieira@email.com', 'Parcela em atraso - Gestrato', '25/07/2026', { selo: { texto: 'Enviado', tom: 'info' } }],
      ['Tatiane Correia Lopes', 'tatiane.correia@email.com', 'Segunda via de boleto', '26/07/2026', { selo: { texto: 'Aberto', tom: 'ok' } }],
      ['Sérgio Murilo Barbosa', 'sergio.barbosa@email.com', 'Parcela em atraso - Gestrato', '20/07/2026', { selo: { texto: 'Rejeitado', tom: 'vencido' } }],
      ['Camila Nogueira Ferreira', 'camila.nogueira@email.com', 'Confirmação de pagamento', '28/07/2026', { selo: { texto: 'Aberto', tom: 'ok' } }],
    ],
  },
  '/cobrancas/ligacoes': {
    titulo: 'Ligações de cobrança',
    descricao: 'Registro de ligações telefônicas realizadas para cobrança',
    textoNovo: 'Registrar ligação',
    colunas: [
      { titulo: 'Cliente', larga: true },
      { titulo: 'Telefone' },
      { titulo: 'Atendente' },
      { titulo: 'Duração' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Otávio Ricardo Freitas', '(95) 99321-8877', 'Bruna Castro', '4min 12s', { selo: { texto: 'Atendida', tom: 'ok' } }],
      ['Elaine Cristina Moraes', '(95) 98776-3345', 'João Pedro Lima', '0min', { selo: { texto: 'Não atendida', tom: 'atencao' } }],
      ['Rogério Batista Dias', '(95) 99654-2201', 'Bruna Castro', '2min 45s', { selo: { texto: 'Atendida', tom: 'ok' } }],
      ['Priscila Santana Reis', '(95) 98123-4490', 'João Pedro Lima', '0min', { selo: { texto: 'Caixa postal', tom: 'neutro' } }],
    ],
  },
  '/cobrancas/cartas': {
    titulo: 'Cartas de cobrança',
    descricao: 'Correspondências físicas enviadas por correio para cobrança de parcelas',
    textoNovo: 'Nova carta',
    colunas: [
      { titulo: 'Cliente', larga: true },
      { titulo: 'Endereço', larga: true },
      { titulo: 'Tipo' },
      { titulo: 'Enviada em' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Heloísa Fernanda Machado', 'Rua das Palmeiras, 245 - Boa Vista/RR', 'Notificação de atraso', '10/07/2026', { selo: { texto: 'Entregue', tom: 'ok' } }],
      ['Cláudio Roberto Aquino', 'Av. Brasil, 1120 - Boa Vista/RR', 'Notificação extrajudicial', '15/07/2026', { selo: { texto: 'Em trânsito', tom: 'info' } }],
      ['Débora Cristina Assis', 'Rua Sete de Setembro, 88 - Boa Vista/RR', 'Notificação de atraso', '05/07/2026', { selo: { texto: 'Devolvida', tom: 'vencido' } }],
      ['Nilson José Cardoso', 'Rua Jardim Floresta, 310 - Boa Vista/RR', 'Aviso de vencimento', '20/07/2026', { selo: { texto: 'Entregue', tom: 'ok' } }],
    ],
  },
  '/cobrancas/notificacoes': {
    titulo: 'Notificações',
    descricao: 'Notificações internas geradas pelo motor de cobrança',
    textoNovo: 'Nova notificação',
    colunas: [
      { titulo: 'Cliente', larga: true },
      { titulo: 'Evento', larga: true },
      { titulo: 'Canal' },
      { titulo: 'Data' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Wagner Luís Pinheiro', 'Parcela vence em 3 dias', 'Push + E-mail', '27/07/2026', { selo: { texto: 'Enviada', tom: 'info' } }],
      ['Aline Fonseca Ribeiro', 'Parcela paga com sucesso', 'Push', '28/07/2026', { selo: { texto: 'Entregue', tom: 'ok' } }],
      ['Marcelo Augusto Tavares', 'Contrato encaminhado ao jurídico', 'E-mail', '22/07/2026', { selo: { texto: 'Entregue', tom: 'ok' } }],
      ['Silvana Aparecida Costa', 'Boleto cancelado', 'Push', '26/07/2026', { selo: { texto: 'Pendente', tom: 'atencao' } }],
    ],
  },
  '/boletos/emissao': {
    titulo: 'Emissão de boletos',
    descricao: 'Boletos emitidos para as parcelas dos contratos ativos',
    textoNovo: 'Emitir boleto',
    colunas: [
      { titulo: 'Cliente', larga: true },
      { titulo: 'Contrato' },
      { titulo: 'Nº do boleto' },
      { titulo: 'Vencimento' },
      { titulo: 'Valor', numerico: true },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Igor Salvador Nery', 'CT-2025-0410', '00192.34567', '10/08/2026', 'R$ 1.420,00', { selo: { texto: 'Registrado', tom: 'ok' } }],
      ['Denise Aparecida Souza', 'CT-2025-0388', '00192.34568', '05/08/2026', 'R$ 2.100,00', { selo: { texto: 'Registrado', tom: 'ok' } }],
      ['Fabrício Lemos Andrade', 'CT-2024-0921', '00192.34569', '02/08/2026', 'R$ 950,00', { selo: { texto: 'Em processamento', tom: 'info' } }],
      ['Sônia Regina Prado', 'CT-2025-0455', '00192.34570', '30/07/2026', 'R$ 1.780,00', { selo: { texto: 'Vencido', tom: 'vencido' } }],
      ['Alexsandro Vieira Lima', 'CT-2023-0602', '00192.34571', '12/08/2026', 'R$ 3.050,00', { selo: { texto: 'Registrado', tom: 'ok' } }],
    ],
  },
  '/boletos/segunda-via': {
    titulo: 'Segunda via de boleto',
    descricao: 'Solicitações de segunda via de boletos emitidas para os clientes',
    textoNovo: 'Emitir segunda via',
    colunas: [
      { titulo: 'Cliente', larga: true },
      { titulo: 'Contrato' },
      { titulo: 'Boleto original' },
      { titulo: 'Solicitado em' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Eduarda Milena Sales', 'CT-2024-0733', '00192.31245', '24/07/2026', { selo: { texto: 'Disponível', tom: 'ok' } }],
      ['Jonas Emanuel Pires', 'CT-2025-0119', '00192.29981', '25/07/2026', { selo: { texto: 'Em processamento', tom: 'info' } }],
      ['Rosimeire Batista Alves', 'CT-2023-0587', '00192.28844', '20/07/2026', { selo: { texto: 'Disponível', tom: 'ok' } }],
      ['Cleiton Rogério Farias', 'CT-2024-0044', '00192.27732', '18/07/2026', { selo: { texto: 'Cancelada', tom: 'vencido' } }],
    ],
  },
  '/boletos/cancelamento': {
    titulo: 'Cancelamento de boletos',
    descricao: 'Boletos cancelados por renegociação, quitação antecipada ou erro de emissão',
    textoNovo: 'Cancelar boleto',
    colunas: [
      { titulo: 'Cliente', larga: true },
      { titulo: 'Nº do boleto' },
      { titulo: 'Motivo', larga: true },
      { titulo: 'Cancelado em' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Vinícius Antunes Rezende', '00192.20981', 'Renegociação de parcelas', '15/07/2026', { selo: { texto: 'Cancelado', tom: 'vencido' } }],
      ['Marlene Aparecida Duarte', '00192.19876', 'Quitação antecipada', '18/07/2026', { selo: { texto: 'Cancelado', tom: 'vencido' } }],
      ['Fábio César Monteiro', '00192.18543', 'Erro no valor emitido', '22/07/2026', { selo: { texto: 'Em processamento', tom: 'info' } }],
      ['Neuza Maria dos Santos', '00192.17220', 'Substituição por novo boleto', '26/07/2026', { selo: { texto: 'Cancelado', tom: 'vencido' } }],
    ],
  },
  '/boletos/registro': {
    titulo: 'Registro (CNAB)',
    descricao: 'Situação de registro dos boletos junto ao banco via arquivo CNAB',
    textoNovo: 'Registrar lote',
    colunas: [
      { titulo: 'Cliente', larga: true },
      { titulo: 'Banco' },
      { titulo: 'Nosso número' },
      { titulo: 'Enviado em' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Rodrigo Almeida Peixoto', 'Banco do Brasil', '00001234567', '20/07/2026', { selo: { texto: 'Registrado', tom: 'ok' } }],
      ['Josiane Cristina Bento', 'Bradesco', '00001234890', '21/07/2026', { selo: { texto: 'Registrado', tom: 'ok' } }],
      ['Leandro Silva Coutinho', 'Itaú Unibanco', '00001235102', '22/07/2026', { selo: { texto: 'Em processamento', tom: 'info' } }],
      ['Adélia Ferreira Nunes', 'Santander', '00001235388', '19/07/2026', { selo: { texto: 'Rejeitado', tom: 'vencido' } }],
      ['Hélio Barbosa Cunha', 'Banco do Brasil', '00001235640', '23/07/2026', { selo: { texto: 'Registrado', tom: 'ok' } }],
    ],
  },
  '/boletos/baixa': {
    titulo: 'Baixa de boletos',
    descricao: 'Boletos baixados após identificação de pagamento pelo banco',
    textoNovo: 'Baixar boleto',
    colunas: [
      { titulo: 'Cliente', larga: true },
      { titulo: 'Nº do boleto' },
      { titulo: 'Banco' },
      { titulo: 'Pago em' },
      { titulo: 'Valor', numerico: true },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Cíntia Aparecida Gonçalves', '00192.15098', 'Bradesco', '25/07/2026', 'R$ 1.650,00', { selo: { texto: 'Baixado', tom: 'ok' } }],
      ['Douglas Henrique Farias', '00192.14877', 'Banco do Brasil', '26/07/2026', 'R$ 2.320,00', { selo: { texto: 'Baixado', tom: 'ok' } }],
      ['Yasmin Cordeiro Rangel', '00192.14556', 'Itaú Unibanco', '27/07/2026', 'R$ 890,00', { selo: { texto: 'Em processamento', tom: 'info' } }],
      ['Gilberto Nascimento Reis', '00192.14210', 'Santander', '24/07/2026', 'R$ 1.480,00', { selo: { texto: 'Baixado', tom: 'ok' } }],
    ],
  },
  '/boletos/pix': {
    titulo: 'Pix',
    descricao: 'Pagamentos via Pix vinculados às parcelas dos contratos',
    textoNovo: 'Gerar cobrança Pix',
    colunas: [
      { titulo: 'Cliente', larga: true },
      { titulo: 'Chave Pix' },
      { titulo: 'Txid' },
      { titulo: 'Valor', numerico: true },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Everton Luiz Barreto', 'contato@evertonbarreto.com', 'TX8827301AB', 'R$ 1.320,00', { selo: { texto: 'Pago', tom: 'ok' } }],
      ['Rosana Maciel Ferreira', '(95) 99887-1234', 'TX8827302AC', 'R$ 2.900,00', { selo: { texto: 'Aguardando pagamento', tom: 'atencao' } }],
      ['Thiago Moreira Castilho', '049.882.331-05', 'TX8827303AD', 'R$ 780,00', { selo: { texto: 'Pago', tom: 'ok' } }],
      ['Larissa Bianchi Souto', 'larissa.souto@email.com', 'TX8827304AE', 'R$ 1.050,00', { selo: { texto: 'Expirado', tom: 'vencido' } }],
    ],
  },
  '/boletos/qrcode': {
    titulo: 'QR Code Pix',
    descricao: 'QR Codes Pix gerados e vinculados aos boletos emitidos',
    textoNovo: 'Gerar QR Code',
    colunas: [
      { titulo: 'Cliente', larga: true },
      { titulo: 'Nº do boleto' },
      { titulo: 'Gerado em' },
      { titulo: 'Validade' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Nathália Ribeiro Prado', '00192.11098', '20/07/2026', '10/08/2026', { selo: { texto: 'Ativo', tom: 'ok' } }],
      ['Jorge Luís Camargo', '00192.11304', '21/07/2026', '05/08/2026', { selo: { texto: 'Ativo', tom: 'ok' } }],
      ['Verônica Salles Bittencourt', '00192.11522', '15/07/2026', '30/07/2026', { selo: { texto: 'Expirado', tom: 'vencido' } }],
      ['Emerson Diego Paiva', '00192.11710', '22/07/2026', '12/08/2026', { selo: { texto: 'Ativo', tom: 'ok' } }],
    ],
  },
  '/boletos/linha-digitavel': {
    titulo: 'Linha digitável',
    descricao: 'Consulta de linhas digitáveis geradas para os boletos ativos',
    textoNovo: 'Consultar linha digitável',
    colunas: [
      { titulo: 'Cliente', larga: true },
      { titulo: 'Linha digitável', larga: true },
      { titulo: 'Vencimento' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Amanda Cristiane Vasconcelos', '00190.00009 03456.789012 34567.890123 4 98760000142000', '05/08/2026', { selo: { texto: 'Registrado', tom: 'ok' } }],
      ['Bruno César Malaquias', '00190.00009 03456.789013 34567.890124 4 98760000090000', '10/08/2026', { selo: { texto: 'Registrado', tom: 'ok' } }],
      ['Célia Regina Mourão', '00190.00009 03456.789014 34567.890125 4 98760000210000', '28/07/2026', { selo: { texto: 'Vencido', tom: 'vencido' } }],
      ['Diogo Fernandes Lacerda', '00190.00009 03456.789015 34567.890126 4 98760000178000', '15/08/2026', { selo: { texto: 'Registrado', tom: 'ok' } }],
    ],
  },
  '/boletos/cnab': {
    titulo: 'Arquivos CNAB',
    descricao: 'Remessas e retornos de arquivos CNAB trocados com os bancos conveniados',
    textoNovo: 'Enviar remessa',
    colunas: [
      { titulo: 'Arquivo', larga: true },
      { titulo: 'Banco' },
      { titulo: 'Tipo' },
      { titulo: 'Registros', numerico: true },
      { titulo: 'Processado em' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['REM_240_20260722.rem', 'Banco do Brasil', 'Remessa', 84, '22/07/2026', { selo: { texto: 'Processado', tom: 'ok' } }],
      ['RET_240_20260723.ret', 'Banco do Brasil', 'Retorno', 79, '23/07/2026', { selo: { texto: 'Processado', tom: 'ok' } }],
      ['REM_237_20260724.rem', 'Bradesco', 'Remessa', 62, '24/07/2026', { selo: { texto: 'Em processamento', tom: 'info' } }],
      ['RET_341_20260721.ret', 'Itaú Unibanco', 'Retorno', 45, '21/07/2026', { selo: { texto: 'Erro na leitura', tom: 'vencido' } }],
    ],
  },
  '/boletos/ofx': {
    titulo: 'Arquivos OFX',
    descricao: 'Extratos bancários OFX importados para conciliação de pagamentos',
    textoNovo: 'Importar OFX',
    colunas: [
      { titulo: 'Arquivo', larga: true },
      { titulo: 'Banco' },
      { titulo: 'Período' },
      { titulo: 'Lançamentos', numerico: true },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['extrato_bb_072026.ofx', 'Banco do Brasil', '01/07/2026 a 28/07/2026', 214, { selo: { texto: 'Conciliado', tom: 'ok' } }],
      ['extrato_bradesco_072026.ofx', 'Bradesco', '01/07/2026 a 28/07/2026', 156, { selo: { texto: 'Em processamento', tom: 'info' } }],
      ['extrato_itau_062026.ofx', 'Itaú Unibanco', '01/06/2026 a 30/06/2026', 189, { selo: { texto: 'Conciliado', tom: 'ok' } }],
      ['extrato_santander_072026.ofx', 'Santander', '01/07/2026 a 28/07/2026', 73, { selo: { texto: 'Divergências encontradas', tom: 'atencao' } }],
    ],
  },
  '/boletos/webhooks': {
    titulo: 'Webhooks',
    descricao: 'Eventos recebidos dos bancos e integrações de cobrança via webhook',
    textoNovo: 'Novo endpoint',
    colunas: [
      { titulo: 'Origem', larga: true },
      { titulo: 'Evento' },
      { titulo: 'Recebido em' },
      { titulo: 'Tentativas', numerico: true },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Banco do Brasil - Boletos', 'boleto.pago', '28/07/2026 09:12', 1, { selo: { texto: 'Processado', tom: 'ok' } }],
      ['Bradesco - Boletos', 'boleto.registrado', '27/07/2026 14:03', 1, { selo: { texto: 'Processado', tom: 'ok' } }],
      ['Gerenciador Pix - RR', 'pix.recebido', '28/07/2026 08:45', 2, { selo: { texto: 'Processado', tom: 'ok' } }],
      ['Itaú Unibanco - Boletos', 'boleto.cancelado', '26/07/2026 17:20', 3, { selo: { texto: 'Falha no processamento', tom: 'vencido' } }],
    ],
  },
  '/documentos/contratos': {
    titulo: 'Documentos de contratos',
    descricao: 'Contratos de compra e venda gerados e arquivados no sistema',
    textoNovo: 'Gerar contrato',
    colunas: [
      { titulo: 'Cliente', larga: true },
      { titulo: 'Contrato' },
      { titulo: 'Empreendimento', larga: true },
      { titulo: 'Gerado em' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Alessandra Nogueira Pinto', 'CT-2025-0410', 'Residencial Monte Verde', '18/07/2026', { selo: { texto: 'Assinado', tom: 'ok' } }],
      ['Kleber Augusto Ramalho', 'CT-2025-0388', 'Loteamento Vista Alegre', '20/07/2026', { selo: { texto: 'Aguardando assinatura', tom: 'atencao' } }],
      ['Mirela Cristina Fonseca', 'CT-2025-0455', 'Residencial Monte Verde', '15/07/2026', { selo: { texto: 'Rascunho', tom: 'neutro' } }],
      ['Osvaldo Ferreira Braga', 'CT-2024-0921', 'Loteamento Águas Claras', '10/07/2026', { selo: { texto: 'Assinado', tom: 'ok' } }],
    ],
  },
  '/documentos/recibos': {
    titulo: 'Recibos',
    descricao: 'Recibos de pagamento emitidos para as parcelas quitadas',
    textoNovo: 'Emitir recibo',
    colunas: [
      { titulo: 'Cliente', larga: true },
      { titulo: 'Contrato' },
      { titulo: 'Referente a' },
      { titulo: 'Valor', numerico: true },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Beatriz Helena Costa', 'CT-2025-0142', 'Parcela 04/60', 'R$ 1.850,00', { selo: { texto: 'Emitido', tom: 'ok' } }],
      ['Nelson Ricardo Almeida', 'CT-2024-0987', 'Parcela 12/48', 'R$ 3.200,00', { selo: { texto: 'Emitido', tom: 'ok' } }],
      ['Sabrina Luíza Gouveia', 'CT-2025-0210', 'Entrada', 'R$ 5.000,00', { selo: { texto: 'Rascunho', tom: 'neutro' } }],
      ['Uéslei Fernando Motta', 'CT-2023-0455', 'Parcela 30/72', 'R$ 2.400,00', { selo: { texto: 'Emitido', tom: 'ok' } }],
    ],
  },
  '/documentos/boletos': {
    titulo: 'Documentos de boletos',
    descricao: 'Arquivos PDF dos boletos gerados, disponíveis para download e reenvio',
    textoNovo: 'Gerar documento',
    colunas: [
      { titulo: 'Cliente', larga: true },
      { titulo: 'Nº do boleto' },
      { titulo: 'Vencimento' },
      { titulo: 'Tamanho' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Ariane Barbosa Klein', '00192.34567', '10/08/2026', '84 KB', { selo: { texto: 'Disponível', tom: 'ok' } }],
      ['Fabricio dos Santos Melo', '00192.34568', '05/08/2026', '81 KB', { selo: { texto: 'Disponível', tom: 'ok' } }],
      ['Ivone Cristina Barros', '00192.34569', '02/08/2026', '0 KB', { selo: { texto: 'Em processamento', tom: 'info' } }],
      ['Luan Gabriel Teixeira', '00192.34570', '30/07/2026', '79 KB', { selo: { texto: 'Disponível', tom: 'ok' } }],
    ],
  },
  '/documentos/declaracoes': {
    titulo: 'Declarações',
    descricao: 'Declarações emitidas a pedido dos compradores, como quitação e negativa de débito',
    textoNovo: 'Emitir declaração',
    colunas: [
      { titulo: 'Cliente', larga: true },
      { titulo: 'Contrato' },
      { titulo: 'Tipo', larga: true },
      { titulo: 'Solicitada em' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Regiane Aparecida Souto', 'CT-2020-0087', 'Declaração de quitação', '12/07/2026', { selo: { texto: 'Emitida', tom: 'ok' } }],
      ['Vagner Luiz Ferraz', 'CT-2025-0142', 'Declaração de adimplência', '20/07/2026', { selo: { texto: 'Emitida', tom: 'ok' } }],
      ['Solange Maria Brandão', 'CT-2024-0398', 'Declaração de residência no lote', '22/07/2026', { selo: { texto: 'Em análise', tom: 'atencao' } }],
      ['Ederson Pablo Nogueira', 'CT-2023-0210', 'Declaração de quitação', '08/07/2026', { selo: { texto: 'Emitida', tom: 'ok' } }],
    ],
  },
  '/documentos/termos': {
    titulo: 'Termos',
    descricao: 'Termos de aditivo, distrato e acordo vinculados aos contratos',
    textoNovo: 'Gerar termo',
    colunas: [
      { titulo: 'Cliente', larga: true },
      { titulo: 'Contrato' },
      { titulo: 'Tipo de termo', larga: true },
      { titulo: 'Gerado em' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Talita Fernandes Rios', 'CT-2024-0733', 'Termo de renegociação', '19/07/2026', { selo: { texto: 'Assinado', tom: 'ok' } }],
      ['Wanderley José Cunha', 'CT-2022-0056', 'Termo de distrato', '21/07/2026', { selo: { texto: 'Aguardando assinatura', tom: 'atencao' } }],
      ['Michele Aparecida Lacerda', 'CT-2025-0119', 'Termo aditivo de prazo', '23/07/2026', { selo: { texto: 'Rascunho', tom: 'neutro' } }],
      ['Anselmo Rodrigues Vale', 'CT-2023-0587', 'Termo de acordo de dívida', '16/07/2026', { selo: { texto: 'Assinado', tom: 'ok' } }],
    ],
  },
  '/documentos/pdf': {
    titulo: 'Geração de PDF',
    descricao: 'Fila de geração de documentos em PDF a partir dos modelos cadastrados',
    textoNovo: 'Gerar PDF',
    colunas: [
      { titulo: 'Documento', larga: true },
      { titulo: 'Cliente', larga: true },
      { titulo: 'Modelo' },
      { titulo: 'Solicitado em' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Contrato_CT-2025-0410.pdf', 'Norberto Alexandre Dias', 'Contrato padrão', '27/07/2026', { selo: { texto: 'Gerado', tom: 'ok' } }],
      ['Recibo_CT-2024-0987_p12.pdf', 'Elizete Cristina Rocha', 'Recibo de pagamento', '28/07/2026', { selo: { texto: 'Gerado', tom: 'ok' } }],
      ['Declaracao_CT-2023-0210.pdf', 'Fagner Luís Andrade', 'Declaração de quitação', '28/07/2026', { selo: { texto: 'Em processamento', tom: 'info' } }],
      ['Termo_CT-2022-0056.pdf', 'Cassiana Beatriz Melo', 'Termo de distrato', '24/07/2026', { selo: { texto: 'Falha na geração', tom: 'vencido' } }],
    ],
  },
  '/documentos/assinatura': {
    titulo: 'Assinaturas',
    descricao: 'Documentos enviados para assinatura eletrônica dos clientes',
    textoNovo: 'Enviar para assinatura',
    colunas: [
      { titulo: 'Documento', larga: true },
      { titulo: 'Cliente', larga: true },
      { titulo: 'Enviado em' },
      { titulo: 'Signatários', numerico: true },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Contrato_CT-2025-0455.pdf', 'Geraldo Vicente Souza', '22/07/2026', 2, { selo: { texto: 'Assinado', tom: 'ok' } }],
      ['Termo_CT-2024-0733.pdf', 'Ivanilde Cristina Paz', '24/07/2026', 2, { selo: { texto: 'Aguardando assinatura', tom: 'atencao' } }],
      ['Aditivo_CT-2025-0119.pdf', 'Reginaldo Costa Amaral', '26/07/2026', 1, { selo: { texto: 'Aguardando assinatura', tom: 'atencao' } }],
      ['Contrato_CT-2023-0587.pdf', 'Denilson Freitas Prado', '18/07/2026', 2, { selo: { texto: 'Assinado', tom: 'ok' } }],
      ['Distrato_CT-2022-0056.pdf', 'Jaqueline Souza Meira', '20/07/2026', 2, { selo: { texto: 'Recusado', tom: 'vencido' } }],
    ],
  },
};

export default telas;
