import type { ConfigDeListagem } from '@/componentes/comuns/PaginaDeListagem';

const telas: Record<string, ConfigDeListagem> = {
  '/contratos/simulacao': {
    titulo: 'Simulação de contrato', descricao: 'Simulações de venda parcelada geradas para clientes', textoNovo: 'Nova simulação',
    colunas: [
      { titulo: 'Cliente', larga: true },
      { titulo: 'Lote' },
      { titulo: 'Valor do lote', numerico: true },
      { titulo: 'Entrada', numerico: true },
      { titulo: 'Parcelas', numerico: true },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Marcos Vinícius Andrade', 'Quadra B / Lote 12', 'R$ 185.000,00', 'R$ 37.000,00', 120, { selo: { texto: 'Em andamento', tom: 'info' } }],
      ['Fernanda Cristina Lopes', 'Quadra A / Lote 05', 'R$ 210.500,00', 'R$ 42.100,00', 96, { selo: { texto: 'Aprovada', tom: 'ok' } }],
      ['Roberto Carlos Nascimento', 'Quadra D / Lote 22', 'R$ 165.000,00', 'R$ 16.500,00', 144, { selo: { texto: 'Pendente', tom: 'atencao' } }],
      ['Juliana Aparecida Souza', 'Quadra C / Lote 08', 'R$ 198.000,00', 'R$ 59.400,00', 84, { selo: { texto: 'Aprovada', tom: 'ok' } }],
      ['Anderson Luiz Ferreira', 'Quadra B / Lote 30', 'R$ 172.300,00', 'R$ 17.230,00', 120, { selo: { texto: 'Cancelada', tom: 'neutro' } }],
    ],
  },
  '/contratos/entrada': {
    titulo: 'Entradas', descricao: 'Pagamentos de entrada vinculados aos contratos', textoNovo: 'Registrar entrada',
    colunas: [
      { titulo: 'Contrato' },
      { titulo: 'Cliente', larga: true },
      { titulo: 'Valor', numerico: true },
      { titulo: 'Forma de pagamento' },
      { titulo: 'Vencimento' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['CT-2025-0123', 'Marcos Vinícius Andrade', 'R$ 37.000,00', 'PIX', '05/08/2025', { selo: { texto: 'Quitado', tom: 'ok' } }],
      ['CT-2025-0145', 'Fernanda Cristina Lopes', 'R$ 42.100,00', 'Boleto', '10/08/2025', { selo: { texto: 'A vencer', tom: 'atencao' } }],
      ['CT-2025-0098', 'Roberto Carlos Nascimento', 'R$ 16.500,00', 'Cartão de crédito', '20/07/2025', { selo: { texto: 'Vencido', tom: 'vencido' } }],
      ['CT-2025-0201', 'Juliana Aparecida Souza', 'R$ 59.400,00', 'Transferência', '15/08/2025', { selo: { texto: 'Quitado', tom: 'ok' } }],
      ['CT-2025-0167', 'Anderson Luiz Ferreira', 'R$ 17.230,00', 'PIX', '02/08/2025', { selo: { texto: 'A vencer', tom: 'atencao' } }],
    ],
  },
  '/contratos/parcelamento': {
    titulo: 'Parcelamento', descricao: 'Planos de parcelamento definidos por contrato', textoNovo: 'Novo plano',
    colunas: [
      { titulo: 'Contrato' },
      { titulo: 'Cliente', larga: true },
      { titulo: 'Qtd. parcelas', numerico: true },
      { titulo: 'Valor da parcela', numerico: true },
      { titulo: 'Índice' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['CT-2025-0123', 'Marcos Vinícius Andrade', 120, 'R$ 1.480,00', 'IGP-M', { selo: { texto: 'Ativo', tom: 'ok' } }],
      ['CT-2025-0145', 'Fernanda Cristina Lopes', 96, 'R$ 1.985,00', 'INCC', { selo: { texto: 'Ativo', tom: 'ok' } }],
      ['CT-2025-0098', 'Roberto Carlos Nascimento', 144, 'R$ 1.230,00', 'IGP-M', { selo: { texto: 'Em atraso', tom: 'vencido' } }],
      ['CT-2025-0201', 'Juliana Aparecida Souza', 84, 'R$ 2.150,00', 'IPCA', { selo: { texto: 'Ativo', tom: 'ok' } }],
      ['CT-2025-0167', 'Anderson Luiz Ferreira', 120, 'R$ 1.395,00', 'IGP-M', { selo: { texto: 'Rascunho', tom: 'neutro' } }],
    ],
  },
  '/contratos/intermediarias': {
    titulo: 'Parcelas intermediárias', descricao: 'Parcelas anuais intermediárias previstas no contrato', textoNovo: 'Nova intermediária',
    colunas: [
      { titulo: 'Contrato' },
      { titulo: 'Cliente', larga: true },
      { titulo: 'Nº', numerico: true },
      { titulo: 'Valor', numerico: true },
      { titulo: 'Vencimento' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['CT-2025-0123', 'Marcos Vinícius Andrade', 1, 'R$ 5.200,00', '10/12/2025', { selo: { texto: 'A vencer', tom: 'atencao' } }],
      ['CT-2025-0145', 'Fernanda Cristina Lopes', 2, 'R$ 6.750,00', '10/12/2026', { selo: { texto: 'A vencer', tom: 'atencao' } }],
      ['CT-2025-0098', 'Roberto Carlos Nascimento', 1, 'R$ 4.100,00', '10/12/2024', { selo: { texto: 'Vencido', tom: 'vencido' } }],
      ['CT-2025-0201', 'Juliana Aparecida Souza', 1, 'R$ 7.320,00', '10/12/2025', { selo: { texto: 'Quitado', tom: 'ok' } }],
      ['CT-2025-0167', 'Anderson Luiz Ferreira', 3, 'R$ 5.800,00', '10/12/2027', { selo: { texto: 'A vencer', tom: 'atencao' } }],
    ],
  },
  '/contratos/baloes': {
    titulo: 'Balões', descricao: 'Parcelas balão com vencimento programado no contrato', textoNovo: 'Novo balão',
    colunas: [
      { titulo: 'Contrato' },
      { titulo: 'Cliente', larga: true },
      { titulo: 'Nº', numerico: true },
      { titulo: 'Valor', numerico: true },
      { titulo: 'Vencimento' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['CT-2025-0123', 'Marcos Vinícius Andrade', 1, 'R$ 18.500,00', '05/08/2030', { selo: { texto: 'A vencer', tom: 'atencao' } }],
      ['CT-2025-0145', 'Fernanda Cristina Lopes', 1, 'R$ 21.000,00', '10/08/2033', { selo: { texto: 'A vencer', tom: 'atencao' } }],
      ['CT-2025-0098', 'Roberto Carlos Nascimento', 2, 'R$ 16.500,00', '20/07/2025', { selo: { texto: 'Vencido', tom: 'vencido' } }],
      ['CT-2025-0201', 'Juliana Aparecida Souza', 1, 'R$ 19.800,00', '15/08/2032', { selo: { texto: 'Quitado', tom: 'ok' } }],
      ['CT-2025-0167', 'Anderson Luiz Ferreira', 1, 'R$ 17.230,00', '02/08/2035', { selo: { texto: 'A vencer', tom: 'atencao' } }],
    ],
  },
  '/contratos/quitacao': {
    titulo: 'Quitações', descricao: 'Contratos quitados integralmente pelos clientes', textoNovo: 'Registrar quitação',
    colunas: [
      { titulo: 'Contrato' },
      { titulo: 'Cliente', larga: true },
      { titulo: 'Lote' },
      { titulo: 'Valor quitado', numerico: true },
      { titulo: 'Data' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['CT-2023-0044', 'Patrícia Helena Costa', 'Quadra A / Lote 18', 'R$ 195.000,00', '12/06/2025', { selo: { texto: 'Quitado', tom: 'ok' } }],
      ['CT-2022-0011', 'Sérgio Ricardo Almeida', 'Quadra C / Lote 03', 'R$ 178.400,00', '28/05/2025', { selo: { texto: 'Quitado', tom: 'ok' } }],
      ['CT-2024-0087', 'Camila Beatriz Rocha', 'Quadra B / Lote 45', 'R$ 210.000,00', '03/07/2025', { selo: { texto: 'Em processamento', tom: 'info' } }],
      ['CT-2023-0132', 'Diego Henrique Martins', 'Quadra D / Lote 11', 'R$ 165.900,00', '19/07/2025', { selo: { texto: 'Quitado', tom: 'ok' } }],
      ['CT-2024-0056', 'Renata Cristina Pires', 'Quadra A / Lote 27', 'R$ 189.750,00', '25/07/2025', { selo: { texto: 'Em processamento', tom: 'info' } }],
    ],
  },
  '/contratos/distrato': {
    titulo: 'Distratos', descricao: 'Solicitações de rescisão contratual', textoNovo: 'Novo distrato',
    colunas: [
      { titulo: 'Contrato' },
      { titulo: 'Cliente', larga: true },
      { titulo: 'Lote' },
      { titulo: 'Valor a devolver', numerico: true },
      { titulo: 'Data da solicitação' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['CT-2024-0021', 'Eduardo Lima Barbosa', 'Quadra C / Lote 14', 'R$ 32.400,00', '01/07/2025', { selo: { texto: 'Distratado', tom: 'vencido' } }],
      ['CT-2023-0078', 'Vanessa Regina Dias', 'Quadra B / Lote 07', 'R$ 41.200,00', '15/07/2025', { selo: { texto: 'Em análise', tom: 'atencao' } }],
      ['CT-2024-0109', 'Thiago Augusto Ramos', 'Quadra A / Lote 33', 'R$ 27.850,00', '22/07/2025', { selo: { texto: 'Em análise', tom: 'atencao' } }],
      ['CT-2022-0063', 'Larissa Fernanda Melo', 'Quadra D / Lote 09', 'R$ 38.900,00', '10/06/2025', { selo: { texto: 'Distratado', tom: 'vencido' } }],
      ['CT-2023-0155', 'Gustavo Henrique Teixeira', 'Quadra B / Lote 19', 'R$ 45.600,00', '05/07/2025', { selo: { texto: 'Cancelado', tom: 'neutro' } }],
    ],
  },
  '/contratos/cessao': {
    titulo: 'Cessões', descricao: 'Cessões de direitos sobre contratos em andamento', textoNovo: 'Nova cessão',
    colunas: [
      { titulo: 'Contrato' },
      { titulo: 'Cedente', larga: true },
      { titulo: 'Cessionário', larga: true },
      { titulo: 'Data' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['CT-2023-0091', 'Marcelo Antônio Souza', 'Bianca Oliveira Santos', '02/07/2025', { selo: { texto: 'Aprovada', tom: 'ok' } }],
      ['CT-2024-0034', 'Cristina Aparecida Reis', 'Felipe Augusto Nunes', '10/07/2025', { selo: { texto: 'Em análise', tom: 'atencao' } }],
      ['CT-2022-0072', 'Alexandre José Pinto', 'Débora Cristina Farias', '18/06/2025', { selo: { texto: 'Aprovada', tom: 'ok' } }],
      ['CT-2024-0118', 'Simone Regina Batista', 'Rafael Eduardo Correia', '25/07/2025', { selo: { texto: 'Em análise', tom: 'atencao' } }],
      ['CT-2023-0049', 'Paulo Sérgio Vieira', 'Natália Cristina Moraes', '30/05/2025', { selo: { texto: 'Recusada', tom: 'vencido' } }],
    ],
  },
  '/contratos/transferencia': {
    titulo: 'Transferências', descricao: 'Transferências de lote entre contratos ativos', textoNovo: 'Nova transferência',
    colunas: [
      { titulo: 'Contrato origem' },
      { titulo: 'Contrato destino' },
      { titulo: 'Cliente', larga: true },
      { titulo: 'Lote' },
      { titulo: 'Data' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['CT-2023-0060', 'CT-2025-0210', 'Amanda Beatriz Souza', 'Quadra A / Lote 41', '08/07/2025', { selo: { texto: 'Concluída', tom: 'ok' } }],
      ['CT-2024-0075', 'CT-2025-0215', 'Bruno César Almeida', 'Quadra C / Lote 16', '14/07/2025', { selo: { texto: 'Em andamento', tom: 'info' } }],
      ['CT-2022-0038', 'CT-2025-0220', 'Priscila Fernanda Rocha', 'Quadra B / Lote 24', '20/06/2025', { selo: { texto: 'Concluída', tom: 'ok' } }],
      ['CT-2024-0092', 'CT-2025-0225', 'Wagner Luís Cardoso', 'Quadra D / Lote 06', '27/07/2025', { selo: { texto: 'Pendente', tom: 'atencao' } }],
      ['CT-2023-0104', 'CT-2025-0230', 'Aline Cristina Souza', 'Quadra A / Lote 12', '12/06/2025', { selo: { texto: 'Concluída', tom: 'ok' } }],
    ],
  },
  '/contratos/renegociacao': {
    titulo: 'Renegociações', descricao: 'Propostas de renegociação de saldo devedor', textoNovo: 'Nova renegociação',
    colunas: [
      { titulo: 'Contrato' },
      { titulo: 'Cliente', larga: true },
      { titulo: 'Saldo devedor', numerico: true },
      { titulo: 'Nova condição' },
      { titulo: 'Data' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['CT-2022-0015', 'Ricardo Alves Monteiro', 'R$ 87.400,00', '60x de R$ 1.520,00', '03/07/2025', { selo: { texto: 'Aprovada', tom: 'ok' } }],
      ['CT-2023-0083', 'Michele Cristina Gomes', 'R$ 62.900,00', '48x de R$ 1.380,00', '11/07/2025', { selo: { texto: 'Em análise', tom: 'atencao' } }],
      ['CT-2021-0027', 'Leandro José Barros', 'R$ 105.200,00', '72x de R$ 1.610,00', '19/06/2025', { selo: { texto: 'Aprovada', tom: 'ok' } }],
      ['CT-2024-0064', 'Tatiane Aparecida Lima', 'R$ 45.300,00', '36x de R$ 1.290,00', '24/07/2025', { selo: { texto: 'Recusada', tom: 'vencido' } }],
      ['CT-2022-0099', 'Fábio Rogério Duarte', 'R$ 73.850,00', '54x de R$ 1.445,00', '28/07/2025', { selo: { texto: 'Em análise', tom: 'atencao' } }],
    ],
  },
  '/contratos/aditivos': {
    titulo: 'Aditivos', descricao: 'Aditivos contratuais registrados', textoNovo: 'Novo aditivo',
    colunas: [
      { titulo: 'Contrato' },
      { titulo: 'Cliente', larga: true },
      { titulo: 'Tipo' },
      { titulo: 'Data' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['CT-2023-0055', 'Vinícius Rodrigues Faria', 'Prorrogação de prazo', '01/07/2025', { selo: { texto: 'Assinado', tom: 'ok' } }],
      ['CT-2024-0080', 'Carla Daniela Nogueira', 'Alteração de titularidade', '09/07/2025', { selo: { texto: 'Em elaboração', tom: 'neutro' } }],
      ['CT-2022-0041', 'Hugo Leonardo Castro', 'Retificação de área', '15/06/2025', { selo: { texto: 'Assinado', tom: 'ok' } }],
      ['CT-2024-0113', 'Elaine Cristina Sales', 'Alteração de índice', '22/07/2025', { selo: { texto: 'Pendente', tom: 'atencao' } }],
      ['CT-2023-0129', 'Rodrigo Nascimento Prado', 'Prorrogação de prazo', '26/07/2025', { selo: { texto: 'Assinado', tom: 'ok' } }],
    ],
  },
  '/contratos/reajustes': {
    titulo: 'Reajustes', descricao: 'Reajustes anuais aplicados aos contratos', textoNovo: 'Novo reajuste',
    colunas: [
      { titulo: 'Contrato' },
      { titulo: 'Cliente', larga: true },
      { titulo: 'Índice' },
      { titulo: 'Percentual', numerico: true },
      { titulo: 'Data de aplicação' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['CT-2022-0028', 'Renato César Oliveira', 'IGP-M', 4.7, '01/07/2025', { selo: { texto: 'Aplicado', tom: 'ok' } }],
      ['CT-2023-0071', 'Sandra Regina Alves', 'INCC', 3.9, '05/07/2025', { selo: { texto: 'Aplicado', tom: 'ok' } }],
      ['CT-2021-0019', 'Márcio Douglas Ribeiro', 'IPCA', 4.2, '10/07/2025', { selo: { texto: 'Pendente', tom: 'atencao' } }],
      ['CT-2024-0047', 'Denise Aparecida Freitas', 'IGP-M', 4.7, '15/07/2025', { selo: { texto: 'Pendente', tom: 'atencao' } }],
      ['CT-2022-0085', 'Otávio Augusto Peixoto', 'INCC', 3.9, '20/06/2025', { selo: { texto: 'Aplicado', tom: 'ok' } }],
    ],
  },
  '/contratos/historico': {
    titulo: 'Histórico de contratos', descricao: 'Linha do tempo de eventos por contrato', textoNovo: 'Registrar evento',
    colunas: [
      { titulo: 'Contrato' },
      { titulo: 'Cliente', larga: true },
      { titulo: 'Evento', larga: true },
      { titulo: 'Data' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['CT-2025-0123', 'Marcos Vinícius Andrade', 'Contrato gerado', '05/07/2025', { selo: { texto: 'Gerado', tom: 'info' } }],
      ['CT-2025-0123', 'Marcos Vinícius Andrade', 'Entrada quitada', '05/08/2025', { selo: { texto: 'Quitado', tom: 'ok' } }],
      ['CT-2024-0021', 'Eduardo Lima Barbosa', 'Distrato solicitado', '01/07/2025', { selo: { texto: 'Vencido', tom: 'vencido' } }],
      ['CT-2023-0091', 'Marcelo Antônio Souza', 'Cessão aprovada', '02/07/2025', { selo: { texto: 'Aprovada', tom: 'ok' } }],
      ['CT-2022-0015', 'Ricardo Alves Monteiro', 'Renegociação aprovada', '03/07/2025', { selo: { texto: 'Aprovada', tom: 'ok' } }],
    ],
  },
  '/contratos/assinatura': {
    titulo: 'Assinatura eletrônica', descricao: 'Contratos enviados para assinatura eletrônica', textoNovo: 'Enviar para assinatura',
    colunas: [
      { titulo: 'Contrato' },
      { titulo: 'Cliente', larga: true },
      { titulo: 'Plataforma' },
      { titulo: 'Envio' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['CT-2025-0231', 'Bruna Karoline Teixeira', 'Clicksign', '20/07/2025', { selo: { texto: 'Assinado', tom: 'ok' } }],
      ['CT-2025-0232', 'Igor Matheus Barros', 'DocuSign', '22/07/2025', { selo: { texto: 'Aguardando', tom: 'atencao' } }],
      ['CT-2025-0233', 'Yasmin Cristina Souza', 'Clicksign', '24/07/2025', { selo: { texto: 'Aguardando', tom: 'atencao' } }],
      ['CT-2025-0234', 'Caio Vinícius Rezende', 'DocuSign', '18/07/2025', { selo: { texto: 'Recusado', tom: 'vencido' } }],
      ['CT-2025-0235', 'Letícia Fernanda Duarte', 'Clicksign', '26/07/2025', { selo: { texto: 'Assinado', tom: 'ok' } }],
    ],
  },
  '/contratos/pdf': {
    titulo: 'Geração de PDF', descricao: 'Documentos de contrato gerados em PDF', textoNovo: 'Gerar PDF',
    colunas: [
      { titulo: 'Contrato' },
      { titulo: 'Cliente', larga: true },
      { titulo: 'Modelo' },
      { titulo: 'Gerado em' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['CT-2025-0123', 'Marcos Vinícius Andrade', 'Modelo padrão', '05/07/2025', { selo: { texto: 'Gerado', tom: 'info' } }],
      ['CT-2025-0145', 'Fernanda Cristina Lopes', 'Modelo com fiador', '07/07/2025', { selo: { texto: 'Gerado', tom: 'info' } }],
      ['CT-2025-0098', 'Roberto Carlos Nascimento', 'Modelo padrão', '10/07/2025', { selo: { texto: 'Erro na geração', tom: 'critico' } }],
      ['CT-2025-0201', 'Juliana Aparecida Souza', 'Modelo comercial', '15/07/2025', { selo: { texto: 'Gerado', tom: 'info' } }],
      ['CT-2025-0167', 'Anderson Luiz Ferreira', 'Modelo padrão', '20/07/2025', { selo: { texto: 'Pendente', tom: 'atencao' } }],
    ],
  },
  '/parcelas/geracao': {
    titulo: 'Geração automática', descricao: 'Lotes de parcelas gerados automaticamente por contrato', textoNovo: 'Gerar parcelas',
    colunas: [
      { titulo: 'Contrato' },
      { titulo: 'Cliente', larga: true },
      { titulo: 'Qtd. geradas', numerico: true },
      { titulo: 'Data de geração' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['CT-2025-0123', 'Marcos Vinícius Andrade', 120, '05/07/2025', { selo: { texto: 'Concluída', tom: 'ok' } }],
      ['CT-2025-0145', 'Fernanda Cristina Lopes', 96, '07/07/2025', { selo: { texto: 'Concluída', tom: 'ok' } }],
      ['CT-2025-0098', 'Roberto Carlos Nascimento', 144, '10/07/2025', { selo: { texto: 'Erro', tom: 'critico' } }],
      ['CT-2025-0201', 'Juliana Aparecida Souza', 84, '15/07/2025', { selo: { texto: 'Concluída', tom: 'ok' } }],
      ['CT-2025-0167', 'Anderson Luiz Ferreira', 120, '20/07/2025', { selo: { texto: 'Em andamento', tom: 'info' } }],
    ],
  },
  '/parcelas/regeracao': {
    titulo: 'Regeração de parcelas', descricao: 'Solicitações de regeração de plano de parcelas', textoNovo: 'Solicitar regeração',
    colunas: [
      { titulo: 'Contrato' },
      { titulo: 'Cliente', larga: true },
      { titulo: 'Motivo', larga: true },
      { titulo: 'Solicitado em' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['CT-2023-0083', 'Michele Cristina Gomes', 'Renegociação aprovada', '11/07/2025', { selo: { texto: 'Concluída', tom: 'ok' } }],
      ['CT-2022-0015', 'Ricardo Alves Monteiro', 'Alteração de índice', '03/07/2025', { selo: { texto: 'Concluída', tom: 'ok' } }],
      ['CT-2024-0064', 'Tatiane Aparecida Lima', 'Correção de valores', '24/07/2025', { selo: { texto: 'Em andamento', tom: 'info' } }],
      ['CT-2022-0099', 'Fábio Rogério Duarte', 'Renegociação aprovada', '28/07/2025', { selo: { texto: 'Pendente', tom: 'atencao' } }],
      ['CT-2021-0027', 'Leandro José Barros', 'Alteração de índice', '19/06/2025', { selo: { texto: 'Erro', tom: 'critico' } }],
    ],
  },
  '/parcelas/recalcular': {
    titulo: 'Recalcular parcelas', descricao: 'Solicitações de recálculo de saldo e parcelas', textoNovo: 'Solicitar recálculo',
    colunas: [
      { titulo: 'Contrato' },
      { titulo: 'Cliente', larga: true },
      { titulo: 'Saldo anterior', numerico: true },
      { titulo: 'Saldo recalculado', numerico: true },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['CT-2022-0028', 'Renato César Oliveira', 'R$ 92.100,00', 'R$ 96.400,00', { selo: { texto: 'Concluído', tom: 'ok' } }],
      ['CT-2023-0071', 'Sandra Regina Alves', 'R$ 58.300,00', 'R$ 60.600,00', { selo: { texto: 'Concluído', tom: 'ok' } }],
      ['CT-2021-0019', 'Márcio Douglas Ribeiro', 'R$ 110.500,00', 'R$ 115.100,00', { selo: { texto: 'Em andamento', tom: 'info' } }],
      ['CT-2024-0047', 'Denise Aparecida Freitas', 'R$ 47.800,00', 'R$ 49.800,00', { selo: { texto: 'Pendente', tom: 'atencao' } }],
      ['CT-2022-0085', 'Otávio Augusto Peixoto', 'R$ 71.200,00', 'R$ 74.000,00', { selo: { texto: 'Concluído', tom: 'ok' } }],
    ],
  },
  '/parcelas/baixa': {
    titulo: 'Baixa de parcelas', descricao: 'Registro de baixa de pagamentos recebidos', textoNovo: 'Registrar baixa',
    colunas: [
      { titulo: 'Contrato' },
      { titulo: 'Cliente', larga: true },
      { titulo: 'Parcela nº', numerico: true },
      { titulo: 'Valor pago', numerico: true },
      { titulo: 'Data do pagamento' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['CT-2025-0123', 'Marcos Vinícius Andrade', 3, 'R$ 1.480,00', '05/09/2025', { selo: { texto: 'Quitado', tom: 'ok' } }],
      ['CT-2025-0145', 'Fernanda Cristina Lopes', 2, 'R$ 1.985,00', '10/09/2025', { selo: { texto: 'Quitado', tom: 'ok' } }],
      ['CT-2025-0098', 'Roberto Carlos Nascimento', 5, 'R$ 1.230,00', '15/07/2025', { selo: { texto: 'Vencido', tom: 'vencido' } }],
      ['CT-2025-0201', 'Juliana Aparecida Souza', 1, 'R$ 2.150,00', '20/09/2025', { selo: { texto: 'A vencer', tom: 'atencao' } }],
      ['CT-2025-0167', 'Anderson Luiz Ferreira', 4, 'R$ 1.395,00', '25/09/2025', { selo: { texto: 'Quitado', tom: 'ok' } }],
    ],
  },
  '/parcelas/estorno': {
    titulo: 'Estornos', descricao: 'Estornos de pagamentos de parcelas', textoNovo: 'Novo estorno',
    colunas: [
      { titulo: 'Contrato' },
      { titulo: 'Cliente', larga: true },
      { titulo: 'Parcela nº', numerico: true },
      { titulo: 'Valor estornado', numerico: true },
      { titulo: 'Data' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['CT-2024-0056', 'Renata Cristina Pires', 7, 'R$ 1.610,00', '02/07/2025', { selo: { texto: 'Concluído', tom: 'ok' } }],
      ['CT-2023-0132', 'Diego Henrique Martins', 12, 'R$ 1.395,00', '08/07/2025', { selo: { texto: 'Em análise', tom: 'atencao' } }],
      ['CT-2024-0087', 'Camila Beatriz Rocha', 4, 'R$ 1.980,00', '14/07/2025', { selo: { texto: 'Concluído', tom: 'ok' } }],
      ['CT-2022-0011', 'Sérgio Ricardo Almeida', 9, 'R$ 1.720,00', '19/07/2025', { selo: { texto: 'Rejeitado', tom: 'vencido' } }],
      ['CT-2023-0044', 'Patrícia Helena Costa', 6, 'R$ 1.560,00', '25/07/2025', { selo: { texto: 'Em análise', tom: 'atencao' } }],
    ],
  },
  '/parcelas/antecipacao': {
    titulo: 'Antecipações', descricao: 'Solicitações de antecipação de parcelas futuras', textoNovo: 'Nova antecipação',
    colunas: [
      { titulo: 'Contrato' },
      { titulo: 'Cliente', larga: true },
      { titulo: 'Qtd. parcelas', numerico: true },
      { titulo: 'Valor com desconto', numerico: true },
      { titulo: 'Data' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['CT-2023-0055', 'Vinícius Rodrigues Faria', 12, 'R$ 16.800,00', '01/07/2025', { selo: { texto: 'Aprovada', tom: 'ok' } }],
      ['CT-2024-0080', 'Carla Daniela Nogueira', 6, 'R$ 9.450,00', '09/07/2025', { selo: { texto: 'Em análise', tom: 'atencao' } }],
      ['CT-2022-0041', 'Hugo Leonardo Castro', 24, 'R$ 31.200,00', '15/06/2025', { selo: { texto: 'Aprovada', tom: 'ok' } }],
      ['CT-2024-0113', 'Elaine Cristina Sales', 8, 'R$ 12.900,00', '22/07/2025', { selo: { texto: 'Recusada', tom: 'vencido' } }],
      ['CT-2023-0129', 'Rodrigo Nascimento Prado', 10, 'R$ 14.500,00', '26/07/2025', { selo: { texto: 'Em análise', tom: 'atencao' } }],
    ],
  },
  '/parcelas/liquidacao': {
    titulo: 'Liquidações', descricao: 'Liquidações totais de saldo devedor', textoNovo: 'Nova liquidação',
    colunas: [
      { titulo: 'Contrato' },
      { titulo: 'Cliente', larga: true },
      { titulo: 'Saldo liquidado', numerico: true },
      { titulo: 'Data' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['CT-2022-0028', 'Renato César Oliveira', 'R$ 96.400,00', '01/07/2025', { selo: { texto: 'Concluída', tom: 'ok' } }],
      ['CT-2023-0071', 'Sandra Regina Alves', 'R$ 60.600,00', '05/07/2025', { selo: { texto: 'Concluída', tom: 'ok' } }],
      ['CT-2021-0019', 'Márcio Douglas Ribeiro', 'R$ 115.100,00', '10/07/2025', { selo: { texto: 'Em processamento', tom: 'info' } }],
      ['CT-2024-0047', 'Denise Aparecida Freitas', 'R$ 49.800,00', '15/07/2025', { selo: { texto: 'Pendente', tom: 'atencao' } }],
      ['CT-2022-0085', 'Otávio Augusto Peixoto', 'R$ 74.000,00', '20/07/2025', { selo: { texto: 'Concluída', tom: 'ok' } }],
    ],
  },
  '/parcelas/segunda-via': {
    titulo: 'Segunda via', descricao: 'Emissões de segunda via de boleto', textoNovo: 'Emitir segunda via',
    colunas: [
      { titulo: 'Contrato' },
      { titulo: 'Cliente', larga: true },
      { titulo: 'Parcela nº', numerico: true },
      { titulo: 'Valor', numerico: true },
      { titulo: 'Novo vencimento' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['CT-2025-0123', 'Marcos Vinícius Andrade', 4, 'R$ 1.480,00', '10/09/2025', { selo: { texto: 'Emitida', tom: 'ok' } }],
      ['CT-2025-0145', 'Fernanda Cristina Lopes', 3, 'R$ 1.985,00', '12/09/2025', { selo: { texto: 'Emitida', tom: 'ok' } }],
      ['CT-2025-0098', 'Roberto Carlos Nascimento', 6, 'R$ 1.230,00', '18/07/2025', { selo: { texto: 'Vencido', tom: 'vencido' } }],
      ['CT-2025-0201', 'Juliana Aparecida Souza', 2, 'R$ 2.150,00', '22/09/2025', { selo: { texto: 'Emitida', tom: 'ok' } }],
      ['CT-2025-0167', 'Anderson Luiz Ferreira', 5, 'R$ 1.395,00', '26/09/2025', { selo: { texto: 'Pendente', tom: 'atencao' } }],
    ],
  },
  '/parcelas/negociacao': {
    titulo: 'Negociação', descricao: 'Propostas de negociação de parcelas em atraso', textoNovo: 'Nova negociação',
    colunas: [
      { titulo: 'Contrato' },
      { titulo: 'Cliente', larga: true },
      { titulo: 'Parcelas em atraso', numerico: true },
      { titulo: 'Valor negociado', numerico: true },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['CT-2023-0083', 'Michele Cristina Gomes', 3, 'R$ 4.140,00', { selo: { texto: 'Acordo firmado', tom: 'ok' } }],
      ['CT-2024-0064', 'Tatiane Aparecida Lima', 5, 'R$ 6.450,00', { selo: { texto: 'Em análise', tom: 'atencao' } }],
      ['CT-2022-0099', 'Fábio Rogério Duarte', 2, 'R$ 2.890,00', { selo: { texto: 'Acordo firmado', tom: 'ok' } }],
      ['CT-2021-0027', 'Leandro José Barros', 8, 'R$ 12.880,00', { selo: { texto: 'Inadimplente', tom: 'vencido' } }],
      ['CT-2022-0015', 'Ricardo Alves Monteiro', 4, 'R$ 6.080,00', { selo: { texto: 'Em análise', tom: 'atencao' } }],
    ],
  },
  '/parcelas/juros': {
    titulo: 'Juros', descricao: 'Encargos de juros aplicados a parcelas em atraso', textoNovo: 'Aplicar juros',
    colunas: [
      { titulo: 'Contrato' },
      { titulo: 'Cliente', larga: true },
      { titulo: 'Parcela nº', numerico: true },
      { titulo: 'Taxa a.m.', numerico: true },
      { titulo: 'Valor de juros', numerico: true },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['CT-2025-0098', 'Roberto Carlos Nascimento', 5, 1.0, 'R$ 12,30', { selo: { texto: 'Aplicado', tom: 'ok' } }],
      ['CT-2021-0027', 'Leandro José Barros', 9, 1.0, 'R$ 16,10', { selo: { texto: 'Aplicado', tom: 'ok' } }],
      ['CT-2024-0021', 'Eduardo Lima Barbosa', 11, 1.0, 'R$ 9,80', { selo: { texto: 'Pendente', tom: 'atencao' } }],
      ['CT-2022-0011', 'Sérgio Ricardo Almeida', 14, 1.0, 'R$ 17,20', { selo: { texto: 'Aplicado', tom: 'ok' } }],
      ['CT-2023-0132', 'Diego Henrique Martins', 8, 1.0, 'R$ 13,90', { selo: { texto: 'Pendente', tom: 'atencao' } }],
    ],
  },
  '/parcelas/multa': {
    titulo: 'Multa', descricao: 'Multas por atraso aplicadas a parcelas', textoNovo: 'Aplicar multa',
    colunas: [
      { titulo: 'Contrato' },
      { titulo: 'Cliente', larga: true },
      { titulo: 'Parcela nº', numerico: true },
      { titulo: 'Percentual', numerico: true },
      { titulo: 'Valor da multa', numerico: true },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['CT-2025-0098', 'Roberto Carlos Nascimento', 5, 2.0, 'R$ 24,60', { selo: { texto: 'Aplicada', tom: 'ok' } }],
      ['CT-2021-0027', 'Leandro José Barros', 9, 2.0, 'R$ 32,20', { selo: { texto: 'Aplicada', tom: 'ok' } }],
      ['CT-2024-0021', 'Eduardo Lima Barbosa', 11, 2.0, 'R$ 19,60', { selo: { texto: 'Pendente', tom: 'atencao' } }],
      ['CT-2022-0011', 'Sérgio Ricardo Almeida', 14, 2.0, 'R$ 34,40', { selo: { texto: 'Aplicada', tom: 'ok' } }],
      ['CT-2023-0132', 'Diego Henrique Martins', 8, 2.0, 'R$ 27,80', { selo: { texto: 'Pendente', tom: 'atencao' } }],
    ],
  },
  '/parcelas/correcao': {
    titulo: 'Correção monetária', descricao: 'Correção monetária aplicada às parcelas por índice contratual', textoNovo: 'Aplicar correção',
    colunas: [
      { titulo: 'Contrato' },
      { titulo: 'Cliente', larga: true },
      { titulo: 'Índice' },
      { titulo: 'Percentual', numerico: true },
      { titulo: 'Valor corrigido', numerico: true },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['CT-2022-0028', 'Renato César Oliveira', 'IGP-M', 4.7, 'R$ 1.549,60', { selo: { texto: 'Aplicada', tom: 'ok' } }],
      ['CT-2023-0071', 'Sandra Regina Alves', 'INCC', 3.9, 'R$ 2.062,42', { selo: { texto: 'Aplicada', tom: 'ok' } }],
      ['CT-2021-0019', 'Márcio Douglas Ribeiro', 'IPCA', 4.2, 'R$ 1.282,08', { selo: { texto: 'Pendente', tom: 'atencao' } }],
      ['CT-2024-0047', 'Denise Aparecida Freitas', 'IGP-M', 4.7, 'R$ 1.460,52', { selo: { texto: 'Pendente', tom: 'atencao' } }],
      ['CT-2022-0085', 'Otávio Augusto Peixoto', 'INCC', 3.9, 'R$ 1.278,44', { selo: { texto: 'Aplicada', tom: 'ok' } }],
    ],
  },
  '/parcelas/descontos': {
    titulo: 'Descontos', descricao: 'Descontos concedidos em parcelas pontuais', textoNovo: 'Conceder desconto',
    colunas: [
      { titulo: 'Contrato' },
      { titulo: 'Cliente', larga: true },
      { titulo: 'Parcela nº', numerico: true },
      { titulo: 'Percentual', numerico: true },
      { titulo: 'Valor do desconto', numerico: true },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['CT-2025-0123', 'Marcos Vinícius Andrade', 3, 5.0, 'R$ 74,00', { selo: { texto: 'Aprovado', tom: 'ok' } }],
      ['CT-2025-0145', 'Fernanda Cristina Lopes', 2, 10.0, 'R$ 198,50', { selo: { texto: 'Em análise', tom: 'atencao' } }],
      ['CT-2025-0098', 'Roberto Carlos Nascimento', 5, 5.0, 'R$ 61,50', { selo: { texto: 'Recusado', tom: 'vencido' } }],
      ['CT-2025-0201', 'Juliana Aparecida Souza', 1, 8.0, 'R$ 172,00', { selo: { texto: 'Aprovado', tom: 'ok' } }],
      ['CT-2025-0167', 'Anderson Luiz Ferreira', 4, 5.0, 'R$ 69,75', { selo: { texto: 'Em análise', tom: 'atencao' } }],
    ],
  },
};

export default telas;
