import type { ConfigDeListagem } from '@/componentes/comuns/PaginaDeListagem';

const telas: Record<string, ConfigDeListagem> = {
  '/crm/leads': {
    titulo: 'Leads', descricao: 'Potenciais clientes captados pelos canais de marketing e vendas.', textoNovo: 'Novo lead',
    colunas: [
      { titulo: 'Nome', larga: true },
      { titulo: 'Origem' },
      { titulo: 'Telefone' },
      { titulo: 'Loteamento de interesse', larga: true },
      { titulo: 'Cadastrado em' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Marcos Vinícius Almeida', 'Facebook Ads', '(95) 9 9812-3344', 'Residencial Monte Cristo', '02/07/2026', { selo: { texto: 'Novo', tom: 'info' } }],
      ['Fernanda Costa Braga', 'Indicação', '(95) 9 9765-1122', 'Loteamento Águas Claras', '05/07/2026', { selo: { texto: 'Em contato', tom: 'info' } }],
      ['Ricardo Souza Lima', 'Instagram', '(95) 9 9988-4455', 'Residencial Monte Cristo', '10/07/2026', { selo: { texto: 'Qualificado', tom: 'atencao' } }],
      ['Juliana Pereira Nunes', 'Site Gestrato', '(95) 9 9654-7788', 'Chácaras Boa Vista Sul', '15/07/2026', { selo: { texto: 'Frio', tom: 'neutro' } }],
      ['Antônio Carlos Freitas', 'Panfletagem', '(95) 9 9877-2233', 'Loteamento Águas Claras', '20/07/2026', { selo: { texto: 'Perdido', tom: 'vencido' } }],
    ],
  },
  '/crm/funil': {
    titulo: 'Funil de vendas', descricao: 'Oportunidades organizadas por etapa do processo comercial.', textoNovo: 'Nova oportunidade',
    colunas: [
      { titulo: 'Cliente', larga: true },
      { titulo: 'Etapa' },
      { titulo: 'Vendedor' },
      { titulo: 'Valor estimado', numerico: true },
      { titulo: 'Última atualização' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Paulo Roberto Guedes', 'Negociação', 'Camila Rodrigues', 'R$ 185.000,00', '18/07/2026', { selo: { texto: 'Em negociação', tom: 'atencao' } }],
      ['Vanessa Lopes Torres', 'Proposta enviada', 'Diego Martins', 'R$ 92.500,00', '19/07/2026', { selo: { texto: 'Em negociação', tom: 'atencao' } }],
      ['Eduardo Nogueira Sá', 'Fechamento', 'Camila Rodrigues', 'R$ 210.000,00', '22/07/2026', { selo: { texto: 'Ganho', tom: 'ok' } }],
      ['Larissa Andrade Melo', 'Qualificação', 'Diego Martins', 'R$ 78.000,00', '24/07/2026', { selo: { texto: 'Novo', tom: 'info' } }],
      ['Gustavo Henrique Reis', 'Fechamento', 'Camila Rodrigues', 'R$ 145.000,00', '26/07/2026', { selo: { texto: 'Perdido', tom: 'vencido' } }],
    ],
  },
  '/crm/atendimento': {
    titulo: 'Atendimentos', descricao: 'Registro dos atendimentos realizados pela equipe comercial.', textoNovo: 'Novo atendimento',
    colunas: [
      { titulo: 'Cliente', larga: true },
      { titulo: 'Canal' },
      { titulo: 'Atendente' },
      { titulo: 'Duração' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Mariana Duarte Costa', 'Telefone', 'Beatriz Farias', '00:12:34', { selo: { texto: 'Concluído', tom: 'ok' } }],
      ['José Adilson Barros', 'WhatsApp', 'Diego Martins', '00:05:10', { selo: { texto: 'Aguardando retorno', tom: 'atencao' } }],
      ['Cláudia Regina Vieira', 'Presencial', 'Camila Rodrigues', '00:35:00', { selo: { texto: 'Concluído', tom: 'ok' } }],
      ['Wellington Souza Dias', 'E-mail', 'Beatriz Farias', '00:02:45', { selo: { texto: 'Em andamento', tom: 'info' } }],
      ['Rosana Aparecida Melo', 'WhatsApp', 'Diego Martins', '00:08:20', { selo: { texto: 'Cancelado', tom: 'vencido' } }],
    ],
  },
  '/crm/agenda': {
    titulo: 'Agenda do CRM', descricao: 'Compromissos e tarefas agendadas com clientes e leads.', textoNovo: 'Novo compromisso',
    colunas: [
      { titulo: 'Cliente', larga: true },
      { titulo: 'Tipo' },
      { titulo: 'Responsável' },
      { titulo: 'Data' },
      { titulo: 'Horário' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Marcos Vinícius Almeida', 'Ligação', 'Camila Rodrigues', '30/07/2026', '09:00', { selo: { texto: 'Pendente', tom: 'atencao' } }],
      ['Fernanda Costa Braga', 'Visita ao lote', 'Diego Martins', '30/07/2026', '14:30', { selo: { texto: 'Confirmado', tom: 'ok' } }],
      ['Eduardo Nogueira Sá', 'Reunião', 'Beatriz Farias', '31/07/2026', '10:15', { selo: { texto: 'Pendente', tom: 'atencao' } }],
      ['Larissa Andrade Melo', 'Ligação', 'Camila Rodrigues', '01/08/2026', '16:00', { selo: { texto: 'Confirmado', tom: 'ok' } }],
      ['Ricardo Souza Lima', 'Visita ao lote', 'Diego Martins', '02/08/2026', '11:00', { selo: { texto: 'Cancelado', tom: 'vencido' } }],
    ],
  },
  '/crm/visitas': {
    titulo: 'Visitas', descricao: 'Visitas agendadas e realizadas aos loteamentos.', textoNovo: 'Nova visita',
    colunas: [
      { titulo: 'Cliente', larga: true },
      { titulo: 'Loteamento', larga: true },
      { titulo: 'Corretor' },
      { titulo: 'Data' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Paulo Roberto Guedes', 'Residencial Monte Cristo', 'Camila Rodrigues', '20/07/2026', { selo: { texto: 'Realizada', tom: 'ok' } }],
      ['Vanessa Lopes Torres', 'Chácaras Boa Vista Sul', 'Diego Martins', '22/07/2026', { selo: { texto: 'Agendada', tom: 'info' } }],
      ['Gustavo Henrique Reis', 'Loteamento Águas Claras', 'Beatriz Farias', '24/07/2026', { selo: { texto: 'Realizada', tom: 'ok' } }],
      ['Juliana Pereira Nunes', 'Residencial Monte Cristo', 'Camila Rodrigues', '27/07/2026', { selo: { texto: 'Agendada', tom: 'info' } }],
      ['Antônio Carlos Freitas', 'Chácaras Boa Vista Sul', 'Diego Martins', '28/07/2026', { selo: { texto: 'Não compareceu', tom: 'vencido' } }],
    ],
  },
  '/crm/ligacoes': {
    titulo: 'Ligações', descricao: 'Histórico de ligações realizadas e recebidas pela equipe.', textoNovo: 'Registrar ligação',
    colunas: [
      { titulo: 'Cliente', larga: true },
      { titulo: 'Tipo' },
      { titulo: 'Atendente' },
      { titulo: 'Duração' },
      { titulo: 'Data' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Mariana Duarte Costa', 'Recebida', 'Beatriz Farias', '00:04:12', '21/07/2026', { selo: { texto: 'Concluída', tom: 'ok' } }],
      ['José Adilson Barros', 'Efetuada', 'Diego Martins', '00:01:50', '22/07/2026', { selo: { texto: 'Não atendida', tom: 'vencido' } }],
      ['Cláudia Regina Vieira', 'Efetuada', 'Camila Rodrigues', '00:09:33', '23/07/2026', { selo: { texto: 'Concluída', tom: 'ok' } }],
      ['Wellington Souza Dias', 'Recebida', 'Beatriz Farias', '00:03:07', '24/07/2026', { selo: { texto: 'Concluída', tom: 'ok' } }],
      ['Rosana Aparecida Melo', 'Efetuada', 'Diego Martins', '00:00:00', '25/07/2026', { selo: { texto: 'Não atendida', tom: 'vencido' } }],
    ],
  },
  '/crm/whatsapp': {
    titulo: 'WhatsApp', descricao: 'Conversas em andamento pelo WhatsApp Business.', textoNovo: 'Nova conversa',
    colunas: [
      { titulo: 'Cliente', larga: true },
      { titulo: 'Última mensagem', larga: true },
      { titulo: 'Atendente' },
      { titulo: 'Recebida em' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Marcos Vinícius Almeida', 'Gostaria de saber o valor da entrada', 'Camila Rodrigues', '25/07/2026 09:12', { selo: { texto: 'Aguardando resposta', tom: 'atencao' } }],
      ['Fernanda Costa Braga', 'Obrigada, vou avaliar a proposta', 'Diego Martins', '26/07/2026 15:40', { selo: { texto: 'Respondida', tom: 'ok' } }],
      ['Ricardo Souza Lima', 'Pode me mandar a localização do lote?', 'Beatriz Farias', '27/07/2026 10:05', { selo: { texto: 'Aguardando resposta', tom: 'atencao' } }],
      ['Juliana Pereira Nunes', 'Vou levar minha esposa para visitar', 'Camila Rodrigues', '28/07/2026 17:22', { selo: { texto: 'Respondida', tom: 'ok' } }],
      ['Antônio Carlos Freitas', 'Não tenho mais interesse, obrigado', 'Diego Martins', '29/07/2026 08:15', { selo: { texto: 'Encerrada', tom: 'neutro' } }],
    ],
  },
  '/crm/historico': {
    titulo: 'Histórico de interações', descricao: 'Linha do tempo consolidada de todos os contatos com o cliente.', textoNovo: 'Nova interação',
    colunas: [
      { titulo: 'Cliente', larga: true },
      { titulo: 'Canal' },
      { titulo: 'Resumo', larga: true },
      { titulo: 'Data' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Paulo Roberto Guedes', 'Ligação', 'Interesse confirmado no lote 14, quadra B', '15/07/2026', { selo: { texto: 'Concluída', tom: 'ok' } }],
      ['Vanessa Lopes Torres', 'E-mail', 'Envio da proposta comercial atualizada', '17/07/2026', { selo: { texto: 'Concluída', tom: 'ok' } }],
      ['Eduardo Nogueira Sá', 'WhatsApp', 'Confirmação de visita ao loteamento', '19/07/2026', { selo: { texto: 'Concluída', tom: 'ok' } }],
      ['Larissa Andrade Melo', 'Presencial', 'Reunião de negociação de condições', '21/07/2026', { selo: { texto: 'Em andamento', tom: 'info' } }],
      ['Gustavo Henrique Reis', 'Ligação', 'Cliente solicitou cancelamento da reserva', '23/07/2026', { selo: { texto: 'Cancelada', tom: 'vencido' } }],
    ],
  },
  '/crm/propostas': {
    titulo: 'Propostas', descricao: 'Propostas comerciais enviadas aos clientes.', textoNovo: 'Nova proposta',
    colunas: [
      { titulo: 'Cliente', larga: true },
      { titulo: 'Loteamento', larga: true },
      { titulo: 'Valor', numerico: true },
      { titulo: 'Validade' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Marcos Vinícius Almeida', 'Residencial Monte Cristo', 'R$ 165.000,00', '10/08/2026', { selo: { texto: 'Enviada', tom: 'info' } }],
      ['Fernanda Costa Braga', 'Loteamento Águas Claras', 'R$ 198.000,00', '12/08/2026', { selo: { texto: 'Aceita', tom: 'ok' } }],
      ['Ricardo Souza Lima', 'Chácaras Boa Vista Sul', 'R$ 220.500,00', '08/08/2026', { selo: { texto: 'Em análise', tom: 'atencao' } }],
      ['Juliana Pereira Nunes', 'Residencial Monte Cristo', 'R$ 152.300,00', '05/08/2026', { selo: { texto: 'Recusada', tom: 'vencido' } }],
      ['Antônio Carlos Freitas', 'Loteamento Águas Claras', 'R$ 175.000,00', '14/08/2026', { selo: { texto: 'Enviada', tom: 'info' } }],
    ],
  },
  '/crm/simulacoes': {
    titulo: 'Simulações', descricao: 'Simulações de financiamento direto realizadas para clientes.', textoNovo: 'Nova simulação',
    colunas: [
      { titulo: 'Cliente', larga: true },
      { titulo: 'Lote' },
      { titulo: 'Entrada', numerico: true },
      { titulo: 'Parcelas', numerico: true },
      { titulo: 'Valor da parcela', numerico: true },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Mariana Duarte Costa', 'Quadra A, Lote 07', 'R$ 15.000,00', 120, 'R$ 1.480,00', { selo: { texto: 'Salva', tom: 'neutro' } }],
      ['José Adilson Barros', 'Quadra C, Lote 22', 'R$ 20.000,00', 96, 'R$ 1.890,00', { selo: { texto: 'Enviada', tom: 'info' } }],
      ['Cláudia Regina Vieira', 'Quadra B, Lote 14', 'R$ 10.000,00', 144, 'R$ 1.320,00', { selo: { texto: 'Aprovada', tom: 'ok' } }],
      ['Wellington Souza Dias', 'Quadra D, Lote 03', 'R$ 25.000,00', 84, 'R$ 2.150,00', { selo: { texto: 'Salva', tom: 'neutro' } }],
      ['Rosana Aparecida Melo', 'Quadra A, Lote 19', 'R$ 12.500,00', 120, 'R$ 1.610,00', { selo: { texto: 'Recusada', tom: 'vencido' } }],
    ],
  },
  '/crm/reserva-de-lote': {
    titulo: 'Reservas de lote', descricao: 'Reservas temporárias de lotes vinculadas a oportunidades do CRM.', textoNovo: 'Nova reserva',
    colunas: [
      { titulo: 'Cliente', larga: true },
      { titulo: 'Lote' },
      { titulo: 'Corretor' },
      { titulo: 'Válida até' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Paulo Roberto Guedes', 'Quadra B, Lote 14', 'Camila Rodrigues', '05/08/2026', { selo: { texto: 'Ativa', tom: 'ok' } }],
      ['Vanessa Lopes Torres', 'Quadra A, Lote 07', 'Diego Martins', '02/08/2026', { selo: { texto: 'Ativa', tom: 'ok' } }],
      ['Eduardo Nogueira Sá', 'Quadra C, Lote 22', 'Camila Rodrigues', '30/07/2026', { selo: { texto: 'Expirando', tom: 'atencao' } }],
      ['Larissa Andrade Melo', 'Quadra D, Lote 03', 'Beatriz Farias', '25/07/2026', { selo: { texto: 'Expirada', tom: 'vencido' } }],
      ['Gustavo Henrique Reis', 'Quadra A, Lote 19', 'Diego Martins', '10/08/2026', { selo: { texto: 'Ativa', tom: 'ok' } }],
    ],
  },
  '/crm/conversao': {
    titulo: 'Conversão em contrato', descricao: 'Reservas e propostas prontas para conversão em contrato de venda.', textoNovo: 'Converter em contrato',
    colunas: [
      { titulo: 'Cliente', larga: true },
      { titulo: 'Lote' },
      { titulo: 'Valor do contrato', numerico: true },
      { titulo: 'Corretor' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Fernanda Costa Braga', 'Quadra A, Lote 07', 'R$ 198.000,00', 'Diego Martins', { selo: { texto: 'Convertido', tom: 'ok' } }],
      ['Ricardo Souza Lima', 'Quadra C, Lote 22', 'R$ 220.500,00', 'Beatriz Farias', { selo: { texto: 'Em análise', tom: 'atencao' } }],
      ['Juliana Pereira Nunes', 'Quadra B, Lote 14', 'R$ 152.300,00', 'Camila Rodrigues', { selo: { texto: 'Pendente', tom: 'atencao' } }],
      ['Antônio Carlos Freitas', 'Quadra D, Lote 03', 'R$ 175.000,00', 'Diego Martins', { selo: { texto: 'Convertido', tom: 'ok' } }],
      ['Mariana Duarte Costa', 'Quadra A, Lote 19', 'R$ 168.900,00', 'Beatriz Farias', { selo: { texto: 'Cancelado', tom: 'vencido' } }],
    ],
  },
  '/clientes/historico': {
    titulo: 'Histórico do cliente', descricao: 'Eventos e movimentações registrados no cadastro do cliente.', textoNovo: 'Novo registro',
    colunas: [
      { titulo: 'Cliente', larga: true },
      { titulo: 'Evento', larga: true },
      { titulo: 'Responsável' },
      { titulo: 'Data' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['José Adilson Barros', 'Alteração de endereço', 'Beatriz Farias', '10/07/2026', { selo: { texto: 'Concluído', tom: 'ok' } }],
      ['Cláudia Regina Vieira', 'Emissão de 2ª via de contrato', 'Camila Rodrigues', '12/07/2026', { selo: { texto: 'Concluído', tom: 'ok' } }],
      ['Wellington Souza Dias', 'Renegociação de parcelas', 'Diego Martins', '15/07/2026', { selo: { texto: 'Em andamento', tom: 'info' } }],
      ['Rosana Aparecida Melo', 'Atualização de telefone', 'Beatriz Farias', '18/07/2026', { selo: { texto: 'Concluído', tom: 'ok' } }],
      ['Marcos Vinícius Almeida', 'Solicitação de distrato', 'Camila Rodrigues', '20/07/2026', { selo: { texto: 'Pendente', tom: 'atencao' } }],
    ],
  },
  '/clientes/documentos': {
    titulo: 'Documentos do cliente', descricao: 'Documentos pessoais cadastrados para cada cliente.', textoNovo: 'Novo documento',
    colunas: [
      { titulo: 'Cliente', larga: true },
      { titulo: 'Tipo de documento' },
      { titulo: 'Número' },
      { titulo: 'Validade' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Fernanda Costa Braga', 'RG', '1.234.567 SSP/RR', '—', { selo: { texto: 'Válido', tom: 'ok' } }],
      ['Ricardo Souza Lima', 'CNH', '98765432100', '22/03/2028', { selo: { texto: 'Válido', tom: 'ok' } }],
      ['Juliana Pereira Nunes', 'CPF', '456.789.123-00', '—', { selo: { texto: 'Válido', tom: 'ok' } }],
      ['Antônio Carlos Freitas', 'RG', '2.345.678 SSP/AM', '—', { selo: { texto: 'Pendente de envio', tom: 'atencao' } }],
      ['Mariana Duarte Costa', 'CNH', '12345678900', '05/01/2025', { selo: { texto: 'Vencido', tom: 'vencido' } }],
    ],
  },
  '/clientes/anexos': {
    titulo: 'Anexos', descricao: 'Arquivos e comprovantes anexados ao cadastro do cliente.', textoNovo: 'Novo anexo',
    colunas: [
      { titulo: 'Cliente', larga: true },
      { titulo: 'Arquivo', larga: true },
      { titulo: 'Tamanho' },
      { titulo: 'Enviado em' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['José Adilson Barros', 'comprovante_residencia.pdf', '842 KB', '11/07/2026', { selo: { texto: 'Aprovado', tom: 'ok' } }],
      ['Cláudia Regina Vieira', 'contracheque_junho.pdf', '510 KB', '13/07/2026', { selo: { texto: 'Aprovado', tom: 'ok' } }],
      ['Wellington Souza Dias', 'rg_frente_verso.jpg', '1,2 MB', '16/07/2026', { selo: { texto: 'Em análise', tom: 'atencao' } }],
      ['Rosana Aparecida Melo', 'certidao_casamento.pdf', '690 KB', '19/07/2026', { selo: { texto: 'Aprovado', tom: 'ok' } }],
      ['Marcos Vinícius Almeida', 'extrato_bancario.pdf', '980 KB', '21/07/2026', { selo: { texto: 'Reprovado', tom: 'vencido' } }],
    ],
  },
  '/clientes/dependentes': {
    titulo: 'Dependentes', descricao: 'Dependentes vinculados ao cadastro dos clientes.', textoNovo: 'Novo dependente',
    colunas: [
      { titulo: 'Cliente', larga: true },
      { titulo: 'Dependente', larga: true },
      { titulo: 'Parentesco' },
      { titulo: 'Data de nascimento' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Fernanda Costa Braga', 'Lucas Costa Braga', 'Filho', '14/02/2015', { selo: { texto: 'Ativo', tom: 'ok' } }],
      ['Ricardo Souza Lima', 'Ana Beatriz Souza Lima', 'Filha', '22/09/2018', { selo: { texto: 'Ativo', tom: 'ok' } }],
      ['Juliana Pereira Nunes', 'Rafael Pereira Nunes', 'Filho', '03/11/2012', { selo: { texto: 'Ativo', tom: 'ok' } }],
      ['Antônio Carlos Freitas', 'Sônia Maria Freitas', 'Cônjuge', '19/05/1980', { selo: { texto: 'Ativo', tom: 'ok' } }],
      ['Mariana Duarte Costa', 'Pedro Duarte Costa', 'Filho', '30/07/2020', { selo: { texto: 'Inativo', tom: 'neutro' } }],
    ],
  },
  '/clientes/referencias': {
    titulo: 'Referências', descricao: 'Referências pessoais e comerciais informadas pelos clientes.', textoNovo: 'Nova referência',
    colunas: [
      { titulo: 'Cliente', larga: true },
      { titulo: 'Referência', larga: true },
      { titulo: 'Tipo' },
      { titulo: 'Telefone' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['José Adilson Barros', 'Carlos Eduardo Ramos', 'Pessoal', '(95) 9 9711-2288', { selo: { texto: 'Confirmada', tom: 'ok' } }],
      ['Cláudia Regina Vieira', 'Loja Móveis Boa Vista', 'Comercial', '(95) 3624-5566', { selo: { texto: 'Confirmada', tom: 'ok' } }],
      ['Wellington Souza Dias', 'Simone Alves Pinto', 'Pessoal', '(95) 9 9822-3399', { selo: { texto: 'Aguardando contato', tom: 'atencao' } }],
      ['Rosana Aparecida Melo', 'Mercadinho Central Ltda', 'Comercial', '(95) 3625-7788', { selo: { texto: 'Confirmada', tom: 'ok' } }],
      ['Marcos Vinícius Almeida', 'Fábio Rocha Teixeira', 'Pessoal', '(95) 9 9933-4411', { selo: { texto: 'Não localizada', tom: 'vencido' } }],
    ],
  },
  '/clientes/enderecos': {
    titulo: 'Endereços', descricao: 'Endereços residenciais e de correspondência dos clientes.', textoNovo: 'Novo endereço',
    colunas: [
      { titulo: 'Cliente', larga: true },
      { titulo: 'Endereço', larga: true },
      { titulo: 'Cidade' },
      { titulo: 'CEP' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Fernanda Costa Braga', 'Rua Jardim Primavera, 145', 'Boa Vista - RR', '69301-140', { selo: { texto: 'Confirmado', tom: 'ok' } }],
      ['Ricardo Souza Lima', 'Av. Ville Roy, 890', 'Boa Vista - RR', '69305-030', { selo: { texto: 'Confirmado', tom: 'ok' } }],
      ['Juliana Pereira Nunes', 'Rua Manaus, 22', 'Rorainópolis - RR', '69373-000', { selo: { texto: 'A confirmar', tom: 'atencao' } }],
      ['Antônio Carlos Freitas', 'Av. Mário Homem de Melo, 512', 'Manaus - AM', '69020-030', { selo: { texto: 'Confirmado', tom: 'ok' } }],
      ['Mariana Duarte Costa', 'Rua das Acácias, 78', 'Caracaraí - RR', '69360-000', { selo: { texto: 'Desatualizado', tom: 'vencido' } }],
    ],
  },
  '/clientes/contatos': {
    titulo: 'Contatos', descricao: 'Canais de contato cadastrados para cada cliente.', textoNovo: 'Novo contato',
    colunas: [
      { titulo: 'Cliente', larga: true },
      { titulo: 'Telefone' },
      { titulo: 'E-mail', larga: true },
      { titulo: 'Preferência' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['José Adilson Barros', '(95) 9 9711-2288', 'jose.barros@gmail.com', 'WhatsApp', { selo: { texto: 'Ativo', tom: 'ok' } }],
      ['Cláudia Regina Vieira', '(95) 9 9822-3399', 'claudia.vieira@hotmail.com', 'Telefone', { selo: { texto: 'Ativo', tom: 'ok' } }],
      ['Wellington Souza Dias', '(95) 9 9933-4411', 'wellington.dias@outlook.com', 'E-mail', { selo: { texto: 'Ativo', tom: 'ok' } }],
      ['Rosana Aparecida Melo', '(95) 9 9644-5522', 'rosana.melo@gmail.com', 'WhatsApp', { selo: { texto: 'Inativo', tom: 'neutro' } }],
      ['Marcos Vinícius Almeida', '(95) 9 9812-3344', 'marcos.almeida@yahoo.com', 'Telefone', { selo: { texto: 'Ativo', tom: 'ok' } }],
    ],
  },
  '/clientes/consulta-cpf': {
    titulo: 'Consulta CPF', descricao: 'Consultas de CPF realizadas em órgãos de proteção ao crédito.', textoNovo: 'Nova consulta',
    colunas: [
      { titulo: 'Cliente', larga: true },
      { titulo: 'CPF' },
      { titulo: 'Consultado em' },
      { titulo: 'Restrições', numerico: true },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Fernanda Costa Braga', '123.456.789-00', '20/07/2026', 0, { selo: { texto: 'Regular', tom: 'ok' } }],
      ['Ricardo Souza Lima', '234.567.890-11', '21/07/2026', 0, { selo: { texto: 'Regular', tom: 'ok' } }],
      ['Juliana Pereira Nunes', '345.678.901-22', '22/07/2026', 2, { selo: { texto: 'Com restrição', tom: 'critico' } }],
      ['Antônio Carlos Freitas', '456.789.012-33', '23/07/2026', 0, { selo: { texto: 'Regular', tom: 'ok' } }],
      ['Mariana Duarte Costa', '567.890.123-44', '24/07/2026', 1, { selo: { texto: 'Com restrição', tom: 'critico' } }],
    ],
  },
  '/clientes/score': {
    titulo: 'Score de crédito', descricao: 'Pontuação de crédito consultada para análise de propostas.', textoNovo: 'Nova consulta',
    colunas: [
      { titulo: 'Cliente', larga: true },
      { titulo: 'Score', numerico: true },
      { titulo: 'Faixa' },
      { titulo: 'Consultado em' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['José Adilson Barros', 812, 'Excelente', '18/07/2026', { selo: { texto: 'Aprovado', tom: 'ok' } }],
      ['Cláudia Regina Vieira', 645, 'Bom', '19/07/2026', { selo: { texto: 'Aprovado', tom: 'ok' } }],
      ['Wellington Souza Dias', 410, 'Regular', '20/07/2026', { selo: { texto: 'Em análise', tom: 'atencao' } }],
      ['Rosana Aparecida Melo', 290, 'Baixo', '21/07/2026', { selo: { texto: 'Reprovado', tom: 'vencido' } }],
      ['Marcos Vinícius Almeida', 720, 'Bom', '22/07/2026', { selo: { texto: 'Aprovado', tom: 'ok' } }],
    ],
  },
  '/clientes/timeline': {
    titulo: 'Timeline', descricao: 'Linha do tempo de eventos e marcos importantes do cliente.', textoNovo: 'Novo evento',
    colunas: [
      { titulo: 'Cliente', larga: true },
      { titulo: 'Evento', larga: true },
      { titulo: 'Categoria' },
      { titulo: 'Data' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Fernanda Costa Braga', 'Assinatura do contrato de compra e venda', 'Comercial', '10/06/2026', { selo: { texto: 'Concluído', tom: 'ok' } }],
      ['Ricardo Souza Lima', 'Pagamento da 1ª parcela em atraso', 'Financeiro', '05/07/2026', { selo: { texto: 'Vencido', tom: 'vencido' } }],
      ['Juliana Pereira Nunes', 'Alteração de plano de pagamento', 'Financeiro', '12/07/2026', { selo: { texto: 'Concluído', tom: 'ok' } }],
      ['Antônio Carlos Freitas', 'Abertura de chamado de suporte', 'Atendimento', '16/07/2026', { selo: { texto: 'Em andamento', tom: 'info' } }],
      ['Mariana Duarte Costa', 'Solicitação de distrato do contrato', 'Comercial', '20/07/2026', { selo: { texto: 'Pendente', tom: 'atencao' } }],
    ],
  },
  '/comercial/reserva-de-lotes': {
    titulo: 'Reserva de lotes', descricao: 'Lotes reservados aguardando formalização da venda.', textoNovo: 'Nova reserva',
    colunas: [
      { titulo: 'Lote' },
      { titulo: 'Loteamento', larga: true },
      { titulo: 'Cliente', larga: true },
      { titulo: 'Valor', numerico: true },
      { titulo: 'Válida até' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Quadra B, Lote 14', 'Residencial Monte Cristo', 'Paulo Roberto Guedes', 'R$ 165.000,00', '05/08/2026', { selo: { texto: 'Ativa', tom: 'ok' } }],
      ['Quadra A, Lote 07', 'Loteamento Águas Claras', 'Vanessa Lopes Torres', 'R$ 198.000,00', '02/08/2026', { selo: { texto: 'Ativa', tom: 'ok' } }],
      ['Quadra C, Lote 22', 'Chácaras Boa Vista Sul', 'Eduardo Nogueira Sá', 'R$ 220.500,00', '30/07/2026', { selo: { texto: 'Expirando', tom: 'atencao' } }],
      ['Quadra D, Lote 03', 'Residencial Monte Cristo', 'Larissa Andrade Melo', 'R$ 152.300,00', '25/07/2026', { selo: { texto: 'Expirada', tom: 'vencido' } }],
      ['Quadra A, Lote 19', 'Loteamento Águas Claras', 'Gustavo Henrique Reis', 'R$ 175.000,00', '10/08/2026', { selo: { texto: 'Ativa', tom: 'ok' } }],
    ],
  },
  '/comercial/venda': {
    titulo: 'Vendas', descricao: 'Contratos de venda de lotes firmados com os clientes.', textoNovo: 'Nova venda',
    colunas: [
      { titulo: 'Cliente', larga: true },
      { titulo: 'Lote' },
      { titulo: 'Vendedor' },
      { titulo: 'Valor total', numerico: true },
      { titulo: 'Data da venda' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Fernanda Costa Braga', 'Quadra A, Lote 07', 'Diego Martins', 'R$ 198.000,00', '10/06/2026', { selo: { texto: 'Ativo', tom: 'ok' } }],
      ['Antônio Carlos Freitas', 'Quadra D, Lote 03', 'Camila Rodrigues', 'R$ 175.000,00', '22/06/2026', { selo: { texto: 'Ativo', tom: 'ok' } }],
      ['José Adilson Barros', 'Quadra B, Lote 09', 'Beatriz Farias', 'R$ 190.000,00', '01/07/2026', { selo: { texto: 'Ativo', tom: 'ok' } }],
      ['Cláudia Regina Vieira', 'Quadra C, Lote 15', 'Diego Martins', 'R$ 210.000,00', '08/07/2026', { selo: { texto: 'Pendente de assinatura', tom: 'atencao' } }],
      ['Wellington Souza Dias', 'Quadra A, Lote 25', 'Camila Rodrigues', 'R$ 168.900,00', '15/07/2026', { selo: { texto: 'Cancelado', tom: 'vencido' } }],
    ],
  },
  '/comercial/cancelamento': {
    titulo: 'Cancelamentos', descricao: 'Solicitações de cancelamento de reservas e vendas.', textoNovo: 'Novo cancelamento',
    colunas: [
      { titulo: 'Cliente', larga: true },
      { titulo: 'Lote' },
      { titulo: 'Motivo', larga: true },
      { titulo: 'Solicitado em' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Rosana Aparecida Melo', 'Quadra A, Lote 19', 'Desistência por mudança de cidade', '12/07/2026', { selo: { texto: 'Aprovado', tom: 'ok' } }],
      ['Marcos Vinícius Almeida', 'Quadra B, Lote 14', 'Inadimplência prolongada', '14/07/2026', { selo: { texto: 'Em análise', tom: 'atencao' } }],
      ['Mariana Duarte Costa', 'Quadra D, Lote 03', 'Desistência por questões financeiras', '16/07/2026', { selo: { texto: 'Aprovado', tom: 'ok' } }],
      ['Ricardo Souza Lima', 'Quadra C, Lote 22', 'Erro no cadastro da proposta', '18/07/2026', { selo: { texto: 'Recusado', tom: 'vencido' } }],
      ['Juliana Pereira Nunes', 'Quadra A, Lote 07', 'Troca por outro lote', '20/07/2026', { selo: { texto: 'Em análise', tom: 'atencao' } }],
    ],
  },
  '/comercial/distrato': {
    titulo: 'Distratos', descricao: 'Contratos de venda distratados formalmente.', textoNovo: 'Novo distrato',
    colunas: [
      { titulo: 'Cliente', larga: true },
      { titulo: 'Lote' },
      { titulo: 'Valor devolvido', numerico: true },
      { titulo: 'Data do distrato' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Gustavo Henrique Reis', 'Quadra A, Lote 19', 'R$ 32.500,00', '05/06/2026', { selo: { texto: 'Concluído', tom: 'ok' } }],
      ['Larissa Andrade Melo', 'Quadra D, Lote 03', 'R$ 18.900,00', '18/06/2026', { selo: { texto: 'Concluído', tom: 'ok' } }],
      ['Eduardo Nogueira Sá', 'Quadra C, Lote 22', 'R$ 45.200,00', '02/07/2026', { selo: { texto: 'Em processamento', tom: 'atencao' } }],
      ['Vanessa Lopes Torres', 'Quadra A, Lote 07', 'R$ 27.000,00', '10/07/2026', { selo: { texto: 'Em processamento', tom: 'atencao' } }],
      ['Paulo Roberto Guedes', 'Quadra B, Lote 14', 'R$ 0,00', '16/07/2026', { selo: { texto: 'Negado', tom: 'critico' } }],
    ],
  },
  '/comercial/comissao': {
    titulo: 'Comissões', descricao: 'Comissões de vendas apuradas para os vendedores.', textoNovo: 'Nova comissão',
    colunas: [
      { titulo: 'Vendedor', larga: true },
      { titulo: 'Venda referente', larga: true },
      { titulo: 'Percentual', numerico: true },
      { titulo: 'Valor', numerico: true },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Diego Martins', 'Fernanda Costa Braga - Lote 07', 5, 'R$ 9.900,00', { selo: { texto: 'Pago', tom: 'ok' } }],
      ['Camila Rodrigues', 'Antônio Carlos Freitas - Lote 03', 5, 'R$ 8.750,00', { selo: { texto: 'Pago', tom: 'ok' } }],
      ['Beatriz Farias', 'José Adilson Barros - Lote 09', 4, 'R$ 7.600,00', { selo: { texto: 'A pagar', tom: 'atencao' } }],
      ['Diego Martins', 'Cláudia Regina Vieira - Lote 15', 5, 'R$ 10.500,00', { selo: { texto: 'A pagar', tom: 'atencao' } }],
      ['Camila Rodrigues', 'Wellington Souza Dias - Lote 25', 4, 'R$ 0,00', { selo: { texto: 'Estornada', tom: 'vencido' } }],
    ],
  },
  '/comercial/ranking': {
    titulo: 'Ranking de vendedores', descricao: 'Desempenho comparado dos vendedores no período.', textoNovo: 'Nova apuração',
    colunas: [
      { titulo: 'Vendedor', larga: true },
      { titulo: 'Vendas no mês', numerico: true },
      { titulo: 'Volume vendido', numerico: true },
      { titulo: 'Meta', numerico: true },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Diego Martins', 9, 'R$ 1.485.000,00', 'R$ 1.200.000,00', { selo: { texto: 'Meta batida', tom: 'ok' } }],
      ['Camila Rodrigues', 7, 'R$ 1.190.000,00', 'R$ 1.200.000,00', { selo: { texto: 'Próximo da meta', tom: 'atencao' } }],
      ['Beatriz Farias', 5, 'R$ 780.000,00', 'R$ 1.000.000,00', { selo: { texto: 'Abaixo da meta', tom: 'vencido' } }],
      ['Rafael Souto Lima', 3, 'R$ 420.000,00', 'R$ 900.000,00', { selo: { texto: 'Abaixo da meta', tom: 'vencido' } }],
      ['Camila Rodrigues', 7, 'R$ 1.190.000,00', 'R$ 1.200.000,00', { selo: { texto: 'Próximo da meta', tom: 'atencao' } }],
    ],
  },
  '/comercial/simulacoes': {
    titulo: 'Simulações comerciais', descricao: 'Simulações de condições comerciais para propostas em negociação.', textoNovo: 'Nova simulação',
    colunas: [
      { titulo: 'Cliente', larga: true },
      { titulo: 'Lote' },
      { titulo: 'Entrada', numerico: true },
      { titulo: 'Parcelas', numerico: true },
      { titulo: 'Valor da parcela', numerico: true },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Paulo Roberto Guedes', 'Quadra B, Lote 14', 'R$ 16.500,00', 120, 'R$ 1.540,00', { selo: { texto: 'Aprovada', tom: 'ok' } }],
      ['Vanessa Lopes Torres', 'Quadra A, Lote 07', 'R$ 19.800,00', 96, 'R$ 1.980,00', { selo: { texto: 'Em análise', tom: 'atencao' } }],
      ['Eduardo Nogueira Sá', 'Quadra C, Lote 22', 'R$ 22.050,00', 144, 'R$ 1.720,00', { selo: { texto: 'Aprovada', tom: 'ok' } }],
      ['Larissa Andrade Melo', 'Quadra D, Lote 03', 'R$ 15.230,00', 84, 'R$ 2.340,00', { selo: { texto: 'Recusada', tom: 'vencido' } }],
      ['Gustavo Henrique Reis', 'Quadra A, Lote 19', 'R$ 17.500,00', 120, 'R$ 1.620,00', { selo: { texto: 'Em análise', tom: 'atencao' } }],
    ],
  },
};

export default telas;
