import type { ConfigDeListagem } from '@/componentes/comuns/PaginaDeListagem';

const telas: Record<string, ConfigDeListagem> = {
  '/financeiro/contas-a-receber': {
    titulo: 'Contas a receber',
    descricao: 'Títulos e parcelas a receber dos compradores de lotes.',
    textoNovo: 'Conta a receber',
    colunas: [
      { titulo: 'Cliente', larga: true },
      { titulo: 'Empreendimento', larga: true },
      { titulo: 'Vencimento' },
      { titulo: 'Valor', numerico: true },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Maria de Fátima Souza', 'Loteamento Bela Vista', '05/07/2025', 'R$ 1.250,00', { selo: { texto: 'Vencida', tom: 'vencido' } }],
      ['João Carlos Ferreira', 'Residencial Monte Cristo', '10/08/2025', 'R$ 980,50', { selo: { texto: 'A vencer', tom: 'neutro' } }],
      ['Empresa Norte Construções Ltda', 'Loteamento Águas Claras', '15/06/2025', 'R$ 3.400,00', { selo: { texto: 'Paga', tom: 'ok' } }],
      ['Ana Paula Lima', 'Residencial Jardim Caracaraí', '20/08/2025', 'R$ 750,00', { selo: { texto: 'Vence hoje', tom: 'atencao' } }],
      ['Roberto Nascimento Melo', 'Loteamento Bela Vista', '30/07/2025', 'R$ 1.100,00', { selo: { texto: 'Renegociada', tom: 'info' } }],
    ],
  },
  '/financeiro/recebimentos': {
    titulo: 'Recebimentos',
    descricao: 'Histórico de valores efetivamente recebidos.',
    textoNovo: 'Recebimento',
    colunas: [
      { titulo: 'Cliente', larga: true },
      { titulo: 'Forma de pagamento' },
      { titulo: 'Data' },
      { titulo: 'Valor recebido', numerico: true },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Carlos Eduardo Batista', 'Pix', '02/07/2025', 'R$ 1.250,00', { selo: { texto: 'Conciliado', tom: 'ok' } }],
      ['Francisca das Chagas Alves', 'Boleto', '04/07/2025', 'R$ 890,00', { selo: { texto: 'Conciliado', tom: 'ok' } }],
      ['Loteadora Rio Branco Empreendimentos', 'Transferência (TED)', '10/07/2025', 'R$ 5.200,00', { selo: { texto: 'Em processamento', tom: 'info' } }],
      ['Sebastião Rodrigues Neto', 'Boleto+Pix', '12/07/2025', 'R$ 610,00', { selo: { texto: 'Pendente de conciliação', tom: 'atencao' } }],
      ['Vanessa Cristina Gomes', 'Pix', '18/07/2025', 'R$ 430,00', { selo: { texto: 'Conciliado', tom: 'ok' } }],
    ],
  },
  '/financeiro/titulos': {
    titulo: 'Títulos',
    descricao: 'Títulos financeiros gerados a partir dos contratos de venda.',
    textoNovo: 'Título',
    colunas: [
      { titulo: 'Número' },
      { titulo: 'Cliente', larga: true },
      { titulo: 'Tipo' },
      { titulo: 'Valor', numerico: true },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['TIT-2025-00812', 'Marcos Antônio Vieira', 'Boleto', 'R$ 1.320,00', { selo: { texto: 'Em aberto', tom: 'neutro' } }],
      ['TIT-2025-00813', 'Josefa Ribeiro dos Santos', 'Pix', 'R$ 750,00', { selo: { texto: 'Quitado', tom: 'ok' } }],
      ['TIT-2025-00814', 'Construtora Amazônia Sul S.A.', 'Boleto+Pix', 'R$ 4.100,00', { selo: { texto: 'Vencido', tom: 'vencido' } }],
      ['TIT-2025-00815', 'Patrícia Almeida Costa', 'Boleto', 'R$ 980,00', { selo: { texto: 'A vencer', tom: 'atencao' } }],
      ['TIT-2025-00816', 'Raimundo Nonato Pereira', 'Pix', 'R$ 1.560,00', { selo: { texto: 'Cancelado', tom: 'neutro' } }],
    ],
  },
  '/financeiro/parcelas': {
    titulo: 'Parcelas',
    descricao: 'Parcelas dos contratos de venda de lotes.',
    textoNovo: 'Parcela',
    colunas: [
      { titulo: 'Contrato' },
      { titulo: 'Cliente', larga: true },
      { titulo: 'Parcela' },
      { titulo: 'Valor', numerico: true },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['CTR-1042', 'Eliane Cristina Souza Lima', '12/48', 'R$ 890,00', { selo: { texto: 'Paga', tom: 'ok' } }],
      ['CTR-1042', 'Eliane Cristina Souza Lima', '13/48', 'R$ 890,00', { selo: { texto: 'A vencer', tom: 'neutro' } }],
      ['CTR-0987', 'Wellington Braga Fernandes', '24/60', 'R$ 1.150,00', { selo: { texto: 'Vencida', tom: 'vencido' } }],
      ['CTR-1101', 'Girlene Maciel Torres', '03/36', 'R$ 620,00', { selo: { texto: 'Vence hoje', tom: 'atencao' } }],
      ['CTR-0765', 'Adenilson Costa Rocha', '40/40', 'R$ 700,00', { selo: { texto: 'Renegociada', tom: 'info' } }],
    ],
  },
  '/financeiro/baixas': {
    titulo: 'Baixas',
    descricao: 'Baixas manuais e automáticas de títulos e parcelas.',
    textoNovo: 'Baixa',
    colunas: [
      { titulo: 'Título' },
      { titulo: 'Cliente', larga: true },
      { titulo: 'Data da baixa' },
      { titulo: 'Valor baixado', numerico: true },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['TIT-2025-00701', 'Gilberto Nery Aguiar', '01/07/2025', 'R$ 1.250,00', { selo: { texto: 'Baixado', tom: 'ok' } }],
      ['TIT-2025-00702', 'Simone Andrade Cardoso', '03/07/2025', 'R$ 940,00', { selo: { texto: 'Baixa automática', tom: 'info' } }],
      ['TIT-2025-00703', 'Nazaré Corrêa Barbosa', '05/07/2025', 'R$ 500,00', { selo: { texto: 'Baixa parcial', tom: 'atencao' } }],
      ['TIT-2025-00704', 'Empreendimentos Boa Vista Ltda', '08/07/2025', 'R$ 3.800,00', { selo: { texto: 'Estornada', tom: 'critico' } }],
      ['TIT-2025-00705', 'Aldenora Pinheiro Sales', '11/07/2025', 'R$ 680,00', { selo: { texto: 'Baixado', tom: 'ok' } }],
    ],
  },
  '/financeiro/renegociacoes': {
    titulo: 'Renegociações',
    descricao: 'Acordos de renegociação de dívidas em atraso.',
    textoNovo: 'Renegociação',
    colunas: [
      { titulo: 'Cliente', larga: true },
      { titulo: 'Contrato' },
      { titulo: 'Data do acordo' },
      { titulo: 'Novo valor total', numerico: true },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Delzuite Farias Monteiro', 'CTR-0842', '02/06/2025', 'R$ 12.400,00', { selo: { texto: 'Ativa', tom: 'ok' } }],
      ['Osmar Tavares Lopes', 'CTR-0759', '15/05/2025', 'R$ 8.900,00', { selo: { texto: 'Em atraso', tom: 'atencao' } }],
      ['Rosangela Ferreira Dias', 'CTR-1023', '20/06/2025', 'R$ 5.600,00', { selo: { texto: 'Quitada', tom: 'info' } }],
      ['Jurandir Alves Bezerra', 'CTR-0611', '28/06/2025', 'R$ 15.200,00', { selo: { texto: 'Descumprida', tom: 'critico' } }],
      ['Cleonice Ramos Teixeira', 'CTR-0933', '05/07/2025', 'R$ 4.350,00', { selo: { texto: 'Ativa', tom: 'ok' } }],
    ],
  },
  '/financeiro/reajustes': {
    titulo: 'Reajustes',
    descricao: 'Reajustes contratuais aplicados por índice de correção.',
    textoNovo: 'Reajuste',
    colunas: [
      { titulo: 'Contrato' },
      { titulo: 'Cliente', larga: true },
      { titulo: 'Índice' },
      { titulo: 'Percentual', numerico: true },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['CTR-0512', 'Iranilde Correia Souza', 'IGP-M', 4.87, { selo: { texto: 'Aplicado', tom: 'ok' } }],
      ['CTR-0688', 'Erivaldo Pantoja Reis', 'INCC', 3.2, { selo: { texto: 'Agendado', tom: 'info' } }],
      ['CTR-0741', 'Marlene Cardoso Freitas', 'IPCA', 2.45, { selo: { texto: 'Pendente', tom: 'atencao' } }],
      ['CTR-0399', 'Genivaldo Souza Lima', 'IGP-M', 5.1, { selo: { texto: 'Cancelado', tom: 'neutro' } }],
      ['CTR-0850', 'Damiana Ribeiro Xavier', 'INCC', 3.75, { selo: { texto: 'Aplicado', tom: 'ok' } }],
    ],
  },
  '/financeiro/inadimplencia': {
    titulo: 'Controle de inadimplência',
    descricao: 'Clientes com parcelas em atraso e situação de cobrança.',
    textoNovo: 'Ocorrência',
    colunas: [
      { titulo: 'Cliente', larga: true },
      { titulo: 'Contrato' },
      { titulo: 'Dias em atraso', numerico: true },
      { titulo: 'Valor em aberto', numerico: true },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Adailton Souza Farias', 'CTR-0654', 92, 'R$ 3.560,00', { selo: { texto: 'Inadimplente', tom: 'vencido' } }],
      ['Neuza Batista Coelho', 'CTR-0721', 15, 'R$ 890,00', { selo: { texto: 'Em atraso', tom: 'atencao' } }],
      ['Wilker Nunes Cavalcante', 'CTR-0489', 210, 'R$ 9.800,00', { selo: { texto: 'Sujeito a retomada', tom: 'critico' } }],
      ['Ivonete Barros da Silva', 'CTR-0902', 5, 'R$ 450,00', { selo: { texto: 'Em atraso', tom: 'atencao' } }],
      ['Expedito Carvalho Nunes', 'CTR-0367', 305, 'R$ 14.200,00', { selo: { texto: 'Em cobrança judicial', tom: 'critico' } }],
    ],
  },
  '/financeiro/cobranca-escritural': {
    titulo: 'Cobrança escritural',
    descricao: 'Cobranças enviadas via débito em conta e convênios bancários.',
    textoNovo: 'Cobrança',
    colunas: [
      { titulo: 'Cliente', larga: true },
      { titulo: 'Banco' },
      { titulo: 'Data de envio' },
      { titulo: 'Valor', numerico: true },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Domingas Pereira Aguiar', 'Banco do Brasil', '01/07/2025', 'R$ 780,00', { selo: { texto: 'Enviada', tom: 'ok' } }],
      ['Almir José Cardoso', 'Bradesco', '02/07/2025', 'R$ 1.100,00', { selo: { texto: 'Falha no envio', tom: 'vencido' } }],
      ['Loteadora Serra Norte Ltda', 'Itaú Unibanco', '03/07/2025', 'R$ 6.200,00', { selo: { texto: 'Programada', tom: 'info' } }],
      ['Terezinha Gonçalves Reis', 'Caixa Econômica Federal', '04/07/2025', 'R$ 540,00', { selo: { texto: 'Pendente', tom: 'atencao' } }],
      ['Osvaldo Miranda Castro', 'Banco do Brasil', '05/07/2025', 'R$ 920,00', { selo: { texto: 'Ignorada', tom: 'neutro' } }],
    ],
  },
  '/financeiro/fluxo-previsto': {
    titulo: 'Fluxo previsto',
    descricao: 'Projeção de entradas e saídas financeiras futuras.',
    textoNovo: 'Lançamento previsto',
    colunas: [
      { titulo: 'Descrição', larga: true },
      { titulo: 'Categoria' },
      { titulo: 'Data prevista' },
      { titulo: 'Valor', numerico: true },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Recebimento de parcelas — Loteamento Bela Vista', 'Entrada', '01/08/2025', 'R$ 42.500,00', { selo: { texto: 'Confirmado', tom: 'ok' } }],
      ['Pagamento de fornecedores de terraplanagem', 'Saída', '05/08/2025', 'R$ 18.900,00', { selo: { texto: 'Agendado', tom: 'info' } }],
      ['Recebimento de renegociações', 'Entrada', '10/08/2025', 'R$ 6.300,00', { selo: { texto: 'Sujeito a atraso', tom: 'atencao' } }],
      ['Folha de pagamento', 'Saída', '05/08/2025', 'R$ 27.400,00', { selo: { texto: 'Confirmado', tom: 'ok' } }],
      ['Impostos sobre vendas', 'Saída', '20/08/2025', 'R$ 9.150,00', { selo: { texto: 'Agendado', tom: 'info' } }],
    ],
  },
  '/financeiro/contas-a-pagar': {
    titulo: 'Contas a pagar',
    descricao: 'Obrigações financeiras da loteadora com fornecedores e prestadores.',
    textoNovo: 'Conta a pagar',
    colunas: [
      { titulo: 'Fornecedor', larga: true },
      { titulo: 'Categoria' },
      { titulo: 'Vencimento' },
      { titulo: 'Valor', numerico: true },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Terraplanagem Roraima Ltda', 'Obras', '03/07/2025', 'R$ 22.000,00', { selo: { texto: 'Vencida', tom: 'vencido' } }],
      ['Cartório de Registro de Imóveis de Boa Vista', 'Cartório', '08/07/2025', 'R$ 3.400,00', { selo: { texto: 'A vencer', tom: 'atencao' } }],
      ['Escritório de Advocacia Farias & Melo', 'Jurídico', '15/07/2025', 'R$ 5.800,00', { selo: { texto: 'Paga', tom: 'ok' } }],
      ['Energisa Roraima Distribuidora', 'Utilidades', '20/07/2025', 'R$ 1.250,00', { selo: { texto: 'A vencer', tom: 'atencao' } }],
      ['Topografia Norte Serviços Ltda', 'Serviços técnicos', '25/07/2025', 'R$ 7.600,00', { selo: { texto: 'Em processamento', tom: 'info' } }],
    ],
  },
  '/financeiro/fornecedores': {
    titulo: 'Fornecedores',
    descricao: 'Cadastro de fornecedores e prestadores de serviço.',
    textoNovo: 'Fornecedor',
    colunas: [
      { titulo: 'Razão social', larga: true },
      { titulo: 'CNPJ' },
      { titulo: 'Cidade' },
      { titulo: 'Categoria' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Terraplanagem Roraima Ltda', '04.512.789/0001-33', 'Boa Vista', 'Obras', { selo: { texto: 'Ativo', tom: 'ok' } }],
      ['Topografia Norte Serviços Ltda', '11.278.940/0001-05', 'Boa Vista', 'Serviços técnicos', { selo: { texto: 'Ativo', tom: 'ok' } }],
      ['Escritório de Advocacia Farias & Melo', '22.671.303/0001-88', 'Manaus', 'Jurídico', { selo: { texto: 'Ativo', tom: 'ok' } }],
      ['Concreto Forte Materiais de Construção', '09.845.120/0001-47', 'Rorainópolis', 'Materiais', { selo: { texto: 'Bloqueado', tom: 'critico' } }],
      ['Sinalização Vias Norte ME', '15.309.662/0001-19', 'Pacaraima', 'Infraestrutura', { selo: { texto: 'Inativo', tom: 'neutro' } }],
    ],
  },
  '/financeiro/pagamentos': {
    titulo: 'Pagamentos',
    descricao: 'Pagamentos efetuados a fornecedores e prestadores.',
    textoNovo: 'Pagamento',
    colunas: [
      { titulo: 'Fornecedor', larga: true },
      { titulo: 'Forma de pagamento' },
      { titulo: 'Data' },
      { titulo: 'Valor pago', numerico: true },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Terraplanagem Roraima Ltda', 'Transferência (TED)', '03/07/2025', 'R$ 22.000,00', { selo: { texto: 'Efetuado', tom: 'ok' } }],
      ['Cartório de Registro de Imóveis de Boa Vista', 'Boleto', '08/07/2025', 'R$ 3.400,00', { selo: { texto: 'Agendado', tom: 'info' } }],
      ['Concreto Forte Materiais de Construção', 'Pix', '11/07/2025', 'R$ 6.750,00', { selo: { texto: 'Cancelado', tom: 'neutro' } }],
      ['Energisa Roraima Distribuidora', 'Débito automático', '20/07/2025', 'R$ 1.250,00', { selo: { texto: 'Pendente', tom: 'atencao' } }],
      ['Sinalização Vias Norte ME', 'Transferência (TED)', '22/07/2025', 'R$ 4.100,00', { selo: { texto: 'Efetuado', tom: 'ok' } }],
    ],
  },
  '/financeiro/agenda': {
    titulo: 'Agenda financeira',
    descricao: 'Compromissos e vencimentos programados no financeiro.',
    textoNovo: 'Compromisso',
    colunas: [
      { titulo: 'Descrição', larga: true },
      { titulo: 'Responsável' },
      { titulo: 'Data' },
      { titulo: 'Valor', numerico: true },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Pagamento de fornecedores de obras', 'Adriano Melo Souza', '01/08/2025', 'R$ 22.000,00', { selo: { texto: 'Agendado', tom: 'info' } }],
      ['Fechamento mensal do caixa', 'Luciana Ferreira Reis', '31/07/2025', 'R$ 0,00', { selo: { texto: 'Pendente', tom: 'atencao' } }],
      ['Envio de boletos do mês', 'Kelly Cristina Nogueira', '05/08/2025', 'R$ 0,00', { selo: { texto: 'Programado', tom: 'info' } }],
      ['Renovação de acordo com fornecedor', 'Adriano Melo Souza', '10/08/2025', 'R$ 0,00', { selo: { texto: 'Concluído', tom: 'ok' } }],
      ['Auditoria de conciliação bancária', 'Luciana Ferreira Reis', '15/08/2025', 'R$ 0,00', { selo: { texto: 'Cancelado', tom: 'neutro' } }],
    ],
  },
  '/financeiro/programacoes': {
    titulo: 'Programações',
    descricao: 'Programações de pagamentos e recebimentos futuros.',
    textoNovo: 'Programação',
    colunas: [
      { titulo: 'Descrição', larga: true },
      { titulo: 'Tipo' },
      { titulo: 'Data' },
      { titulo: 'Valor', numerico: true },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Pagamento de folha — julho/2025', 'Saída', '05/08/2025', 'R$ 27.400,00', { selo: { texto: 'Programada', tom: 'info' } }],
      ['Recebimento de parcelas em lote', 'Entrada', '10/08/2025', 'R$ 38.900,00', { selo: { texto: 'Programada', tom: 'info' } }],
      ['Pagamento de impostos federais', 'Saída', '20/08/2025', 'R$ 9.150,00', { selo: { texto: 'Pendente', tom: 'atencao' } }],
      ['Repasse a incorporadora parceira', 'Saída', '25/08/2025', 'R$ 14.700,00', { selo: { texto: 'Cancelada', tom: 'neutro' } }],
      ['Recebimento de sinal de novas vendas', 'Entrada', '28/08/2025', 'R$ 21.300,00', { selo: { texto: 'Confirmada', tom: 'ok' } }],
    ],
  },
  '/financeiro/caixa-diario': {
    titulo: 'Caixa diário',
    descricao: 'Movimentações do caixa registradas no dia a dia.',
    textoNovo: 'Lançamento',
    colunas: [
      { titulo: 'Descrição', larga: true },
      { titulo: 'Operador' },
      { titulo: 'Data' },
      { titulo: 'Valor', numerico: true },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Recebimento em dinheiro — plantão de vendas', 'Fabiana Souza Lima', '28/07/2025', 'R$ 850,00', { selo: { texto: 'Conciliado', tom: 'ok' } }],
      ['Pagamento de despesa de cartório', 'Fabiana Souza Lima', '28/07/2025', 'R$ 320,00', { selo: { texto: 'Conciliado', tom: 'ok' } }],
      ['Recebimento em dinheiro — cliente balcão', 'Renato Almeida Costa', '29/07/2025', 'R$ 400,00', { selo: { texto: 'Pendente', tom: 'atencao' } }],
      ['Vale para deslocamento de equipe', 'Renato Almeida Costa', '29/07/2025', 'R$ 150,00', { selo: { texto: 'Pendente', tom: 'atencao' } }],
      ['Sangria para depósito bancário', 'Fabiana Souza Lima', '29/07/2025', 'R$ 1.000,00', { selo: { texto: 'Conciliado', tom: 'ok' } }],
    ],
  },
  '/financeiro/movimentacoes': {
    titulo: 'Movimentações',
    descricao: 'Extrato consolidado de todas as movimentações financeiras.',
    textoNovo: 'Movimentação',
    colunas: [
      { titulo: 'Descrição', larga: true },
      { titulo: 'Conta' },
      { titulo: 'Data' },
      { titulo: 'Valor', numerico: true },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Recebimento de parcela — CTR-1042', 'Banco do Brasil CC', '02/07/2025', 'R$ 890,00', { selo: { texto: 'Conciliada', tom: 'ok' } }],
      ['Pagamento a fornecedor de obras', 'Itaú Unibanco CC', '03/07/2025', 'R$ 22.000,00', { selo: { texto: 'Conciliada', tom: 'ok' } }],
      ['Transferência entre contas', 'Bradesco CC', '05/07/2025', 'R$ 5.000,00', { selo: { texto: 'Em processamento', tom: 'info' } }],
      ['Tarifa bancária mensal', 'Banco do Brasil CC', '10/07/2025', 'R$ 45,90', { selo: { texto: 'Pendente', tom: 'atencao' } }],
      ['Estorno de pagamento duplicado', 'Itaú Unibanco CC', '12/07/2025', 'R$ 610,00', { selo: { texto: 'Cancelada', tom: 'neutro' } }],
    ],
  },
  '/financeiro/sangrias': {
    titulo: 'Sangrias',
    descricao: 'Retiradas de numerário do caixa para depósito ou custódia.',
    textoNovo: 'Sangria',
    colunas: [
      { titulo: 'Caixa de origem', larga: true },
      { titulo: 'Operador' },
      { titulo: 'Data' },
      { titulo: 'Valor', numerico: true },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Caixa — Stand de vendas Bela Vista', 'Fabiana Souza Lima', '28/07/2025', 'R$ 1.000,00', { selo: { texto: 'Depositada', tom: 'ok' } }],
      ['Caixa — Sede administrativa', 'Renato Almeida Costa', '28/07/2025', 'R$ 2.500,00', { selo: { texto: 'Depositada', tom: 'ok' } }],
      ['Caixa — Stand de vendas Jardim Caracaraí', 'Wesley Andrade Souza', '29/07/2025', 'R$ 800,00', { selo: { texto: 'Pendente', tom: 'atencao' } }],
      ['Caixa — Sede administrativa', 'Renato Almeida Costa', '29/07/2025', 'R$ 1.750,00', { selo: { texto: 'Em trânsito', tom: 'info' } }],
      ['Caixa — Stand de vendas Bela Vista', 'Fabiana Souza Lima', '29/07/2025', 'R$ 620,00', { selo: { texto: 'Cancelada', tom: 'neutro' } }],
    ],
  },
  '/financeiro/fechamento': {
    titulo: 'Fechamento de caixa',
    descricao: 'Fechamentos diários e mensais do caixa por unidade.',
    textoNovo: 'Fechamento',
    colunas: [
      { titulo: 'Unidade', larga: true },
      { titulo: 'Responsável' },
      { titulo: 'Data' },
      { titulo: 'Saldo apurado', numerico: true },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Stand de vendas Bela Vista', 'Fabiana Souza Lima', '28/07/2025', 'R$ 3.420,00', { selo: { texto: 'Conciliado', tom: 'ok' } }],
      ['Sede administrativa', 'Renato Almeida Costa', '28/07/2025', 'R$ 8.900,00', { selo: { texto: 'Conciliado', tom: 'ok' } }],
      ['Stand de vendas Jardim Caracaraí', 'Wesley Andrade Souza', '29/07/2025', 'R$ 1.150,00', { selo: { texto: 'Divergência', tom: 'critico' } }],
      ['Sede administrativa', 'Renato Almeida Costa', '29/07/2025', 'R$ 6.200,00', { selo: { texto: 'Aguardando conferência', tom: 'atencao' } }],
      ['Stand de vendas Bela Vista', 'Fabiana Souza Lima', '29/07/2025', 'R$ 2.780,00', { selo: { texto: 'Rascunho', tom: 'neutro' } }],
    ],
  },
  '/financeiro/conciliacao': {
    titulo: 'Conciliação bancária',
    descricao: 'Conciliação entre lançamentos internos e extratos bancários.',
    textoNovo: 'Conciliação',
    colunas: [
      { titulo: 'Banco' },
      { titulo: 'Descrição', larga: true },
      { titulo: 'Data' },
      { titulo: 'Valor', numerico: true },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Banco do Brasil', 'Recebimento Pix — Maria de Fátima Souza', '02/07/2025', 'R$ 1.250,00', { selo: { texto: 'Conciliado', tom: 'ok' } }],
      ['Itaú Unibanco', 'Pagamento — Terraplanagem Roraima Ltda', '03/07/2025', 'R$ 22.000,00', { selo: { texto: 'Conciliado', tom: 'ok' } }],
      ['Bradesco', 'Transferência entre contas', '05/07/2025', 'R$ 5.000,00', { selo: { texto: 'Divergente', tom: 'critico' } }],
      ['Caixa Econômica Federal', 'Boleto compensado — TIT-2025-00701', '06/07/2025', 'R$ 890,00', { selo: { texto: 'Pendente', tom: 'atencao' } }],
      ['Banco do Brasil', 'Tarifa bancária mensal', '10/07/2025', 'R$ 45,90', { selo: { texto: 'Não identificado', tom: 'neutro' } }],
    ],
  },
  '/financeiro/extratos': {
    titulo: 'Extratos',
    descricao: 'Extratos bancários importados para conciliação.',
    textoNovo: 'Importar extrato',
    colunas: [
      { titulo: 'Banco' },
      { titulo: 'Conta' },
      { titulo: 'Período' },
      { titulo: 'Saldo final', numerico: true },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Banco do Brasil', 'CC 21.345-6', '01/07/2025 a 31/07/2025', 'R$ 48.900,00', { selo: { texto: 'Importado', tom: 'ok' } }],
      ['Itaú Unibanco', 'CC 55.209-1', '01/07/2025 a 31/07/2025', 'R$ 12.340,00', { selo: { texto: 'Importado', tom: 'ok' } }],
      ['Bradesco', 'CC 08.771-4', '01/07/2025 a 31/07/2025', 'R$ 6.780,00', { selo: { texto: 'Processando', tom: 'info' } }],
      ['Caixa Econômica Federal', 'CC 33.998-2', '01/06/2025 a 30/06/2025', 'R$ 21.500,00', { selo: { texto: 'Com divergências', tom: 'critico' } }],
      ['Banco do Brasil', 'CC 21.345-6', '01/06/2025 a 30/06/2025', 'R$ 39.200,00', { selo: { texto: 'Importado', tom: 'ok' } }],
    ],
  },
  '/financeiro/transferencias': {
    titulo: 'Transferências',
    descricao: 'Transferências entre contas bancárias da empresa.',
    textoNovo: 'Transferência',
    colunas: [
      { titulo: 'Conta de origem', larga: true },
      { titulo: 'Conta de destino', larga: true },
      { titulo: 'Data' },
      { titulo: 'Valor', numerico: true },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Banco do Brasil CC 21.345-6', 'Itaú Unibanco CC 55.209-1', '03/07/2025', 'R$ 10.000,00', { selo: { texto: 'Concluída', tom: 'ok' } }],
      ['Itaú Unibanco CC 55.209-1', 'Bradesco CC 08.771-4', '08/07/2025', 'R$ 3.500,00', { selo: { texto: 'Em processamento', tom: 'info' } }],
      ['Caixa Econômica Federal CC 33.998-2', 'Banco do Brasil CC 21.345-6', '12/07/2025', 'R$ 7.200,00', { selo: { texto: 'Pendente', tom: 'atencao' } }],
      ['Banco do Brasil CC 21.345-6', 'Caixa Econômica Federal CC 33.998-2', '18/07/2025', 'R$ 1.900,00', { selo: { texto: 'Cancelada', tom: 'neutro' } }],
      ['Bradesco CC 08.771-4', 'Itaú Unibanco CC 55.209-1', '22/07/2025', 'R$ 4.750,00', { selo: { texto: 'Rejeitada', tom: 'critico' } }],
    ],
  },
};

export default telas;
