import type { ConfigDeListagem } from '@/componentes/comuns/PaginaDeListagem';

const telas: Record<string, ConfigDeListagem> = {
  '/integracoes/asaas': {
    titulo: 'Integração Asaas',
    descricao: 'Eventos e cobranças sincronizados com o gateway Asaas.',
    textoNovo: 'Nova cobrança',
    colunas: [
      { titulo: 'Evento', larga: true },
      { titulo: 'Referência' },
      { titulo: 'Valor', numerico: true },
      { titulo: 'Data/hora' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Boleto gerado', 'COB-84512', 'R$ 890,00', '28/07/2025 09:12', { selo: { texto: 'Sincronizado', tom: 'ok' } }],
      ['PIX confirmado', 'COB-84509', 'R$ 1.240,50', '28/07/2025 08:47', { selo: { texto: 'Sincronizado', tom: 'ok' } }],
      ['Webhook recebido', 'COB-84498', 'R$ 560,00', '27/07/2025 17:30', { selo: { texto: 'Sincronizado', tom: 'ok' } }],
      ['Cobrança vencida', 'COB-84400', 'R$ 720,00', '25/07/2025 00:00', { selo: { texto: 'Erro no envio', tom: 'vencido' } }],
      ['Chave de API renovada', '—', 0, '20/07/2025 14:05', { selo: { texto: 'Token expirando', tom: 'atencao' } }],
    ],
  },
  '/integracoes/inter': {
    titulo: 'Integração Banco Inter',
    descricao: 'Conta conectada ao Banco Inter para emissão de boletos e Pix.',
    textoNovo: 'Nova conexão',
    colunas: [
      { titulo: 'Conta', larga: true },
      { titulo: 'Agência' },
      { titulo: 'Certificado' },
      { titulo: 'Última sincronização' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Conta corrente 0001', '0001', 'cert-inter-2025.pfx', '29/07/2025 07:15', { selo: { texto: 'Conectado', tom: 'ok' } }],
      ['Conta cobrança 0002', '0001', 'cert-inter-2025.pfx', '28/07/2025 22:40', { selo: { texto: 'Conectado', tom: 'ok' } }],
      ['Conta arrecadação 0003', '0002', 'cert-inter-2024.pfx', '15/06/2025 10:00', { selo: { texto: 'Certificado vencendo', tom: 'atencao' } }],
      ['Conta reserva 0004', '0002', 'cert-inter-teste.pfx', '10/07/2025 09:30', { selo: { texto: 'Em teste', tom: 'info' } }],
      ['Conta legada 0005', '0003', 'cert-inter-2022.pfx', '02/03/2025 08:00', { selo: { texto: 'Desconectado', tom: 'vencido' } }],
    ],
  },
  '/integracoes/sicredi': {
    titulo: 'Integração Sicredi',
    descricao: 'Convênios de cobrança conectados à cooperativa Sicredi.',
    textoNovo: 'Novo convênio',
    colunas: [
      { titulo: 'Convênio', larga: true },
      { titulo: 'Posto' },
      { titulo: 'Carteira' },
      { titulo: 'Última sincronização' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Convênio 123456', '0921', '1', '29/07/2025 06:50', { selo: { texto: 'Conectado', tom: 'ok' } }],
      ['Convênio 654321', '0921', '3', '28/07/2025 20:10', { selo: { texto: 'Conectado', tom: 'ok' } }],
      ['Convênio 789012', '0455', '1', '01/07/2025 11:20', { selo: { texto: 'Pendente de homologação', tom: 'atencao' } }],
      ['Convênio 345678', '0455', '2', '18/06/2025 09:00', { selo: { texto: 'Não configurado', tom: 'neutro' } }],
      ['Convênio 901234', '0921', '1', '05/05/2025 13:45', { selo: { texto: 'Desconectado', tom: 'vencido' } }],
    ],
  },
  '/integracoes/cora': {
    titulo: 'Integração Cora',
    descricao: 'Conta digital Cora conectada para emissão de boletos e Pix.',
    textoNovo: 'Nova conexão',
    colunas: [
      { titulo: 'Conta', larga: true },
      { titulo: 'Ambiente' },
      { titulo: 'Chave de API' },
      { titulo: 'Última sincronização' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Conta principal', 'Produção', 'cora_live_2f8a', '29/07/2025 07:40', { selo: { texto: 'Conectado', tom: 'ok' } }],
      ['Conta cobrança recorrente', 'Produção', 'cora_live_9c1d', '29/07/2025 06:55', { selo: { texto: 'Conectado', tom: 'ok' } }],
      ['Conta homologação', 'Sandbox', 'cora_test_44ab', '22/07/2025 15:20', { selo: { texto: 'Em teste', tom: 'info' } }],
      ['Conta filial Goiânia', 'Produção', 'cora_live_77fe', '30/04/2025 08:10', { selo: { texto: 'Token expirando', tom: 'atencao' } }],
      ['Conta descontinuada', 'Produção', 'cora_live_00aa', '12/01/2025 09:00', { selo: { texto: 'Desconectado', tom: 'vencido' } }],
    ],
  },
  '/integracoes/sicoob': {
    titulo: 'Integração Sicoob',
    descricao: 'Convênios Sicoob conectados para cobrança bancária.',
    textoNovo: 'Novo convênio',
    colunas: [
      { titulo: 'Convênio', larga: true },
      { titulo: 'Cooperativa' },
      { titulo: 'Carteira' },
      { titulo: 'Última sincronização' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Convênio 3021455', '4327', '1', '29/07/2025 07:05', { selo: { texto: 'Conectado', tom: 'ok' } }],
      ['Convênio 3021988', '4327', '9', '28/07/2025 19:15', { selo: { texto: 'Conectado', tom: 'ok' } }],
      ['Convênio 3055120', '2678', '1', '19/07/2025 10:40', { selo: { texto: 'Certificado vencendo', tom: 'atencao' } }],
      ['Convênio 3099441', '2678', '1', '01/07/2025 08:00', { selo: { texto: 'Não configurado', tom: 'neutro' } }],
      ['Convênio 3012009', '4327', '3', '11/03/2025 09:30', { selo: { texto: 'Erro na comunicação', tom: 'critico' } }],
    ],
  },
  '/integracoes/whatsapp': {
    titulo: 'WhatsApp Cloud API',
    descricao: 'Mensagens enviadas via WhatsApp Cloud API para clientes e corretores.',
    textoNovo: 'Nova mensagem',
    colunas: [
      { titulo: 'Destinatário', larga: true },
      { titulo: 'Modelo' },
      { titulo: 'Canal' },
      { titulo: 'Enviado em' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Marcos Antônio Ferreira', 'Lembrete de vencimento', '+55 95 99123-4567', '29/07/2025 08:00', { selo: { texto: 'Entregue', tom: 'ok' } }],
      ['Juliana Beatriz Souza', 'Boleto disponível', '+55 95 99876-5432', '28/07/2025 18:30', { selo: { texto: 'Entregue', tom: 'ok' } }],
      ['Carlos Eduardo Nascimento', 'Confirmação de Pix', '+55 63 99234-1122', '28/07/2025 15:12', { selo: { texto: 'Enviado', tom: 'info' } }],
      ['Fernanda Lima Rocha', 'Cobrança em atraso', '+55 62 99345-8890', '26/07/2025 09:45', { selo: { texto: 'Não entregue', tom: 'vencido' } }],
      ['Número de teste', 'Template em revisão', '+55 95 99000-0000', '20/07/2025 10:00', { selo: { texto: 'Em teste', tom: 'info' } }],
    ],
  },
  '/integracoes/twilio': {
    titulo: 'Twilio',
    descricao: 'SMS e chamadas de voz disparados via Twilio.',
    textoNovo: 'Novo envio',
    colunas: [
      { titulo: 'Destinatário', larga: true },
      { titulo: 'Tipo' },
      { titulo: 'Custo', numerico: true },
      { titulo: 'Enviado em' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Ricardo Alves Pereira', 'SMS', 'R$ 0,18', '29/07/2025 07:50', { selo: { texto: 'Entregue', tom: 'ok' } }],
      ['Ana Paula Martins', 'SMS', 'R$ 0,18', '28/07/2025 16:20', { selo: { texto: 'Entregue', tom: 'ok' } }],
      ['Bruno Henrique Costa', 'Chamada de voz', 'R$ 0,45', '27/07/2025 11:10', { selo: { texto: 'Enviado', tom: 'info' } }],
      ['Diego Fernandes Lopes', 'SMS', 'R$ 0,18', '24/07/2025 09:00', { selo: { texto: 'Falha no envio', tom: 'vencido' } }],
      ['Conta sandbox Twilio', '—', 0, '15/07/2025 08:00', { selo: { texto: 'Não configurado', tom: 'neutro' } }],
    ],
  },
  '/integracoes/zenvia': {
    titulo: 'Zenvia',
    descricao: 'Notificações multicanal disparadas via plataforma Zenvia.',
    textoNovo: 'Novo envio',
    colunas: [
      { titulo: 'Destinatário', larga: true },
      { titulo: 'Canal' },
      { titulo: 'Modelo' },
      { titulo: 'Enviado em' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Eliane Souza Pinto', 'SMS', 'Lembrete de parcela', '29/07/2025 07:30', { selo: { texto: 'Entregue', tom: 'ok' } }],
      ['Camila Rodrigues Dias', 'WhatsApp', 'Confirmação de cadastro', '28/07/2025 14:00', { selo: { texto: 'Entregue', tom: 'ok' } }],
      ['Marcos Antônio Ferreira', 'E-mail', 'Segunda via de boleto', '27/07/2025 10:20', { selo: { texto: 'Enviado', tom: 'info' } }],
      ['Juliana Beatriz Souza', 'SMS', 'Aviso de atraso', '22/07/2025 09:15', { selo: { texto: 'Não entregue', tom: 'vencido' } }],
      ['Chave de API Zenvia', '—', 'Renovação de token', '05/07/2025 08:00', { selo: { texto: 'Token expirando', tom: 'atencao' } }],
    ],
  },
  '/integracoes/resend': {
    titulo: 'Resend (e-mail)',
    descricao: 'E-mails transacionais enviados via Resend.',
    textoNovo: 'Novo envio',
    colunas: [
      { titulo: 'Destinatário', larga: true },
      { titulo: 'Assunto' },
      { titulo: 'Enviado em' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['ana.martins@rorainopolisemp.com.br', 'Contrato assinado com sucesso', '29/07/2025 08:05', { selo: { texto: 'Entregue', tom: 'ok' } }],
      ['bruno.costa@rorainopolisemp.com.br', 'Boleto de julho disponível', '28/07/2025 17:40', { selo: { texto: 'Entregue', tom: 'ok' } }],
      ['camila.dias@rorainopolisemp.com.br', 'Confirmação de recebimento Pix', '27/07/2025 12:00', { selo: { texto: 'Enviado', tom: 'info' } }],
      ['diego.lopes@rorainopolisemp.com.br', 'Notificação de inadimplência', '23/07/2025 09:30', { selo: { texto: 'Rejeitado', tom: 'vencido' } }],
      ['domínio remetente', 'Verificação DKIM/SPF', '10/07/2025 08:00', { selo: { texto: 'Pendente', tom: 'atencao' } }],
    ],
  },
  '/integracoes/viacep': {
    titulo: 'ViaCEP',
    descricao: 'Consultas de endereço realizadas via API ViaCEP.',
    textoNovo: 'Nova consulta',
    colunas: [
      { titulo: 'CEP consultado' },
      { titulo: 'Endereço retornado', larga: true },
      { titulo: 'Consultado em' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['69301-000', 'Boa Vista - RR, Centro', '29/07/2025 08:12', { selo: { texto: 'Sucesso', tom: 'ok' } }],
      ['69373-000', 'Rorainópolis - RR, Área Rural', '28/07/2025 15:30', { selo: { texto: 'Sucesso', tom: 'ok' } }],
      ['69360-000', 'Caracaraí - RR, Centro', '27/07/2025 10:00', { selo: { texto: 'Sucesso', tom: 'ok' } }],
      ['00000-000', 'CEP não encontrado', '25/07/2025 09:20', { selo: { texto: 'Erro na consulta', tom: 'vencido' } }],
      ['77000-000', 'Palmas - TO, Centro', '20/07/2025 14:45', { selo: { texto: 'Sucesso', tom: 'ok' } }],
    ],
  },
  '/integracoes/receita-federal': {
    titulo: 'Receita Federal',
    descricao: 'Consultas de situação cadastral de CPF e CNPJ na Receita Federal.',
    textoNovo: 'Nova consulta',
    colunas: [
      { titulo: 'Documento', larga: true },
      { titulo: 'Tipo' },
      { titulo: 'Resultado' },
      { titulo: 'Consultado em' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['111.222.333-44', 'CPF', 'Regular', '29/07/2025 07:20', { selo: { texto: 'Sucesso', tom: 'ok' } }],
      ['12.345.678/0001-90', 'CNPJ', 'Ativa', '28/07/2025 16:00', { selo: { texto: 'Sucesso', tom: 'ok' } }],
      ['222.333.444-55', 'CPF', 'Pendente de regularização', '26/07/2025 11:30', { selo: { texto: 'Pendente', tom: 'atencao' } }],
      ['333.444.555-66', 'CPF', 'Não disponível', '24/07/2025 09:00', { selo: { texto: 'Erro na consulta', tom: 'vencido' } }],
      ['67.890.123/0001-45', 'CNPJ', 'Ativa', '15/07/2025 10:10', { selo: { texto: 'Sucesso', tom: 'ok' } }],
    ],
  },
  '/integracoes/serasa': {
    titulo: 'Serasa',
    descricao: 'Consultas de score e negativações via Serasa Experian.',
    textoNovo: 'Nova consulta',
    colunas: [
      { titulo: 'Documento', larga: true },
      { titulo: 'Score', numerico: true },
      { titulo: 'Restrições', numerico: true },
      { titulo: 'Consultado em' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['111.222.333-44', 720, 0, '29/07/2025 07:10', { selo: { texto: 'Sucesso', tom: 'ok' } }],
      ['222.333.444-55', 480, 2, '28/07/2025 14:50', { selo: { texto: 'Sucesso', tom: 'ok' } }],
      ['333.444.555-66', 0, 0, '27/07/2025 09:30', { selo: { texto: 'Erro na consulta', tom: 'vencido' } }],
      ['444.555.666-77', 610, 1, '21/07/2025 11:00', { selo: { texto: 'Sucesso', tom: 'ok' } }],
      ['Contrato de acesso Serasa', 0, 0, '01/07/2025 08:00', { selo: { texto: 'Não configurado', tom: 'neutro' } }],
    ],
  },
  '/integracoes/apis-proprias': {
    titulo: 'APIs próprias',
    descricao: 'Chaves e integrações expostas pela API própria do Gestrato.',
    textoNovo: 'Nova chave de API',
    colunas: [
      { titulo: 'Nome da chave', larga: true },
      { titulo: 'Escopo' },
      { titulo: 'Chamadas no mês', numerico: true },
      { titulo: 'Última utilização' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['App mobile oficial', 'Leitura/escrita', 48210, '29/07/2025 08:20', { selo: { texto: 'Ativa', tom: 'ok' } }],
      ['Integração contábil externa', 'Somente leitura', 3120, '28/07/2025 22:00', { selo: { texto: 'Ativa', tom: 'ok' } }],
      ['Portal do corretor', 'Leitura/escrita', 15980, '29/07/2025 07:45', { selo: { texto: 'Ativa', tom: 'ok' } }],
      ['Chave de homologação', 'Leitura/escrita', 210, '18/07/2025 10:00', { selo: { texto: 'Em teste', tom: 'info' } }],
      ['Chave revogada BI legado', 'Somente leitura', 0, '02/05/2025 09:00', { selo: { texto: 'Revogada', tom: 'vencido' } }],
    ],
  },
  '/portal-cliente/login': {
    titulo: 'Acessos do portal do cliente',
    descricao: 'Últimos acessos de clientes ao portal do cliente.',
    textoNovo: 'Novo acesso',
    colunas: [
      { titulo: 'Cliente', larga: true },
      { titulo: 'CPF' },
      { titulo: 'Dispositivo' },
      { titulo: 'Data/hora' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Marcos Antônio Ferreira', '111.222.333-44', 'Navegador (Chrome)', '29/07/2025 08:00', { selo: { texto: 'Sucesso', tom: 'ok' } }],
      ['Juliana Beatriz Souza', '222.333.444-55', 'App mobile', '28/07/2025 20:15', { selo: { texto: 'Sucesso', tom: 'ok' } }],
      ['Carlos Eduardo Nascimento', '333.444.555-66', 'Navegador (Safari)', '27/07/2025 13:40', { selo: { texto: 'Sucesso', tom: 'ok' } }],
      ['Fernanda Lima Rocha', '444.555.666-77', 'App mobile', '25/07/2025 09:00', { selo: { texto: 'Senha incorreta', tom: 'vencido' } }],
      ['Ricardo Alves Pereira', '555.666.777-88', 'Navegador (Edge)', '20/07/2025 18:30', { selo: { texto: 'Bloqueado', tom: 'critico' } }],
    ],
  },
  '/portal-cliente/parcelas': {
    titulo: 'Parcelas (portal do cliente)',
    descricao: 'Parcelas visualizadas pelos clientes no portal.',
    textoNovo: 'Nova parcela',
    colunas: [
      { titulo: 'Cliente', larga: true },
      { titulo: 'Contrato' },
      { titulo: 'Parcela' },
      { titulo: 'Valor', numerico: true },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Marcos Antônio Ferreira', 'CT-2025-0142', '12/60', 'R$ 890,00', { selo: { texto: 'Em dia', tom: 'ok' } }],
      ['Juliana Beatriz Souza', 'CT-2025-0098', '05/48', 'R$ 1.120,00', { selo: { texto: 'Em dia', tom: 'ok' } }],
      ['Carlos Eduardo Nascimento', 'CT-2024-0231', '30/36', 'R$ 650,00', { selo: { texto: 'Vencida', tom: 'vencido' } }],
      ['Fernanda Lima Rocha', 'CT-2025-0055', '02/60', 'R$ 980,00', { selo: { texto: 'A vencer', tom: 'atencao' } }],
      ['Ricardo Alves Pereira', 'CT-2024-0187', '48/48', 'R$ 1.340,00', { selo: { texto: 'Quitada', tom: 'ok' } }],
    ],
  },
  '/portal-cliente/boletos': {
    titulo: 'Boletos (portal do cliente)',
    descricao: 'Boletos disponibilizados aos clientes para download.',
    textoNovo: 'Novo boleto',
    colunas: [
      { titulo: 'Cliente', larga: true },
      { titulo: 'Nosso número' },
      { titulo: 'Valor', numerico: true },
      { titulo: 'Vencimento' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Marcos Antônio Ferreira', '00184521', 'R$ 890,00', '05/08/2025', { selo: { texto: 'Emitido', tom: 'ok' } }],
      ['Juliana Beatriz Souza', '00184498', 'R$ 1.120,00', '10/08/2025', { selo: { texto: 'Emitido', tom: 'ok' } }],
      ['Carlos Eduardo Nascimento', '00181203', 'R$ 650,00', '15/07/2025', { selo: { texto: 'Vencido', tom: 'vencido' } }],
      ['Fernanda Lima Rocha', '00184550', 'R$ 980,00', '01/09/2025', { selo: { texto: 'Emitido', tom: 'ok' } }],
      ['Ricardo Alves Pereira', '00179987', 'R$ 1.340,00', '20/06/2025', { selo: { texto: 'Pago', tom: 'ok' } }],
    ],
  },
  '/portal-cliente/pix': {
    titulo: 'Pix (portal do cliente)',
    descricao: 'Cobranças Pix geradas para pagamento no portal.',
    textoNovo: 'Novo Pix',
    colunas: [
      { titulo: 'Cliente', larga: true },
      { titulo: 'Identificador Txid' },
      { titulo: 'Valor', numerico: true },
      { titulo: 'Gerado em' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Marcos Antônio Ferreira', 'TXID48A9F2', 'R$ 890,00', '29/07/2025 08:00', { selo: { texto: 'Pago', tom: 'ok' } }],
      ['Juliana Beatriz Souza', 'TXID91C3D0', 'R$ 1.120,00', '28/07/2025 19:20', { selo: { texto: 'Aguardando pagamento', tom: 'atencao' } }],
      ['Carlos Eduardo Nascimento', 'TXID22B7E1', 'R$ 650,00', '27/07/2025 09:10', { selo: { texto: 'Expirado', tom: 'vencido' } }],
      ['Fernanda Lima Rocha', 'TXID65F0A3', 'R$ 980,00', '26/07/2025 14:45', { selo: { texto: 'Pago', tom: 'ok' } }],
      ['Ricardo Alves Pereira', 'TXID09D4C7', 'R$ 1.340,00', '25/07/2025 11:00', { selo: { texto: 'Pago', tom: 'ok' } }],
    ],
  },
  '/portal-cliente/contrato': {
    titulo: 'Contrato (portal do cliente)',
    descricao: 'Contratos disponibilizados para consulta dos clientes.',
    textoNovo: 'Novo contrato',
    colunas: [
      { titulo: 'Cliente', larga: true },
      { titulo: 'Contrato' },
      { titulo: 'Lote' },
      { titulo: 'Assinado em' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Marcos Antônio Ferreira', 'CT-2025-0142', 'Quadra A, Lote 12', '10/03/2025', { selo: { texto: 'Assinado', tom: 'ok' } }],
      ['Juliana Beatriz Souza', 'CT-2025-0098', 'Quadra B, Lote 07', '22/01/2025', { selo: { texto: 'Assinado', tom: 'ok' } }],
      ['Carlos Eduardo Nascimento', 'CT-2024-0231', 'Quadra 03, Lote 21', '05/09/2024', { selo: { texto: 'Assinado', tom: 'ok' } }],
      ['Fernanda Lima Rocha', 'CT-2025-0055', 'Quadra C, Lote 04', '—', { selo: { texto: 'Aguardando assinatura', tom: 'atencao' } }],
      ['Ricardo Alves Pereira', 'CT-2024-0187', 'Quadra 01, Lote 15', '18/06/2024', { selo: { texto: 'Cancelado', tom: 'critico' } }],
    ],
  },
  '/portal-cliente/historico': {
    titulo: 'Histórico (portal do cliente)',
    descricao: 'Histórico de eventos e interações do cliente no portal.',
    textoNovo: 'Novo evento',
    colunas: [
      { titulo: 'Cliente', larga: true },
      { titulo: 'Evento' },
      { titulo: 'Data/hora' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Marcos Antônio Ferreira', 'Download de boleto', '29/07/2025 08:05', { selo: { texto: 'Concluído', tom: 'ok' } }],
      ['Juliana Beatriz Souza', 'Alteração de e-mail cadastral', '27/07/2025 16:40', { selo: { texto: 'Concluído', tom: 'ok' } }],
      ['Carlos Eduardo Nascimento', 'Solicitação de segunda via', '25/07/2025 10:20', { selo: { texto: 'Em análise', tom: 'info' } }],
      ['Fernanda Lima Rocha', 'Pedido de renegociação', '20/07/2025 09:00', { selo: { texto: 'Pendente', tom: 'atencao' } }],
      ['Ricardo Alves Pereira', 'Reclamação de cobrança indevida', '15/07/2025 14:15', { selo: { texto: 'Rejeitado', tom: 'vencido' } }],
    ],
  },
  '/portal-cliente/solicitacoes': {
    titulo: 'Solicitações',
    descricao: 'Solicitações abertas pelos clientes através do portal.',
    textoNovo: 'Nova solicitação',
    colunas: [
      { titulo: 'Cliente', larga: true },
      { titulo: 'Assunto' },
      { titulo: 'Protocolo' },
      { titulo: 'Aberta em' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Marcos Antônio Ferreira', 'Segunda via de contrato', 'SOL-3021', '28/07/2025 09:30', { selo: { texto: 'Concluída', tom: 'ok' } }],
      ['Juliana Beatriz Souza', 'Alteração de dia de vencimento', 'SOL-3045', '27/07/2025 15:10', { selo: { texto: 'Em análise', tom: 'info' } }],
      ['Carlos Eduardo Nascimento', 'Quitação antecipada', 'SOL-3050', '26/07/2025 11:00', { selo: { texto: 'Pendente', tom: 'atencao' } }],
      ['Fernanda Lima Rocha', 'Troca de titularidade', 'SOL-2998', '18/07/2025 08:45', { selo: { texto: 'Recusada', tom: 'vencido' } }],
      ['Ricardo Alves Pereira', 'Emissão de boleto avulso', 'SOL-3061', '29/07/2025 07:50', { selo: { texto: 'Concluída', tom: 'ok' } }],
    ],
  },
  '/portal-cliente/atualizacao-cadastral': {
    titulo: 'Atualização cadastral',
    descricao: 'Solicitações de atualização de dados cadastrais dos clientes.',
    textoNovo: 'Nova atualização',
    colunas: [
      { titulo: 'Cliente', larga: true },
      { titulo: 'Campo alterado' },
      { titulo: 'Solicitado em' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Marcos Antônio Ferreira', 'Telefone', '29/07/2025 08:10', { selo: { texto: 'Aprovada', tom: 'ok' } }],
      ['Juliana Beatriz Souza', 'Endereço', '27/07/2025 14:20', { selo: { texto: 'Em análise', tom: 'info' } }],
      ['Carlos Eduardo Nascimento', 'E-mail', '25/07/2025 09:30', { selo: { texto: 'Aprovada', tom: 'ok' } }],
      ['Fernanda Lima Rocha', 'Dados bancários', '22/07/2025 10:00', { selo: { texto: 'Pendente de documento', tom: 'atencao' } }],
      ['Ricardo Alves Pereira', 'Nome completo', '10/07/2025 16:00', { selo: { texto: 'Recusada', tom: 'vencido' } }],
    ],
  },
  '/portal-cliente/renegociacao': {
    titulo: 'Renegociação (portal do cliente)',
    descricao: 'Propostas de renegociação solicitadas pelos clientes.',
    textoNovo: 'Nova renegociação',
    colunas: [
      { titulo: 'Cliente', larga: true },
      { titulo: 'Contrato' },
      { titulo: 'Valor em atraso', numerico: true },
      { titulo: 'Solicitada em' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Carlos Eduardo Nascimento', 'CT-2024-0231', 'R$ 1.950,00', '26/07/2025 11:15', { selo: { texto: 'Em análise', tom: 'info' } }],
      ['Fernanda Lima Rocha', 'CT-2025-0055', 'R$ 980,00', '24/07/2025 09:40', { selo: { texto: 'Pendente', tom: 'atencao' } }],
      ['Diego Fernandes Lopes', 'CT-2023-0119', 'R$ 3.420,00', '15/07/2025 10:00', { selo: { texto: 'Aprovada', tom: 'ok' } }],
      ['Marcos Antônio Ferreira', 'CT-2025-0142', 'R$ 0,00', '—', { selo: { texto: 'Não configurada', tom: 'neutro' } }],
      ['Ricardo Alves Pereira', 'CT-2024-0187', 'R$ 2.100,00', '05/06/2025 08:30', { selo: { texto: 'Recusada', tom: 'vencido' } }],
    ],
  },
  '/portal-corretor/clientes': {
    titulo: 'Clientes (portal do corretor)',
    descricao: 'Clientes vinculados à carteira do corretor.',
    textoNovo: 'Novo cliente',
    colunas: [
      { titulo: 'Cliente', larga: true },
      { titulo: 'CPF' },
      { titulo: 'Contratos ativos', numerico: true },
      { titulo: 'Último contato' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Marcos Antônio Ferreira', '111.222.333-44', 1, '28/07/2025 09:00', { selo: { texto: 'Ativo', tom: 'ok' } }],
      ['Juliana Beatriz Souza', '222.333.444-55', 1, '27/07/2025 16:15', { selo: { texto: 'Ativo', tom: 'ok' } }],
      ['Carlos Eduardo Nascimento', '333.444.555-66', 2, '20/07/2025 11:30', { selo: { texto: 'Inadimplente', tom: 'vencido' } }],
      ['Fernanda Lima Rocha', '444.555.666-77', 1, '18/07/2025 14:00', { selo: { texto: 'Ativo', tom: 'ok' } }],
      ['Ricardo Alves Pereira', '555.666.777-88', 0, '02/06/2025 10:20', { selo: { texto: 'Prospecto', tom: 'info' } }],
    ],
  },
  '/portal-corretor/vendas': {
    titulo: 'Vendas (portal do corretor)',
    descricao: 'Vendas realizadas pelo corretor no período.',
    textoNovo: 'Nova venda',
    colunas: [
      { titulo: 'Cliente', larga: true },
      { titulo: 'Lote' },
      { titulo: 'Valor da venda', numerico: true },
      { titulo: 'Data da venda' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Marcos Antônio Ferreira', 'Quadra A, Lote 12', 'R$ 128.000,00', '10/03/2025', { selo: { texto: 'Concluída', tom: 'ok' } }],
      ['Juliana Beatriz Souza', 'Quadra B, Lote 07', 'R$ 145.500,00', '22/01/2025', { selo: { texto: 'Concluída', tom: 'ok' } }],
      ['Fernanda Lima Rocha', 'Quadra C, Lote 04', 'R$ 132.900,00', '29/07/2025', { selo: { texto: 'Em assinatura', tom: 'atencao' } }],
      ['Ricardo Alves Pereira', 'Quadra 01, Lote 15', 'R$ 98.400,00', '18/06/2024', { selo: { texto: 'Cancelada', tom: 'critico' } }],
      ['Novo interessado Boa Vista', 'Quadra A, Lote 18', 'R$ 120.000,00', '25/07/2025', { selo: { texto: 'Em negociação', tom: 'info' } }],
    ],
  },
  '/portal-corretor/comissao': {
    titulo: 'Comissão (portal do corretor)',
    descricao: 'Comissões apuradas para o corretor a partir das vendas.',
    textoNovo: 'Nova comissão',
    colunas: [
      { titulo: 'Venda', larga: true },
      { titulo: 'Percentual', numerico: true },
      { titulo: 'Valor', numerico: true },
      { titulo: 'Competência' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Quadra A, Lote 12 - Marcos Ferreira', '5,0%', 'R$ 6.400,00', 'Julho/2025', { selo: { texto: 'Paga', tom: 'ok' } }],
      ['Quadra B, Lote 07 - Juliana Souza', '5,0%', 'R$ 7.275,00', 'Julho/2025', { selo: { texto: 'Paga', tom: 'ok' } }],
      ['Quadra C, Lote 04 - Fernanda Rocha', '4,5%', 'R$ 5.980,50', 'Agosto/2025', { selo: { texto: 'A pagar', tom: 'atencao' } }],
      ['Quadra 01, Lote 15 - Ricardo Pereira', '5,0%', 'R$ 4.920,00', 'Junho/2024', { selo: { texto: 'Estornada', tom: 'vencido' } }],
      ['Quadra A, Lote 18 - Novo interessado', '5,0%', 'R$ 6.000,00', 'Agosto/2025', { selo: { texto: 'Em cálculo', tom: 'info' } }],
    ],
  },
  '/portal-corretor/contratos': {
    titulo: 'Contratos (portal do corretor)',
    descricao: 'Contratos originados pelas vendas do corretor.',
    textoNovo: 'Novo contrato',
    colunas: [
      { titulo: 'Cliente', larga: true },
      { titulo: 'Contrato' },
      { titulo: 'Valor total', numerico: true },
      { titulo: 'Assinado em' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Marcos Antônio Ferreira', 'CT-2025-0142', 'R$ 128.000,00', '10/03/2025', { selo: { texto: 'Vigente', tom: 'ok' } }],
      ['Juliana Beatriz Souza', 'CT-2025-0098', 'R$ 145.500,00', '22/01/2025', { selo: { texto: 'Vigente', tom: 'ok' } }],
      ['Fernanda Lima Rocha', 'CT-2025-0055', 'R$ 132.900,00', '—', { selo: { texto: 'Aguardando assinatura', tom: 'atencao' } }],
      ['Ricardo Alves Pereira', 'CT-2024-0187', 'R$ 98.400,00', '18/06/2024', { selo: { texto: 'Cancelado', tom: 'critico' } }],
      ['Carlos Eduardo Nascimento', 'CT-2024-0231', 'R$ 89.700,00', '05/09/2024', { selo: { texto: 'Inadimplente', tom: 'vencido' } }],
    ],
  },
  '/portal-corretor/agenda': {
    titulo: 'Agenda (portal do corretor)',
    descricao: 'Compromissos e visitas agendadas pelo corretor.',
    textoNovo: 'Novo compromisso',
    colunas: [
      { titulo: 'Compromisso', larga: true },
      { titulo: 'Cliente' },
      { titulo: 'Local' },
      { titulo: 'Data/hora' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Visita ao lote', 'Ricardo Alves Pereira', 'Quadra A, Lote 18', '30/07/2025 10:00', { selo: { texto: 'Confirmado', tom: 'ok' } }],
      ['Assinatura de contrato', 'Fernanda Lima Rocha', 'Escritório Boa Vista', '31/07/2025 14:00', { selo: { texto: 'Pendente', tom: 'atencao' } }],
      ['Reunião de renegociação', 'Carlos Eduardo Nascimento', 'Online', '29/07/2025 16:30', { selo: { texto: 'Confirmado', tom: 'ok' } }],
      ['Visita ao lote', 'Novo interessado Boa Vista', 'Quadra A, Lote 18', '01/08/2025 09:00', { selo: { texto: 'A confirmar', tom: 'info' } }],
      ['Entrega de documentação', 'Diego Fernandes Lopes', 'Escritório Palmas', '18/07/2025 11:00', { selo: { texto: 'Cancelado', tom: 'vencido' } }],
    ],
  },
  '/mobile/dashboard': {
    titulo: 'Mobile · Dashboard',
    descricao: 'Indicadores exibidos no painel inicial do aplicativo mobile.',
    textoNovo: 'Novo indicador',
    colunas: [
      { titulo: 'Indicador', larga: true },
      { titulo: 'Perfil' },
      { titulo: 'Valor', numerico: true },
      { titulo: 'Atualizado em' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Parcelas em aberto', 'Cliente', 3, '29/07/2025 08:00', { selo: { texto: 'Atualizado', tom: 'ok' } }],
      ['Vendas do mês', 'Corretor', 6, '29/07/2025 07:30', { selo: { texto: 'Atualizado', tom: 'ok' } }],
      ['Comissão a receber', 'Corretor', 'R$ 12.400,00', '29/07/2025 07:30', { selo: { texto: 'Atualizado', tom: 'ok' } }],
      ['Contratos inadimplentes', 'Gestor', 18, '28/07/2025 22:00', { selo: { texto: 'Atenção', tom: 'atencao' } }],
      ['Widget de metas', 'Corretor', 0, '10/06/2025 10:00', { selo: { texto: 'Não configurado', tom: 'neutro' } }],
    ],
  },
  '/mobile/financeiro': {
    titulo: 'Mobile · Financeiro',
    descricao: 'Resumo financeiro disponível no aplicativo mobile.',
    textoNovo: 'Novo lançamento',
    colunas: [
      { titulo: 'Cliente', larga: true },
      { titulo: 'Parcela' },
      { titulo: 'Valor', numerico: true },
      { titulo: 'Vencimento' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Marcos Antônio Ferreira', '12/60', 'R$ 890,00', '05/08/2025', { selo: { texto: 'A vencer', tom: 'atencao' } }],
      ['Juliana Beatriz Souza', '05/48', 'R$ 1.120,00', '10/08/2025', { selo: { texto: 'A vencer', tom: 'atencao' } }],
      ['Carlos Eduardo Nascimento', '30/36', 'R$ 650,00', '15/07/2025', { selo: { texto: 'Vencida', tom: 'vencido' } }],
      ['Fernanda Lima Rocha', '02/60', 'R$ 980,00', '01/09/2025', { selo: { texto: 'Em dia', tom: 'ok' } }],
      ['Ricardo Alves Pereira', '48/48', 'R$ 1.340,00', '20/06/2025', { selo: { texto: 'Quitada', tom: 'ok' } }],
    ],
  },
  '/mobile/cobranca': {
    titulo: 'Mobile · Cobrança',
    descricao: 'Ações de cobrança disponíveis para a equipe no aplicativo mobile.',
    textoNovo: 'Nova ação',
    colunas: [
      { titulo: 'Cliente', larga: true },
      { titulo: 'Ação' },
      { titulo: 'Valor em atraso', numerico: true },
      { titulo: 'Registrada em' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Carlos Eduardo Nascimento', 'Ligação de cobrança', 'R$ 1.950,00', '29/07/2025 09:00', { selo: { texto: 'Concluída', tom: 'ok' } }],
      ['Diego Fernandes Lopes', 'Envio de notificação extrajudicial', 'R$ 3.420,00', '25/07/2025 10:30', { selo: { texto: 'Em andamento', tom: 'info' } }],
      ['Fernanda Lima Rocha', 'Mensagem de cobrança amigável', 'R$ 980,00', '24/07/2025 08:40', { selo: { texto: 'Pendente', tom: 'atencao' } }],
      ['Ricardo Alves Pereira', 'Encaminhamento jurídico', 'R$ 2.100,00', '10/06/2025 11:15', { selo: { texto: 'Encaminhado', tom: 'critico' } }],
      ['Marcos Antônio Ferreira', 'Cobrança automática', 'R$ 0,00', '20/07/2025 07:00', { selo: { texto: 'Não necessária', tom: 'neutro' } }],
    ],
  },
  '/mobile/contratos': {
    titulo: 'Mobile · Contratos',
    descricao: 'Contratos consultados via aplicativo mobile.',
    textoNovo: 'Novo contrato',
    colunas: [
      { titulo: 'Cliente', larga: true },
      { titulo: 'Contrato' },
      { titulo: 'Lote' },
      { titulo: 'Consultado em' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Marcos Antônio Ferreira', 'CT-2025-0142', 'Quadra A, Lote 12', '29/07/2025 08:15', { selo: { texto: 'Vigente', tom: 'ok' } }],
      ['Juliana Beatriz Souza', 'CT-2025-0098', 'Quadra B, Lote 07', '28/07/2025 19:00', { selo: { texto: 'Vigente', tom: 'ok' } }],
      ['Carlos Eduardo Nascimento', 'CT-2024-0231', 'Quadra 03, Lote 21', '27/07/2025 12:20', { selo: { texto: 'Inadimplente', tom: 'vencido' } }],
      ['Fernanda Lima Rocha', 'CT-2025-0055', 'Quadra C, Lote 04', '—', { selo: { texto: 'Aguardando assinatura', tom: 'atencao' } }],
      ['Ricardo Alves Pereira', 'CT-2024-0187', 'Quadra 01, Lote 15', '15/06/2025 09:40', { selo: { texto: 'Cancelado', tom: 'critico' } }],
    ],
  },
  '/mobile/clientes': {
    titulo: 'Mobile · Clientes',
    descricao: 'Clientes consultados por corretores e equipe interna no aplicativo mobile.',
    textoNovo: 'Novo cliente',
    colunas: [
      { titulo: 'Cliente', larga: true },
      { titulo: 'CPF' },
      { titulo: 'Telefone' },
      { titulo: 'Último acesso' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Marcos Antônio Ferreira', '111.222.333-44', '(95) 99123-4567', '29/07/2025 08:00', { selo: { texto: 'Ativo', tom: 'ok' } }],
      ['Juliana Beatriz Souza', '222.333.444-55', '(95) 99876-5432', '28/07/2025 20:15', { selo: { texto: 'Ativo', tom: 'ok' } }],
      ['Carlos Eduardo Nascimento', '333.444.555-66', '(63) 99234-1122', '20/07/2025 11:30', { selo: { texto: 'Inadimplente', tom: 'vencido' } }],
      ['Fernanda Lima Rocha', '444.555.666-77', '(62) 99345-8890', '18/07/2025 14:00', { selo: { texto: 'Ativo', tom: 'ok' } }],
      ['Ricardo Alves Pereira', '555.666.777-88', '(95) 99456-7788', '02/06/2025 10:20', { selo: { texto: 'Inativo', tom: 'neutro' } }],
    ],
  },
  '/mobile/push': {
    titulo: 'Mobile · Notificações push',
    descricao: 'Notificações push enviadas para os aplicativos dos clientes e corretores.',
    textoNovo: 'Nova notificação',
    colunas: [
      { titulo: 'Título', larga: true },
      { titulo: 'Público' },
      { titulo: 'Dispositivos', numerico: true },
      { titulo: 'Enviada em' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Boleto disponível para pagamento', 'Clientes', 1240, '29/07/2025 07:00', { selo: { texto: 'Entregue', tom: 'ok' } }],
      ['Nova meta de vendas do mês', 'Corretores', 58, '28/07/2025 08:00', { selo: { texto: 'Entregue', tom: 'ok' } }],
      ['Parcela vence amanhã', 'Clientes', 890, '27/07/2025 18:00', { selo: { texto: 'Enviando', tom: 'info' } }],
      ['Atualização do aplicativo disponível', 'Todos', 2130, '20/07/2025 09:00', { selo: { texto: 'Falha no envio', tom: 'vencido' } }],
      ['Campanha de indicação', 'Corretores', 0, '15/07/2025 10:00', { selo: { texto: 'Não configurada', tom: 'neutro' } }],
    ],
  },
};

export default telas;
