import type { ConfigDeListagem } from '@/componentes/comuns/PaginaDeListagem';

const telas: Record<string, ConfigDeListagem> = {
  '/dashboard/financeiro': {
    titulo: 'Dashboard financeiro',
    descricao: 'Indicadores financeiros consolidados do mês.',
    textoNovo: 'Novo indicador',
    colunas: [
      { titulo: 'Indicador', larga: true },
      { titulo: 'Valor' },
      { titulo: 'Variação' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Receita do mês', 'R$ 482.300,00', '+8,4%', { selo: { texto: 'Em dia', tom: 'ok' } }],
      ['Despesas do mês', 'R$ 156.900,00', '+2,1%', { selo: { texto: 'Atenção', tom: 'atencao' } }],
      ['Saldo em caixa', 'R$ 1.245.780,00', '+5,3%', { selo: { texto: 'Em dia', tom: 'ok' } }],
      ['Recebimentos pendentes', 'R$ 98.450,00', '-3,2%', { selo: { texto: 'Atenção', tom: 'atencao' } }],
      ['Inadimplência', '6,8%', '+0,9%', { selo: { texto: 'Vencido', tom: 'vencido' } }],
      ['Ticket médio', 'R$ 3.420,00', '+1,5%', { selo: { texto: 'Em dia', tom: 'ok' } }],
    ],
  },
  '/dashboard/comercial': {
    titulo: 'Dashboard comercial',
    descricao: 'Indicadores de vendas e desempenho comercial do mês.',
    textoNovo: 'Novo indicador',
    colunas: [
      { titulo: 'Indicador', larga: true },
      { titulo: 'Valor' },
      { titulo: 'Variação' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Vendas do mês', '42 unidades', '+12%', { selo: { texto: 'Em dia', tom: 'ok' } }],
      ['Faturamento em vendas', 'R$ 1.850.000,00', '+15%', { selo: { texto: 'Em dia', tom: 'ok' } }],
      ['Propostas em andamento', '18', '+4', { selo: { texto: 'Gerado', tom: 'info' } }],
      ['Taxa de conversão', '24,5%', '+2,1%', { selo: { texto: 'Em dia', tom: 'ok' } }],
      ['Distratos no mês', '3', '+1', { selo: { texto: 'Atenção', tom: 'atencao' } }],
      ['Corretores ativos', '12', '0', { selo: { texto: 'Inativo', tom: 'neutro' } }],
    ],
  },
  '/dashboard/inadimplencia': {
    titulo: 'Dashboard de inadimplência',
    descricao: 'Indicadores de atraso e recuperação de crédito.',
    textoNovo: 'Novo indicador',
    colunas: [
      { titulo: 'Indicador', larga: true },
      { titulo: 'Valor' },
      { titulo: 'Variação' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Parcelas vencidas', '187', '+14', { selo: { texto: 'Vencido', tom: 'vencido' } }],
      ['Valor em atraso', 'R$ 342.680,00', '+9,2%', { selo: { texto: 'Vencido', tom: 'vencido' } }],
      ['Clientes inadimplentes', '96', '+7', { selo: { texto: 'Vencido', tom: 'vencido' } }],
      ['Taxa de inadimplência', '6,8%', '+0,5%', { selo: { texto: 'Atenção', tom: 'atencao' } }],
      ['Recuperado no mês', 'R$ 78.400,00', '+11%', { selo: { texto: 'Em dia', tom: 'ok' } }],
      ['Acordos firmados', '21', '+6', { selo: { texto: 'Gerado', tom: 'info' } }],
    ],
  },
  '/dashboard/contratos': {
    titulo: 'Dashboard de contratos',
    descricao: 'Indicadores da carteira de contratos.',
    textoNovo: 'Novo indicador',
    colunas: [
      { titulo: 'Indicador', larga: true },
      { titulo: 'Valor' },
      { titulo: 'Variação' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Contratos ativos', '1.284', '+18', { selo: { texto: 'Em dia', tom: 'ok' } }],
      ['Contratos assinados no mês', '42', '+9', { selo: { texto: 'Em dia', tom: 'ok' } }],
      ['Contratos quitados', '356', '+12', { selo: { texto: 'Em dia', tom: 'ok' } }],
      ['Contratos cancelados', '9', '+2', { selo: { texto: 'Atenção', tom: 'atencao' } }],
      ['Contratos em análise jurídica', '5', '+1', { selo: { texto: 'Gerado', tom: 'info' } }],
      ['Tempo médio de aprovação', '4,2 dias', '-0,6 dias', { selo: { texto: 'Em dia', tom: 'ok' } }],
    ],
  },
  '/dashboard/cobranca': {
    titulo: 'Dashboard de cobrança',
    descricao: 'Indicadores de emissão e recebimento de cobranças.',
    textoNovo: 'Novo indicador',
    colunas: [
      { titulo: 'Indicador', larga: true },
      { titulo: 'Valor' },
      { titulo: 'Variação' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Boletos emitidos no mês', '1.520', '+6%', { selo: { texto: 'Gerado', tom: 'info' } }],
      ['Boletos pagos', '1.298', '+4%', { selo: { texto: 'Em dia', tom: 'ok' } }],
      ['Boletos vencidos', '187', '+11%', { selo: { texto: 'Vencido', tom: 'vencido' } }],
      ['Pix recebidos', '412', '+19%', { selo: { texto: 'Em dia', tom: 'ok' } }],
      ['Régua de cobrança ativa', '3 etapas', '0', { selo: { texto: 'Inativo', tom: 'neutro' } }],
      ['Custo de emissão', 'R$ 2.340,00', '+1,2%', { selo: { texto: 'Atenção', tom: 'atencao' } }],
    ],
  },
  '/dashboard/fluxo-de-caixa': {
    titulo: 'Dashboard de fluxo de caixa',
    descricao: 'Indicadores de entradas e saídas projetadas e realizadas.',
    textoNovo: 'Novo indicador',
    colunas: [
      { titulo: 'Indicador', larga: true },
      { titulo: 'Valor' },
      { titulo: 'Variação' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Entradas previstas', 'R$ 612.000,00', '+7%', { selo: { texto: 'Em dia', tom: 'ok' } }],
      ['Saídas previstas', 'R$ 198.500,00', '+3%', { selo: { texto: 'Atenção', tom: 'atencao' } }],
      ['Saldo projetado', 'R$ 413.500,00', '+9%', { selo: { texto: 'Em dia', tom: 'ok' } }],
      ['Entradas realizadas', 'R$ 540.200,00', '+5%', { selo: { texto: 'Em dia', tom: 'ok' } }],
      ['Saídas realizadas', 'R$ 187.300,00', '+2%', { selo: { texto: 'Atenção', tom: 'atencao' } }],
      ['Disponibilidade em caixa', 'R$ 1.245.780,00', '+4%', { selo: { texto: 'Em dia', tom: 'ok' } }],
    ],
  },
  '/dashboard/loteamento': {
    titulo: 'Dashboard por loteamento',
    descricao: 'Desempenho de vendas e receita por loteamento.',
    textoNovo: 'Novo indicador',
    colunas: [
      { titulo: 'Loteamento', larga: true },
      { titulo: 'Vendidos', numerico: true },
      { titulo: 'Disponíveis', numerico: true },
      { titulo: 'Receita' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Residencial Rio Branco', 210, 110, 'R$ 890.000,00', { selo: { texto: 'Em dia', tom: 'ok' } }],
      ['Jardim das Palmeiras', 145, 35, 'R$ 620.000,00', { selo: { texto: 'Em dia', tom: 'ok' } }],
      ['Vila Nova Caracaraí', 60, 36, 'R$ 210.000,00', { selo: { texto: 'Atenção', tom: 'atencao' } }],
      ['Recanto dos Ipês', 180, 30, 'R$ 740.000,00', { selo: { texto: 'Em dia', tom: 'ok' } }],
      ['Portal do Cerrado', 300, 150, 'R$ 1.120.000,00', { selo: { texto: 'Gerado', tom: 'info' } }],
    ],
  },
  '/dashboard/empresa': {
    titulo: 'Dashboard por empresa',
    descricao: 'Desempenho financeiro consolidado por empresa do grupo.',
    textoNovo: 'Novo indicador',
    colunas: [
      { titulo: 'Empresa', larga: true },
      { titulo: 'Contratos ativos', numerico: true },
      { titulo: 'Receita do mês' },
      { titulo: 'Inadimplência' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Rorainópolis Empreendimentos Imobiliários Ltda', 420, 'R$ 320.000,00', '5,2%', { selo: { texto: 'Em dia', tom: 'ok' } }],
      ['Norte Terras Loteadora S.A.', 310, 'R$ 210.000,00', '7,8%', { selo: { texto: 'Atenção', tom: 'atencao' } }],
      ['Caracaraí Desenvolvimento Urbano Ltda', 96, 'R$ 85.000,00', '9,1%', { selo: { texto: 'Vencido', tom: 'vencido' } }],
      ['Serra do Sol Incorporadora Ltda', 150, 'R$ 130.000,00', '3,4%', { selo: { texto: 'Em dia', tom: 'ok' } }],
      ['Vale do Cerrado Loteamentos Ltda', 308, 'R$ 260.000,00', '4,6%', { selo: { texto: 'Em dia', tom: 'ok' } }],
    ],
  },
  '/favoritos': {
    titulo: 'Favoritos',
    descricao: 'Telas e registros marcados como favoritos.',
    textoNovo: 'Novo favorito',
    colunas: [
      { titulo: 'Item', larga: true },
      { titulo: 'Tipo' },
      { titulo: 'Último acesso' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Relatório de inadimplência', 'Relatório', '28/07/2026', { selo: { texto: 'Gerado', tom: 'info' } }],
      ['Contrato #4821 - João Batista Ferreira', 'Contrato', '27/07/2026', { selo: { texto: 'Em dia', tom: 'ok' } }],
      ['Loteamento Residencial Rio Branco', 'Loteamento', '25/07/2026', { selo: { texto: 'Em dia', tom: 'ok' } }],
      ['Cliente Maria das Graças Souza', 'Cliente', '24/07/2026', { selo: { texto: 'Em dia', tom: 'ok' } }],
      ['Dashboard financeiro', 'Dashboard', '29/07/2026', { selo: { texto: 'Gerado', tom: 'info' } }],
    ],
  },
  '/ultimos-acessos': {
    titulo: 'Últimos acessos',
    descricao: 'Últimas telas acessadas pelos usuários do sistema.',
    textoNovo: 'Registrar acesso',
    colunas: [
      { titulo: 'Tela', larga: true },
      { titulo: 'Usuário' },
      { titulo: 'Data/Hora' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Relatório de parcelas', 'Lucas Andrade', '29/07/2026 09:12', { selo: { texto: 'Gerado', tom: 'info' } }],
      ['Contrato #5012', 'Fernanda Lima', '29/07/2026 08:47', { selo: { texto: 'Em dia', tom: 'ok' } }],
      ['Cadastro de clientes', 'Marcos Vinícius', '28/07/2026 17:30', { selo: { texto: 'Em dia', tom: 'ok' } }],
      ['Dashboard comercial', 'Patrícia Gomes', '28/07/2026 16:05', { selo: { texto: 'Gerado', tom: 'info' } }],
      ['Relatório de cobranças', 'Rafael Nunes', '28/07/2026 14:22', { selo: { texto: 'Atenção', tom: 'atencao' } }],
    ],
  },
  '/avisos': {
    titulo: 'Avisos',
    descricao: 'Avisos gerais publicados no sistema.',
    textoNovo: 'Novo aviso',
    colunas: [
      { titulo: 'Aviso', larga: true },
      { titulo: 'Categoria' },
      { titulo: 'Data' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Manutenção programada no sistema', 'Sistema', '30/07/2026', { selo: { texto: 'Atenção', tom: 'atencao' } }],
      ['Atualização da régua de cobrança', 'Cobrança', '28/07/2026', { selo: { texto: 'Gerado', tom: 'info' } }],
      ['Novo layout de boletos disponível', 'Financeiro', '26/07/2026', { selo: { texto: 'Gerado', tom: 'info' } }],
      ['Prazo de envio de comissões', 'Comercial', '25/07/2026', { selo: { texto: 'Atenção', tom: 'atencao' } }],
      ['Revisão de contratos pendente', 'Jurídico', '22/07/2026', { selo: { texto: 'Vencido', tom: 'vencido' } }],
    ],
  },
  '/notificacoes': {
    titulo: 'Notificações',
    descricao: 'Notificações recentes geradas pelo sistema.',
    textoNovo: 'Nova notificação',
    colunas: [
      { titulo: 'Notificação', larga: true },
      { titulo: 'Origem' },
      { titulo: 'Data' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['12 parcelas venceram hoje', 'Cobrança', '29/07/2026', { selo: { texto: 'Vencido', tom: 'vencido' } }],
      ['Novo contrato assinado - Lote 45 Quadra B', 'Comercial', '29/07/2026', { selo: { texto: 'Em dia', tom: 'ok' } }],
      ['Boleto Pix confirmado - Cliente Ana Paula Cardoso', 'Financeiro', '28/07/2026', { selo: { texto: 'Em dia', tom: 'ok' } }],
      ['Solicitação de distrato recebida', 'Jurídico', '27/07/2026', { selo: { texto: 'Atenção', tom: 'atencao' } }],
      ['Corretor cadastrado - Ricardo Alves Pereira', 'Comercial', '26/07/2026', { selo: { texto: 'Gerado', tom: 'info' } }],
    ],
  },
  '/agenda': {
    titulo: 'Agenda',
    descricao: 'Compromissos e eventos programados.',
    textoNovo: 'Novo compromisso',
    colunas: [
      { titulo: 'Compromisso', larga: true },
      { titulo: 'Responsável' },
      { titulo: 'Data' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Reunião com incorporadora Vale do Cerrado', 'Diretoria', '30/07/2026', { selo: { texto: 'Gerado', tom: 'info' } }],
      ['Visita técnica ao loteamento Portal do Cerrado', 'Engenharia', '31/07/2026', { selo: { texto: 'Gerado', tom: 'info' } }],
      ['Assinatura de contrato - Lote 12 Quadra D', 'Jurídico', '29/07/2026', { selo: { texto: 'Em dia', tom: 'ok' } }],
      ['Reunião de cobrança mensal', 'Financeiro', '01/08/2026', { selo: { texto: 'Atenção', tom: 'atencao' } }],
      ['Treinamento de novos corretores', 'Comercial', '03/08/2026', { selo: { texto: 'Inativo', tom: 'neutro' } }],
    ],
  },
  '/tarefas': {
    titulo: 'Tarefas',
    descricao: 'Tarefas pendentes atribuídas às equipes.',
    textoNovo: 'Nova tarefa',
    colunas: [
      { titulo: 'Tarefa', larga: true },
      { titulo: 'Responsável' },
      { titulo: 'Prazo' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Enviar boletos do mês', 'Financeiro', '30/07/2026', { selo: { texto: 'Atenção', tom: 'atencao' } }],
      ['Revisar contratos vencidos', 'Jurídico', '31/07/2026', { selo: { texto: 'Vencido', tom: 'vencido' } }],
      ['Atualizar cadastro de corretores', 'Comercial', '02/08/2026', { selo: { texto: 'Inativo', tom: 'neutro' } }],
      ['Conciliar recebimentos Pix', 'Financeiro', '29/07/2026', { selo: { texto: 'Gerado', tom: 'info' } }],
      ['Emitir relatório de inadimplência', 'Cobrança', '29/07/2026', { selo: { texto: 'Atenção', tom: 'atencao' } }],
    ],
  },
  '/relatorios/dashboard-executivo': {
    titulo: 'Relatório executivo',
    descricao: 'Indicadores consolidados para a alta gestão.',
    textoNovo: 'Novo indicador',
    colunas: [
      { titulo: 'Indicador', larga: true },
      { titulo: 'Valor' },
      { titulo: 'Variação' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Receita consolidada', 'R$ 2.480.000,00', '+6,7%', { selo: { texto: 'Em dia', tom: 'ok' } }],
      ['Lotes vendidos no trimestre', '312', '+9%', { selo: { texto: 'Em dia', tom: 'ok' } }],
      ['Inadimplência geral', '6,2%', '+0,4%', { selo: { texto: 'Atenção', tom: 'atencao' } }],
      ['Contratos ativos', '3.140', '+45', { selo: { texto: 'Em dia', tom: 'ok' } }],
      ['Margem líquida', '28,4%', '+1,1%', { selo: { texto: 'Em dia', tom: 'ok' } }],
      ['Custo operacional', 'R$ 610.000,00', '+3,2%', { selo: { texto: 'Atenção', tom: 'atencao' } }],
    ],
  },
  '/relatorios/clientes': {
    titulo: 'Relatório de clientes',
    descricao: 'Clientes cadastrados e situação dos contratos.',
    textoNovo: 'Novo cliente',
    colunas: [
      { titulo: 'Cliente', larga: true },
      { titulo: 'CPF/CNPJ' },
      { titulo: 'Cidade' },
      { titulo: 'Contratos', numerico: true },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Maria das Graças Souza', '123.456.789-00', 'Boa Vista', 2, { selo: { texto: 'Em dia', tom: 'ok' } }],
      ['João Batista Ferreira', '234.567.890-11', 'Rorainópolis', 1, { selo: { texto: 'Em dia', tom: 'ok' } }],
      ['Ana Paula Cardoso', '345.678.901-22', 'Caracaraí', 1, { selo: { texto: 'Atenção', tom: 'atencao' } }],
      ['Ricardo Alves Pereira', '456.789.012-33', 'Boa Vista', 3, { selo: { texto: 'Em dia', tom: 'ok' } }],
      ['Sandra Regina Costa', '567.890.123-44', 'Palmas', 1, { selo: { texto: 'Vencido', tom: 'vencido' } }],
    ],
  },
  '/relatorios/contratos': {
    titulo: 'Relatório de contratos',
    descricao: 'Contratos firmados e sua situação atual.',
    textoNovo: 'Novo contrato',
    colunas: [
      { titulo: 'Contrato' },
      { titulo: 'Cliente', larga: true },
      { titulo: 'Loteamento' },
      { titulo: 'Valor' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['#4821', 'João Batista Ferreira', 'Residencial Rio Branco', 'R$ 85.000,00', { selo: { texto: 'Em dia', tom: 'ok' } }],
      ['#5012', 'Fernanda Lima Souza', 'Jardim das Palmeiras', 'R$ 62.000,00', { selo: { texto: 'Em dia', tom: 'ok' } }],
      ['#4790', 'Ana Paula Cardoso', 'Vila Nova Caracaraí', 'R$ 48.500,00', { selo: { texto: 'Vencido', tom: 'vencido' } }],
      ['#5108', 'Ricardo Alves Pereira', 'Portal do Cerrado', 'R$ 112.000,00', { selo: { texto: 'Em dia', tom: 'ok' } }],
      ['#4955', 'Sandra Regina Costa', 'Recanto dos Ipês', 'R$ 74.300,00', { selo: { texto: 'Atenção', tom: 'atencao' } }],
    ],
  },
  '/relatorios/parcelas': {
    titulo: 'Relatório de parcelas',
    descricao: 'Parcelas em aberto e vencidas por contrato.',
    textoNovo: 'Nova parcela',
    colunas: [
      { titulo: 'Parcela' },
      { titulo: 'Contrato' },
      { titulo: 'Vencimento' },
      { titulo: 'Valor' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['14/60', '#4821', '10/07/2026', 'R$ 1.416,00', { selo: { texto: 'Vencido', tom: 'vencido' } }],
      ['22/48', '#5012', '05/08/2026', 'R$ 1.291,00', { selo: { texto: 'Gerado', tom: 'info' } }],
      ['08/36', '#4790', '15/06/2026', 'R$ 1.347,00', { selo: { texto: 'Vencido', tom: 'vencido' } }],
      ['31/72', '#5108', '10/08/2026', 'R$ 1.555,00', { selo: { texto: 'Gerado', tom: 'info' } }],
      ['19/50', '#4955', '20/07/2026', 'R$ 1.486,00', { selo: { texto: 'Atenção', tom: 'atencao' } }],
    ],
  },
  '/relatorios/recebimentos': {
    titulo: 'Relatório de recebimentos',
    descricao: 'Pagamentos confirmados no período.',
    textoNovo: 'Novo recebimento',
    colunas: [
      { titulo: 'Data' },
      { titulo: 'Cliente', larga: true },
      { titulo: 'Forma de pagamento' },
      { titulo: 'Valor' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['28/07/2026', 'Maria das Graças Souza', 'Pix', 'R$ 1.416,00', { selo: { texto: 'Em dia', tom: 'ok' } }],
      ['27/07/2026', 'João Batista Ferreira', 'Boleto', 'R$ 1.291,00', { selo: { texto: 'Em dia', tom: 'ok' } }],
      ['26/07/2026', 'Ana Paula Cardoso', 'Boleto', 'R$ 1.347,00', { selo: { texto: 'Em dia', tom: 'ok' } }],
      ['25/07/2026', 'Ricardo Alves Pereira', 'Pix', 'R$ 1.555,00', { selo: { texto: 'Em dia', tom: 'ok' } }],
      ['24/07/2026', 'Sandra Regina Costa', 'Transferência', 'R$ 1.486,00', { selo: { texto: 'Em dia', tom: 'ok' } }],
    ],
  },
  '/relatorios/fluxo-de-caixa': {
    titulo: 'Relatório de fluxo de caixa',
    descricao: 'Entradas, saídas e saldo mensal.',
    textoNovo: 'Novo lançamento',
    colunas: [
      { titulo: 'Mês' },
      { titulo: 'Entradas' },
      { titulo: 'Saídas' },
      { titulo: 'Saldo' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Março/2026', 'R$ 520.000,00', 'R$ 180.000,00', 'R$ 340.000,00', { selo: { texto: 'Em dia', tom: 'ok' } }],
      ['Abril/2026', 'R$ 495.000,00', 'R$ 172.000,00', 'R$ 323.000,00', { selo: { texto: 'Em dia', tom: 'ok' } }],
      ['Maio/2026', 'R$ 540.200,00', 'R$ 187.300,00', 'R$ 352.900,00', { selo: { texto: 'Em dia', tom: 'ok' } }],
      ['Junho/2026', 'R$ 480.000,00', 'R$ 210.000,00', 'R$ 270.000,00', { selo: { texto: 'Atenção', tom: 'atencao' } }],
      ['Julho/2026', 'R$ 612.000,00', 'R$ 198.500,00', 'R$ 413.500,00', { selo: { texto: 'Em dia', tom: 'ok' } }],
    ],
  },
  '/relatorios/inadimplencia': {
    titulo: 'Relatório de inadimplência',
    descricao: 'Clientes com parcelas em atraso.',
    textoNovo: 'Novo registro',
    colunas: [
      { titulo: 'Cliente', larga: true },
      { titulo: 'Contrato' },
      { titulo: 'Dias em atraso', numerico: true },
      { titulo: 'Valor em atraso' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Ana Paula Cardoso', '#4790', 45, 'R$ 4.041,00', { selo: { texto: 'Crítico', tom: 'critico' } }],
      ['Sandra Regina Costa', '#4955', 12, 'R$ 1.486,00', { selo: { texto: 'Vencido', tom: 'vencido' } }],
      ['Carlos Eduardo Nunes', '#4602', 78, 'R$ 6.230,00', { selo: { texto: 'Crítico', tom: 'critico' } }],
      ['Fabiana Ribeiro Alves', '#4715', 5, 'R$ 1.180,00', { selo: { texto: 'Atenção', tom: 'atencao' } }],
      ['Marcos Vinícius Lima', '#4880', 30, 'R$ 2.970,00', { selo: { texto: 'Vencido', tom: 'vencido' } }],
    ],
  },
  '/relatorios/cobrancas': {
    titulo: 'Relatório de cobranças',
    descricao: 'Régua de cobrança e último contato por cliente.',
    textoNovo: 'Nova cobrança',
    colunas: [
      { titulo: 'Cliente', larga: true },
      { titulo: 'Etapa da régua' },
      { titulo: 'Último contato' },
      { titulo: 'Canal' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Ana Paula Cardoso', '3ª notificação', '27/07/2026', 'WhatsApp', { selo: { texto: 'Crítico', tom: 'critico' } }],
      ['Sandra Regina Costa', '1ª notificação', '25/07/2026', 'E-mail', { selo: { texto: 'Atenção', tom: 'atencao' } }],
      ['Carlos Eduardo Nunes', 'Negativação', '20/07/2026', 'Carta', { selo: { texto: 'Crítico', tom: 'critico' } }],
      ['Fabiana Ribeiro Alves', '1ª notificação', '26/07/2026', 'SMS', { selo: { texto: 'Atenção', tom: 'atencao' } }],
      ['Marcos Vinícius Lima', '2ª notificação', '24/07/2026', 'WhatsApp', { selo: { texto: 'Vencido', tom: 'vencido' } }],
    ],
  },
  '/relatorios/boletos': {
    titulo: 'Relatório de boletos',
    descricao: 'Boletos emitidos e sua situação de pagamento.',
    textoNovo: 'Novo boleto',
    colunas: [
      { titulo: 'Boleto' },
      { titulo: 'Cliente', larga: true },
      { titulo: 'Vencimento' },
      { titulo: 'Valor' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['000482', 'Maria das Graças Souza', '10/08/2026', 'R$ 1.416,00', { selo: { texto: 'Gerado', tom: 'info' } }],
      ['000483', 'João Batista Ferreira', '05/08/2026', 'R$ 1.291,00', { selo: { texto: 'Gerado', tom: 'info' } }],
      ['000410', 'Ana Paula Cardoso', '15/06/2026', 'R$ 1.347,00', { selo: { texto: 'Vencido', tom: 'vencido' } }],
      ['000501', 'Ricardo Alves Pereira', '10/08/2026', 'R$ 1.555,00', { selo: { texto: 'Gerado', tom: 'info' } }],
      ['000455', 'Sandra Regina Costa', '20/07/2026', 'R$ 1.486,00', { selo: { texto: 'Atenção', tom: 'atencao' } }],
    ],
  },
  '/relatorios/pix': {
    titulo: 'Relatório de Pix',
    descricao: 'Recebimentos via Pix confirmados no período.',
    textoNovo: 'Novo recebimento',
    colunas: [
      { titulo: 'Data' },
      { titulo: 'Cliente', larga: true },
      { titulo: 'Chave Pix' },
      { titulo: 'Valor' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['28/07/2026', 'Maria das Graças Souza', 'CPF', 'R$ 1.416,00', { selo: { texto: 'Em dia', tom: 'ok' } }],
      ['27/07/2026', 'Ricardo Alves Pereira', 'E-mail', 'R$ 1.555,00', { selo: { texto: 'Em dia', tom: 'ok' } }],
      ['26/07/2026', 'João Batista Ferreira', 'Aleatória', 'R$ 1.291,00', { selo: { texto: 'Em dia', tom: 'ok' } }],
      ['25/07/2026', 'Fernanda Lima Souza', 'CPF', 'R$ 980,00', { selo: { texto: 'Em dia', tom: 'ok' } }],
      ['24/07/2026', 'Marcos Vinícius Lima', 'Telefone', 'R$ 2.970,00', { selo: { texto: 'Em dia', tom: 'ok' } }],
    ],
  },
  '/relatorios/corretores': {
    titulo: 'Relatório de corretores',
    descricao: 'Desempenho de vendas por corretor no mês.',
    textoNovo: 'Novo corretor',
    colunas: [
      { titulo: 'Corretor', larga: true },
      { titulo: 'CRECI' },
      { titulo: 'Vendas no mês', numerico: true },
      { titulo: 'Comissão gerada' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Ricardo Alves Pereira', 'CRECI-RR 1234', 8, 'R$ 24.600,00', { selo: { texto: 'Em dia', tom: 'ok' } }],
      ['Patrícia Gomes', 'CRECI-RR 2201', 5, 'R$ 15.900,00', { selo: { texto: 'Em dia', tom: 'ok' } }],
      ['Rafael Nunes', 'CRECI-RR 3087', 2, 'R$ 6.200,00', { selo: { texto: 'Atenção', tom: 'atencao' } }],
      ['Fernanda Lima Souza', 'CRECI-RR 1876', 9, 'R$ 28.400,00', { selo: { texto: 'Em dia', tom: 'ok' } }],
      ['Lucas Andrade', 'CRECI-RR 2450', 0, 'R$ 0,00', { selo: { texto: 'Inativo', tom: 'neutro' } }],
    ],
  },
  '/relatorios/comissoes': {
    titulo: 'Relatório de comissões',
    descricao: 'Comissões geradas por venda e corretor.',
    textoNovo: 'Nova comissão',
    colunas: [
      { titulo: 'Corretor', larga: true },
      { titulo: 'Contrato' },
      { titulo: 'Valor da venda' },
      { titulo: 'Comissão' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Ricardo Alves Pereira', '#5108', 'R$ 112.000,00', 'R$ 3.360,00', { selo: { texto: 'Em dia', tom: 'ok' } }],
      ['Patrícia Gomes', '#5012', 'R$ 62.000,00', 'R$ 1.860,00', { selo: { texto: 'Em dia', tom: 'ok' } }],
      ['Fernanda Lima Souza', '#4955', 'R$ 74.300,00', 'R$ 2.229,00', { selo: { texto: 'Gerado', tom: 'info' } }],
      ['Rafael Nunes', '#4821', 'R$ 85.000,00', 'R$ 2.550,00', { selo: { texto: 'Atenção', tom: 'atencao' } }],
      ['Lucas Andrade', '#4790', 'R$ 48.500,00', 'R$ 1.455,00', { selo: { texto: 'Vencido', tom: 'vencido' } }],
    ],
  },
  '/relatorios/lotes': {
    titulo: 'Relatório de lotes',
    descricao: 'Situação dos lotes por quadra e loteamento.',
    textoNovo: 'Novo lote',
    colunas: [
      { titulo: 'Lote' },
      { titulo: 'Quadra' },
      { titulo: 'Loteamento', larga: true },
      { titulo: 'Área (m²)', numerico: true },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['12', 'B', 'Residencial Rio Branco', 360, { selo: { texto: 'Vendido', tom: 'info' } }],
      ['45', 'D', 'Portal do Cerrado', 420, { selo: { texto: 'Disponível', tom: 'ok' } }],
      ['08', 'A', 'Jardim das Palmeiras', 300, { selo: { texto: 'Reservado', tom: 'atencao' } }],
      ['23', 'C', 'Vila Nova Caracaraí', 280, { selo: { texto: 'Disponível', tom: 'ok' } }],
      ['15', 'A', 'Recanto dos Ipês', 350, { selo: { texto: 'Bloqueado', tom: 'neutro' } }],
    ],
  },
  '/relatorios/empreendimentos': {
    titulo: 'Relatório de empreendimentos',
    descricao: 'Unidades vendidas e disponíveis por empreendimento.',
    textoNovo: 'Novo empreendimento',
    colunas: [
      { titulo: 'Empreendimento', larga: true },
      { titulo: 'Loteamento' },
      { titulo: 'Vendidas', numerico: true },
      { titulo: 'Disponíveis', numerico: true },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Rio Branco Fase 1', 'Residencial Rio Branco', 120, 40, { selo: { texto: 'Em dia', tom: 'ok' } }],
      ['Rio Branco Fase 2', 'Residencial Rio Branco', 60, 100, { selo: { texto: 'Gerado', tom: 'info' } }],
      ['Jardim das Palmeiras Único', 'Jardim das Palmeiras', 145, 35, { selo: { texto: 'Em dia', tom: 'ok' } }],
      ['Portal do Cerrado Fase 1', 'Portal do Cerrado', 180, 45, { selo: { texto: 'Em dia', tom: 'ok' } }],
      ['Vila Nova Caracaraí Único', 'Vila Nova Caracaraí', 60, 36, { selo: { texto: 'Atenção', tom: 'atencao' } }],
    ],
  },
  '/relatorios/exportacao-excel': {
    titulo: 'Exportação Excel',
    descricao: 'Relatórios exportados em planilha Excel.',
    textoNovo: 'Nova exportação',
    colunas: [
      { titulo: 'Relatório', larga: true },
      { titulo: 'Formato' },
      { titulo: 'Gerado em' },
      { titulo: 'Tamanho' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Relatório de inadimplência', 'XLSX', '29/07/2026', '842 KB', { selo: { texto: 'Gerado', tom: 'info' } }],
      ['Relatório de contratos', 'XLSX', '28/07/2026', '1,2 MB', { selo: { texto: 'Gerado', tom: 'info' } }],
      ['Relatório de recebimentos', 'XLSX', '27/07/2026', '640 KB', { selo: { texto: 'Gerado', tom: 'info' } }],
      ['Relatório de comissões', 'XLSX', '25/07/2026', '310 KB', { selo: { texto: 'Gerado', tom: 'info' } }],
      ['Relatório de lotes', 'XLSX', '20/07/2026', '480 KB', { selo: { texto: 'Gerado', tom: 'info' } }],
    ],
  },
  '/relatorios/pdf': {
    titulo: 'Exportação PDF',
    descricao: 'Relatórios exportados em documento PDF.',
    textoNovo: 'Nova exportação',
    colunas: [
      { titulo: 'Relatório', larga: true },
      { titulo: 'Formato' },
      { titulo: 'Gerado em' },
      { titulo: 'Tamanho' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Relatório executivo', 'PDF', '29/07/2026', '1,8 MB', { selo: { texto: 'Gerado', tom: 'info' } }],
      ['Relatório de cobranças', 'PDF', '28/07/2026', '920 KB', { selo: { texto: 'Gerado', tom: 'info' } }],
      ['Relatório de fluxo de caixa', 'PDF', '27/07/2026', '760 KB', { selo: { texto: 'Gerado', tom: 'info' } }],
      ['Relatório de clientes', 'PDF', '24/07/2026', '540 KB', { selo: { texto: 'Gerado', tom: 'info' } }],
      ['Relatório de empreendimentos', 'PDF', '18/07/2026', '1,1 MB', { selo: { texto: 'Gerado', tom: 'info' } }],
    ],
  },
  '/loteamentos': {
    titulo: 'Loteamentos',
    descricao: 'Loteamentos registrados junto aos empreendimentos.',
    textoNovo: 'Novo loteamento',
    colunas: [
      { titulo: 'Nome', larga: true },
      { titulo: 'Cidade' },
      { titulo: 'Matrícula' },
      { titulo: 'Lotes', numerico: true },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Residencial Rio Branco', 'Boa Vista', '48.512', 320, { selo: { texto: 'Aprovado', tom: 'ok' } }],
      ['Jardim das Palmeiras', 'Rorainópolis', '22.104', 180, { selo: { texto: 'Aprovado', tom: 'ok' } }],
      ['Vila Nova Caracaraí', 'Caracaraí', '15.987', 96, { selo: { texto: 'Em análise', tom: 'info' } }],
      ['Recanto dos Ipês', 'Boa Vista', '48.998', 210, { selo: { texto: 'Aprovado', tom: 'ok' } }],
      ['Portal do Cerrado', 'Goiânia', '77.321', 450, { selo: { texto: 'Pendente', tom: 'atencao' } }],
    ],
  },
  '/loteamentos/quadras': {
    titulo: 'Quadras',
    descricao: 'Quadras cadastradas por loteamento.',
    textoNovo: 'Nova quadra',
    colunas: [
      { titulo: 'Quadra' },
      { titulo: 'Loteamento', larga: true },
      { titulo: 'Lotes', numerico: true },
      { titulo: 'Área total (m²)', numerico: true },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['A', 'Residencial Rio Branco', 40, 14400, { selo: { texto: 'Em dia', tom: 'ok' } }],
      ['B', 'Residencial Rio Branco', 36, 12960, { selo: { texto: 'Em dia', tom: 'ok' } }],
      ['C', 'Jardim das Palmeiras', 28, 8400, { selo: { texto: 'Em dia', tom: 'ok' } }],
      ['D', 'Portal do Cerrado', 52, 21840, { selo: { texto: 'Gerado', tom: 'info' } }],
      ['A', 'Vila Nova Caracaraí', 24, 6720, { selo: { texto: 'Atenção', tom: 'atencao' } }],
    ],
  },
  '/loteamentos/situacao': {
    titulo: 'Situação do lote',
    descricao: 'Situação individual de cada lote comercializado.',
    textoNovo: 'Novo lote',
    colunas: [
      { titulo: 'Lote' },
      { titulo: 'Quadra' },
      { titulo: 'Loteamento', larga: true },
      { titulo: 'Comprador' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['12', 'B', 'Residencial Rio Branco', 'João Batista Ferreira', { selo: { texto: 'Vendido', tom: 'info' } }],
      ['45', 'D', 'Portal do Cerrado', 'Ricardo Alves Pereira', { selo: { texto: 'Vendido', tom: 'info' } }],
      ['08', 'A', 'Jardim das Palmeiras', '—', { selo: { texto: 'Reservado', tom: 'atencao' } }],
      ['23', 'C', 'Vila Nova Caracaraí', '—', { selo: { texto: 'Disponível', tom: 'ok' } }],
      ['15', 'A', 'Recanto dos Ipês', '—', { selo: { texto: 'Bloqueado', tom: 'neutro' } }],
    ],
  },
  '/loteamentos/disponibilidade': {
    titulo: 'Disponibilidade',
    descricao: 'Disponibilidade de lotes por loteamento.',
    textoNovo: 'Novo registro',
    colunas: [
      { titulo: 'Loteamento', larga: true },
      { titulo: 'Total de lotes', numerico: true },
      { titulo: 'Vendidos', numerico: true },
      { titulo: 'Disponíveis', numerico: true },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['Residencial Rio Branco', 320, 210, 110, { selo: { texto: 'Em dia', tom: 'ok' } }],
      ['Jardim das Palmeiras', 180, 145, 35, { selo: { texto: 'Atenção', tom: 'atencao' } }],
      ['Vila Nova Caracaraí', 96, 60, 36, { selo: { texto: 'Atenção', tom: 'atencao' } }],
      ['Recanto dos Ipês', 210, 180, 30, { selo: { texto: 'Atenção', tom: 'atencao' } }],
      ['Portal do Cerrado', 450, 300, 150, { selo: { texto: 'Em dia', tom: 'ok' } }],
    ],
  },
  '/auditoria': {
    titulo: 'Trilha de auditoria',
    descricao: 'Ações registradas pelos usuários do sistema.',
    textoNovo: 'Novo registro',
    colunas: [
      { titulo: 'Data/Hora' },
      { titulo: 'Usuário' },
      { titulo: 'Ação' },
      { titulo: 'Registro', larga: true },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['29/07/2026 09:15', 'Lucas Andrade', 'Alteração', 'Contrato #4821', { selo: { texto: 'Gerado', tom: 'info' } }],
      ['29/07/2026 08:40', 'Fernanda Lima', 'Exclusão', 'Corretor Rafael Nunes', { selo: { texto: 'Crítico', tom: 'critico' } }],
      ['28/07/2026 17:22', 'Marcos Vinícius', 'Criação', 'Cliente Sandra Regina Costa', { selo: { texto: 'Em dia', tom: 'ok' } }],
      ['28/07/2026 15:10', 'Patrícia Gomes', 'Alteração', 'Lote 45 Quadra D', { selo: { texto: 'Gerado', tom: 'info' } }],
      ['27/07/2026 11:05', 'Rafael Nunes', 'Login', 'Sistema', { selo: { texto: 'Inativo', tom: 'neutro' } }],
    ],
  },
  '/auditoria/historico': {
    titulo: 'Histórico de alterações',
    descricao: 'Alterações realizadas em registros do sistema.',
    textoNovo: 'Novo registro',
    colunas: [
      { titulo: 'Data/Hora' },
      { titulo: 'Registro', larga: true },
      { titulo: 'Campo alterado' },
      { titulo: 'Valor anterior' },
      { titulo: 'Situação' },
    ],
    linhas: [
      ['29/07/2026 09:15', 'Contrato #4821', 'Valor da parcela', 'R$ 1.380,00', { selo: { texto: 'Atenção', tom: 'atencao' } }],
      ['28/07/2026 14:32', 'Cliente Maria das Graças Souza', 'Endereço', 'Rua Sete de Setembro, 120', { selo: { texto: 'Gerado', tom: 'info' } }],
      ['27/07/2026 10:08', 'Lote 08 Quadra A', 'Situação', 'Disponível', { selo: { texto: 'Gerado', tom: 'info' } }],
      ['26/07/2026 16:45', 'Corretor Ricardo Alves Pereira', 'Comissão', '3%', { selo: { texto: 'Atenção', tom: 'atencao' } }],
      ['25/07/2026 09:20', 'Contrato #4955', 'Vencimento', '20/07/2026', { selo: { texto: 'Vencido', tom: 'vencido' } }],
    ],
  },
};

export default telas;
